In [5]:
import numpy as np
import pandas as pd
import glob
import musclebeachtools as mbt
import samb_work.dimtools as dimt
import os

from natsort import natsorted
from pathlib import Path
import joblib
from datetime import datetime
from matplotlib.widgets import SpanSelector, Button
from matplotlib.colors import PowerNorm
from PIL import Image
from tqdm import tqdm
import tkinter as tk
from tkinter import simpledialog
from IPython.display import display, clear_output
import ipywidgets as widgets

import sahara_work as saw
import musclebeachtools as mbt
import neuraltoolkit as ntk
import matplotlib.pyplot as plt

# from james_work import crit_utils as cu
from sahara_work import crit_utils as cu
%load_ext autoreload
%autoreload 2
import os
NCPU = "4"
os.environ['OMP_NUM_THREADS'] = '4'
os.environ['OPENBLAS_NUM_THREADS'] = '4'
os.environ['MKL_NUM_THREADS'] = '4'
os.environ['VECLIB_MAXIMUM_THREADS'] = '4'
os.environ['NUMEXPR_NUM_THREADS'] = '4'
plt.rcParams['pdf.fonttype'] = 42
plt.rcParams.update({'font.family':'DejaVu Sans'})
#import swifter

/hlabhome/wg-mjames/.conda/envs/james_test_copy/lib/python3.8/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
/hlabhome/wg-mjames/.conda/envs/james_test_copy/lib/python3.8/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index

In [21]:
def get_100_isi_timings(isis):
    output = []
    if len(isis):
        #print(isis[0], isis[-1])
        for time_ind in range(0,len(isis)-1, 100):
            output.append(isis[time_ind])
        output.append(isis[-1])
    return output

In [22]:
def get_sleeptimes(sleepnpy):
    #deal with sleepybois
    sleep_states = np.zeros((2,0))
    sleeps = np.load(sleepnpy)
    timestamps = (np.nonzero(np.diff(sleeps))[0]+1)*4
    time_ind = (timestamps/4)-1
    states = sleeps[time_ind.astype(int)]
    s = np.array(states)
    t = np.stack((timestamps,s))
    sleep_states = np.concatenate((sleep_states,t), axis =1)
    start_time = np.append([0],sleep_states[0,:-1])
    stop_time = sleep_states[0,:]
    sleepstate = sleep_states[1,:]
    sleepdf = pd.DataFrame({'start_time': start_time,'stop_time': stop_time,'sleepstate': sleepstate})
    return(sleepdf)

# make into a function
def get_isi_df(cell_dir, sleepnpy_dir, animal_name, fr_cutoff=50):
    animal_name = animal_name.lower()
    cells = np.load(cell_dir, allow_pickle=True)
    # good_cells = [cell for cell in cells if cell.quality < 3 and cell.plotFR(binsz=cell.end_time, lplot=0, lonoff=0)[0][0] < fr_cutoff and cell.presence_ratio() > .99]

    # rstart time is the same
    start_time = cells[0].rstart_time
    start_time = datetime.strptime(start_time, '%Y-%m-%d_%H-%M-%S')
    # cu = james_work crit_utils
    birthday = cu.get_birthday(animal_name)
    age = start_time - birthday
    # convert age to decimal days
    age = age.days + age.seconds/(24*60*60)
    geno = cu.get_genotype(animal_name)
    sex = cu.get_sex(animal_name)
    sleep_df = get_sleeptimes(sleepnpy_dir)
    print('got initial info')
    # cell_dir = '/media/HlabShare/Clustering_Data/ZBR00114/12hr_bins/zbr114_04262024/0_12/probe2/co/H_2024-04-26_17-25-37_2024-04-27_05-20-38_neurons_group0.npy'
    # sleepnpy_dir = '/media/HlabShare/Ben_work/data/ZBR114/0426/0_12/ZBR114_0426_0_12_sleep.npy'
    record_time = sleepnpy_dir.split('/')
    epoch = record_time[-3] + '_' + record_time[-2]
    # display(sleep_df)
    # brain_region = [cu.get_regions(animal_name)]

    # cell_type and peak_latency are not the same for all cells
    # cell_type = cells[0].cell_type
    # peak_latency = cells[0].peaklatency


    # loop through each cell of good_cells
    # get the spike times for each cell
    spike_time_and_state = pd.DataFrame()
    
    for neuron_index, neuron in enumerate(cells):
        neuron_spike_times = neuron.spike_time_sec
        for index, row in sleep_df.iterrows():
            start_time = row['start_time']
            stop_time = row['stop_time']
            sleep_state = row['sleepstate']
            cell_spikes = neuron_spike_times[(neuron_spike_times >= start_time) & (neuron_spike_times <= stop_time)]

            spike_time_and_state = pd.concat([spike_time_and_state, pd.DataFrame({'cell_no': neuron_index,
                                                                                  'spikes': [cell_spikes], 
                                                                                  'sleep_state': sleep_state, 
                                                                                  'cell_type': neuron.cell_type, 
                                                                                  'peak_latency': neuron.peaklatency, 
                                                                                  'region': neuron.region,
                                                                                  'length': int(stop_time-start_time)})])

    # change 4, 5 to 1 first
    # merging mircoarousal and quiet wake into wake
    #spike_time_and_state['sleep_state'] = spike_time_and_state['sleep_state'].replace(4, 1)
    spike_time_and_state['sleep_state'] = spike_time_and_state['sleep_state'].replace(5, 1)

    #display(spike_time_and_state)

    # separate the dataframes by cell number
    cells = spike_time_and_state['cell_no'].unique()

    # display(cells)

    cell_isi = pd.DataFrame()

    for cell_index, cell in enumerate(cells):
        cell_df = spike_time_and_state[spike_time_and_state['cell_no'] == cell_index]

#         print(cell_index)
#         print(len(cell_df))

        cell_type = cell_df['cell_type'].iloc[0]
        peak_latency = cell_df['peak_latency'].iloc[0]
        brain_region = cell_df['region'].iloc[0]

        wake = cell_df[cell_df['sleep_state'] == 1]
        nrem = cell_df[cell_df['sleep_state'] == 2]
        rem = cell_df[cell_df['sleep_state'] == 3]
        ma = cell_df[cell_df['sleep_state']==4]

        wake_isi = []
        nrem_isi = []
        rem_isi = []
        ma_isi = []
        wake_isi_timings, nrem_isi_timings, rem_isi_timings = [],[],[]
        wake_lens, nrem_lens, rem_lens, ma_lens = [],[],[], []
        for index, row in wake.iterrows():
            spikes = row['spikes']
            isi = np.diff(spikes)
            wake_isi.append(isi)
            wake_isi_timings.append(get_100_isi_timings(spikes))
            wake_lens.append(row['length'])
        for index, row in nrem.iterrows():
            spikes = row['spikes']
            isi = np.diff(spikes)
            nrem_isi.append(isi)
            nrem_isi_timings.append(get_100_isi_timings(spikes))
            nrem_lens.append(row['length'])
        for index, row in rem.iterrows():
            spikes = row['spikes']
            isi = np.diff(spikes)
            rem_isi.append(isi)
            rem_isi_timings.append(get_100_isi_timings(spikes))
            rem_lens.append(row['length'])
#         for index, row in ma.iterrows():
#             spikes = row['spikes']
#             isi = np.diff(spikes)
#             ma_isi.append(isi)
#             ma_lens.append(row['length'])

        cell_isi = pd.concat([cell_isi, pd.DataFrame({
                                                            'animal': animal_name,
                                                            'epoch': epoch,
                                                            'age':age,
                                                            'sex': sex,
                                                            'geno': geno,
                                                            'brain_region': brain_region,
                                                            'cell_type': cell_type,
                                                            'peak_latency': peak_latency,
                                                            'cell_no': cell_index,
                                                            'wake_isi': [wake_isi],
                                                            'nrem_isi': [nrem_isi],
                                                            'rem_isi': [rem_isi],
                                                            #'ma_isi': [ma_isi],
                                                            'wake_lens': [wake_lens],
                                                            'nrem_lens': [nrem_lens],
                                                            'rem_lens': [rem_lens],
                                                            'wake_timings': [wake_isi_timings],
                                                            'nrem_timings': [nrem_isi_timings],
                                                            'rem_timings': [rem_isi_timings],
                                                            #'ma_lens': [ma_lens]
                                                            })])

    # reset index to cell_no
    cell_isi = cell_isi.reset_index(drop=True)
    #display(cell_isi)
    return cell_isi

# function to get cell_dir and sleepnpy_dir based on animal name
def get_dirs(animal_name, cell_base_dir, sleepnpy_base_dir):
    character_code = animal_name[:3]
    character_code = character_code.upper()
    number_code = animal_name[-3:]
    # add zeros in front of number_code to make the length of 5
    number_code = number_code.zfill(5)
    # '/media/HlabShare/appps1_cortical_communication_samb/appps1/data/ZBR117/0529/0_12/ZBR117_0529_0_12_singleunits.npy'
    cell_dir = natsorted(glob.glob(f'{cell_base_dir}{animal_name.lower()}/*/*_*/*_singleunits.npy'))
    sleepnpy_dir = natsorted(glob.glob(f'{sleepnpy_base_dir}{animal_name.upper()}/*/*_*/*_sleep.npy'))
    return cell_dir, sleepnpy_dir

animal_names = [
    'caf69',
    'caf71',
    'caf73',
    'caf74',
    'caf75',
    'caf77',
    'caf81',
    'caf82',
    'zbr106',
    'zbr113',
    'zbr114',
    'zbr117',
    'zbr118',
    'zbr119',
    'bth90',
    'bth95',
    'bth100'
    ]
print(len(animal_names))

cell_base_dir = '/media/HlabShare/appps1_cortical_communication_samb/appps1/data/'
sleepnpy_base_dir = '/media/HlabShare/appps1_cortical_communication_samb/appps1/data/'
all_animal_isi_df = pd.DataFrame()
for animal_name in animal_names:
    print('Working on', animal_name)
    cell_dir, sleepnpy_dir = get_dirs(animal_name, cell_base_dir, sleepnpy_base_dir)
    print(f"Has {len(cell_dir)} files to go through")
    for i in range(len(cell_dir)):
        isi_df = get_isi_df(cell_dir[i], sleepnpy_dir[i], animal_name)
        display(isi_df)
        all_animal_isi_df = pd.concat([all_animal_isi_df, isi_df], ignore_index=True)
display(all_animal_isi_df)

17
Working on caf69
Has 3 files to go through
got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,caf69,1228_0_12,358.152546,F,wt,ACC,RSU,0.68,0,"[[0.00592, 0.00132, 0.004360000000000001, 0.02...","[[0.15272000000004482, 0.07171999999991385, 0....","[[0.15104000000019369, 0.11567999999988388, 0....","[3320, 320, 20, 1708, 588, 92, 740, 252, 68, 3...","[520, 440, 40, 240, 180, 200, 180, 220, 180, 6...","[160, 40, 100, 20, 40, 60, 100, 40, 108, 80, 3...","[[0.00532, 8.30984, 16.46344, 25.3846, 37.0028...","[[3320.05296, 3328.55344, 3339.40532, 3345.584...","[[3841.05772, 3868.16824, 3891.42572, 3909.411..."
1,caf69,1228_0_12,358.152546,F,wt,ACC,RSU,0.68,1,"[[0.12224, 6.87172, 1.7081599999999995, 2.1617...","[[14.897280000000137, 1.6376399999999194, 6.17...","[[3.8209999999999127, 4.546280000000024, 3.097...","[3320, 320, 20, 1708, 588, 92, 740, 252, 68, 3...","[520, 440, 40, 240, 180, 200, 180, 220, 180, 6...","[160, 40, 100, 20, 40, 60, 100, 40, 108, 80, 3...","[[4e-05, 219.53304, 509.02504, 573.5778, 737.8...","[[3329.31148, 3785.66544], [4008.16452, 4438.9...","[[3859.45592, 3980.94744], [4470.14316, 4478.7..."
2,caf69,1228_0_12,358.152546,F,wt,ACC,RSU,0.52,2,"[[0.06476000000000001, 0.017119999999999996, 0...","[[0.05519999999978609, 0.8142000000002554, 0.0...","[[0.05375999999978376, 0.286200000000008, 0.08...","[3320, 320, 20, 1708, 588, 92, 740, 252, 68, 3...","[520, 440, 40, 240, 180, 200, 180, 220, 180, 6...","[160, 40, 100, 20, 40, 60, 100, 40, 108, 80, 3...","[[0.01684, 22.50024, 46.03396, 66.695, 89.9888...","[[3320.1932, 3372.29616, 3432.87716, 3497.7676...","[[3840.76872, 3894.55876, 3944.32072, 3989.872..."
3,caf69,1228_0_12,358.152546,F,wt,ACC,RSU,0.52,3,"[[0.24439999999999998, 0.27224000000000004, 0....","[[2.0253600000000915, 0.87920000000031, 0.7080...","[[0.6291599999999562, 0.11724000000003798, 0.7...","[3320, 320, 20, 1708, 588, 92, 740, 252, 68, 3...","[520, 440, 40, 240, 180, 200, 180, 220, 180, 6...","[160, 40, 100, 20, 40, 60, 100, 40, 108, 80, 3...","[[0.00892, 22.6154, 48.60976, 73.74956, 91.015...","[[3320.42208, 3368.56088, 3431.02976, 3503.225...","[[3840.58268, 3899.72988, 3942.88864, 3976.861..."
4,caf69,1228_0_12,358.152546,F,wt,ACC,RSU,0.48,4,"[[0.15028000000000002, 0.34468000000000004, 0....","[[0.59996000000001, 0.4675600000000486, 0.8568...","[[2.2804799999998977, 0.46628000000009706, 1.0...","[3320, 320, 20, 1708, 588, 92, 740, 252, 68, 3...","[520, 440, 40, 240, 180, 200, 180, 220, 180, 6...","[160, 40, 100, 20, 40, 60, 100, 40, 108, 80, 3...","[[0.25464, 28.47056, 53.57136, 85.74888, 91.68...","[[3320.71772, 3373.96056, 3425.57584, 3523.176...","[[3841.0414, 3907.79736, 3946.2996, 3986.7532,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,caf69,1228_0_12,358.152546,F,wt,CA1,FS,0.16,108,"[[34.46592, 6.195040000000006, 4.6371599999999...","[[2.4536400000001777, 126.5286799999999], [53....","[[], [], [], [], [], [], [0.8602799999998751],...","[3320, 320, 20, 1708, 588, 92, 740, 252, 68, 3...","[520, 440, 40, 240, 180, 200, 180, 220, 180, 6...","[160, 40, 100, 20, 40, 60, 100, 40, 108, 80, 3...","[[32.80516, 3241.5028], [4615.8082, 4616.21448...","[[3585.84156, 3714.82388], [4004.17008, 4179.7...","[[], [4462.15176], [], [], [], [], [6402.35072..."
109,caf69,1228_0_12,358.152546,F,wt,CA1,FS,0.16,109,"[[0.011119999999999991, 0.25624, 1.09736000000...","[[0.00864000000001397, 0.017479999999977736, 0...","[[0.6227999999996428, 0.01224000000001979, 0.0...","[3320, 320, 20, 1708, 588, 92, 740, 252, 68, 3...","[520, 440, 40, 240, 180, 200, 180, 220, 180, 6...","[160, 40, 100, 20, 40, 60, 100, 40, 108, 80, 3...","[[0.16508, 22.5774, 66.36284, 107.02832, 139.5...","[[3321.97504, 3369.055, 3399.23044, 3427.95528...","[[3840.5284, 3865.65348, 3884.4952, 3893.80336..."
110,caf69,1228_0_12,358.152546,F,wt,CA1,FS,0.36,110,"[[34.998279999999994, 0.0036400000000043065, 9...","[[196.11527999999998], [], [], [], [], [], [],...","[[], [], [], [], [], [], [], [0.54920000000129...","[3320, 320, 20, 1708, 588, 92, 740, 252, 68, 3...","[520, 440, 40, 240, 180, 200, 180, 220, 180, 6...","[160, 40, 100, 20, 40, 60, 100, 40, 108, 80, 3...","[[23.7944, 965.23472, 3274.18148], [], [], [67...","[[3582.47956, 3778.59484], [4212.19708], [], [...","[[], [], [], [], [], [], [], [8600.06988, 8637..."
111,caf69,1228_0_12,358.152546,F,wt,CA1,FS,0.24,111,"[[0.05284000000000333, 127.84891999999996, 3.3...","[[], [], [], [], [], [], [], [], [6.2287200000...","[[], [], [], [], [], [], [], [0.02023999999983...","[3320, 320, 20, 1708, 588, 92, 740, 252, 68, 3...","[520, 440, 40, 240, 180, 200, 180, 220, 180, 6...","[160, 40, 100, 20, 40, 60, 100, 40, 108, 80, 3...","[[442.77108, 2270.36436], [4803.15776], [], [6...","[[], [], [], [], [], [], [5741.02588], [], [61...","[[], [], [], [], [], [], [], [8601.54016, 8635..."
112,caf69,1228_0_12,358.152546,F,wt,CA1,RSU,0.72,112,"[[0.0021599999999999953, 0.05448, 0.0106799999...","[[0.01224000000001979, 0.003440000000409782, 0...","[[0.10072000000036496, 0.09819999999990614, 0....","[3320, 320, 20, 1708, 588, 92, 740, 252, 68, 3...","[520, 440, 40, 240, 180, 200, 180, 220, 180, 6...","[160, 40, 100, 20, 40, 60, 100, 40, 108, 80, 3...","[[0.09692, 5.22988, 10.21908, 15.25, 20.21604,...","[[3320.14076, 3325.27612, 3330.55812, 3336.137...","[[3840.1946, 3844.824, 3849.7016, 3855.1738, 3..."

got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,caf69,1230_0_12,360.350069,F,wt,ACC,RSU,0.68,0,"[[0.008239999999999997, 0.12388000000000002, 0...","[[0.15499999999997272, 0.026360000000067885, 0...","[[0.1572000000001026, 0.2180799999998726, 0.20...","[464, 32, 4, 28, 132, 12, 48, 32, 76, 80, 4, 6...","[440, 800, 380, 240, 60, 540, 500, 400, 560, 1...","[80, 120, 100, 120, 120, 40, 40, 120, 160, 36,...","[[0.06716, 6.26484, 10.93276, 16.27832, 21.464...","[[1400.03316, 1409.95224, 1419.47252, 1431.124...","[[1840.10032, 1850.59672, 1862.92868, 1868.039..."
1,caf69,1230_0_12,360.350069,F,wt,ACC,RSU,0.64,1,"[[0.03216, 0.024640000000000002, 0.00299999999...","[[0.010199999999940701, 0.03920000000016444, 0...","[[0.007920000000012806, 0.0768399999999474, 0....","[464, 32, 4, 28, 132, 12, 48, 32, 76, 80, 4, 6...","[440, 800, 380, 240, 60, 540, 500, 400, 560, 1...","[80, 120, 100, 120, 120, 40, 40, 120, 160, 36,...","[[4e-05, 3.97644, 9.08664, 13.49404, 18.98232,...","[[1400.1804, 1406.86436, 1415.66032, 1421.9640...","[[1840.07752, 1845.03056, 1854.02816, 1861.824..."
2,caf69,1230_0_12,360.350069,F,wt,ACC,RSU,0.60,2,"[[0.07152, 0.04124, 0.34524, 0.486200000000000...","[[0.03435999999987871, 0.024040000000013606, 0...","[[0.4557200000001558, 0.01756000000000313, 0.1...","[464, 32, 4, 28, 132, 12, 48, 32, 76, 80, 4, 6...","[440, 800, 380, 240, 60, 540, 500, 400, 560, 1...","[80, 120, 100, 120, 120, 40, 40, 120, 160, 36,...","[[0.00068, 19.50456, 36.82864, 82.88096, 127.8...","[[1400.07176, 1441.48528, 1497.01032, 1555.473...","[[1840.08784, 1868.06584, 1892.7318, 1919.4996..."
3,caf69,1230_0_12,360.350069,F,wt,ACC,RSU,0.64,3,"[[0.003239999999999993, 0.11176, 0.30811999999...","[[0.008000000000038199, 0.2400399999999081, 0....","[[0.08047999999985223, 0.06144000000017513, 0....","[464, 32, 4, 28, 132, 12, 48, 32, 76, 80, 4, 6...","[440, 800, 380, 240, 60, 540, 500, 400, 560, 1...","[80, 120, 100, 120, 120, 40, 40, 120, 160, 36,...","[[0.07208, 15.09396, 40.64872, 155.25012, 193....","[[1400.2988, 1627.93472, 1837.92856], [1920.56...","[[1840.04204, 1891.45236, 1919.93704], [2721.2..."
4,caf69,1230_0_12,360.350069,F,wt,ACC,RSU,0.64,4,"[[0.0022000000000000075, 0.021079999999999988,...","[[0.1311599999999089, 0.007160000000112632, 0....","[[0.14148000000000138, 0.13011999999980617, 0....","[464, 32, 4, 28, 132, 12, 48, 32, 76, 80, 4, 6...","[440, 800, 380, 240, 60, 540, 500, 400, 560, 1...","[80, 120, 100, 120, 120, 40, 40, 120, 160, 36,...","[[0.06712, 13.9256, 26.83008, 86.28036, 152.70...","[[1400.29888, 1490.87144, 1656.444, 1839.95796...","[[1840.18404, 1882.1058, 1915.54608], [2720.55..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,caf69,1230_0_12,360.350069,F,wt,CA1,FS,0.24,98,"[[0.08600000000000001, 0.007719999999999991, 0...","[[0.038840000000163855, 0.03971999999998843, 0...","[[0.024840000000040163, 0.015079999999898064, ...","[464, 32, 4, 28, 132, 12, 48, 32, 76, 80, 4, 6...","[440, 800, 380, 240, 60, 540, 500, 400, 560, 1...","[80, 120, 100, 120, 120, 40, 40, 120, 160, 36,...","[[4e-05, 7.55952, 13.87992, 21.56788, 29.29604...","[[1400.00696, 1407.1888, 1411.57212, 1419.9694...","[[1840.03044, 1844.78644, 1851.2142, 1857.9278..."
99,caf69,1230_0_12,360.350069,F,wt,CA1,FS,0.24,99,"[[0.13440000000000002, 0.41267999999999994, 0....","[[0.5940000000000509, 0.04048000000011598, 1.1...","[[0.07395999999994274, 0.048800000000028376, 0...","[464, 32, 4, 28, 132, 12, 48, 32, 76, 80, 4, 6...","[440, 800, 380, 240, 60, 540, 500, 400, 560, 1...","[80, 120, 100, 120, 120, 40, 40, 120, 160, 36,...","[[0.05336, 4.73884, 18.24964, 25.60804, 27.609...","[[1400.4026, 1423.42572, 1440.73824, 1460.3150...","[[1840.0506, 1855.24728, 1871.2616, 1880.62536..."
100,caf69,1230_0_12,360.350069,F,wt,CA1,RSU,0.84,100,"[[0.06183999999999999, 0.42504, 0.214960000000...","[[0.19707999999991443, 0.10860000000002401, 0....","[[0.4111199999999826, 0.9209200000000237, 0.90...","[464, 32, 4, 28, 132, 12, 48, 32, 76, 80, 4, 6...","[440, 800, 380, 240, 60, 540, 500, 400, 560, 1...","[80, 120, 100, 120, 120, 40, 40, 120, 160, 36,...","[[0.08324, 21.71924, 44.54308, 66.46516, 95.27...","[[1400.06224, 1440.43956, 1495.84016, 1577.304...","[[1840.45996, 1889.55208, 1919.62636], [2721.3..."
101,caf69,1230_0_12,360.350069,F,wt,CA1,RSU,0.92,101,"[[0.13047999999999998, 0.08556000000000002, 0....","[[0.02476000000001477, 0.17207999999982349, 0....","[[0.04827999999997701, 0.013800000000173895, 0...","[464, 32, 4, 28, 132, 12, 48, 32, 76, 80, 4, 6...","[440, 800, 380, 240, 60, 540, 500, 400, 560, 1...","[80, 120, 100, 120, 120, 40, 40, 120, 160, 36,...","[[0.08716, 8.01516, 16.46572, 25.32344, 34.401...","[[1400.08696, 1408.7212, 1416.97932, 1426.0806...","[[1840.16376, 1848.88796, 1858.06796, 1868.316..."
102,caf69,1230_0_12,360.350069,F,wt,CA1,RSU,0.80,102,"[[0.004519999999999999, 0.10568, 0.20664, 0.03...","[[0.15059999999994034, 0.2617600000000948, 0.2...","[[0.010480000000143264, 0.02803999999991902, 0...","[464, 32, 4, 28, 132, 12, 48, 32, 76, 80, 4, 6...","[440, 800, 380, 240, 60, 540, 500, 400, 560, 1...","[80, 120, 100, 120, 120, 40, 40, 120, 160, 36,...","[[0.00576, 10.63088, 21.55996, 31.04036, 39.70...","[[1400.30224, 1408.8294, 1416.41176, 1422.8089...","[[1840.07072, 1844.33296, 1851.8426, 1858.8008..."

got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,caf69,1230_12_24,360.850081,F,wt,ACC,RSU,0.64,0,"[[0.18736000000000003, 0.0012800000000000034, ...","[[0.1286800000000312, 0.2014799999999468, 0.00...","[[0.04760000000078435, 0.3038799999994808, 0.9...","[240, 160, 60, 128, 84, 4, 320, 868, 12, 600, ...","[1120, 1840, 180, 680, 180, 280, 260, 880, 520...","[60, 80, 40, 100, 140, 80, 120, 160, 120, 180,...","[[0.13892, 21.90044, 49.18428, 67.02052, 94.44...","[[880.0932, 908.21092, 939.01344, 956.186, 971...","[[4160.09632, 4193.68148, 4219.94064], [4400.2..."
1,caf69,1230_12_24,360.850081,F,wt,ACC,RSU,0.68,1,"[[0.17903999999999998, 0.03844000000000003, 0....","[[0.08984000000009473, 0.055959999999913634, 0...","[[0.04863999999997759, 0.2153200000002471, 0.0...","[240, 160, 60, 128, 84, 4, 320, 868, 12, 600, ...","[1120, 1840, 180, 680, 180, 280, 260, 880, 520...","[60, 80, 40, 100, 140, 80, 120, 160, 120, 180,...","[[0.10896, 9.09868, 20.76652, 36.28616, 48.231...","[[880.08328, 894.67264, 904.75172, 915.33948, ...","[[4160.19768, 4174.8644, 4186.82012, 4202.2528..."
2,caf69,1230_12_24,360.850081,F,wt,ACC,RSU,0.56,2,"[[0.002559999999999951, 0.01920000000000005, 0...","[[0.4053199999999606, 1.0171200000000908, 0.23...","[[0.5313999999998487, 0.24567999999999302, 2.2...","[240, 160, 60, 128, 84, 4, 320, 868, 12, 600, ...","[1120, 1840, 180, 680, 180, 280, 260, 880, 520...","[60, 80, 40, 100, 140, 80, 120, 160, 120, 180,...","[[0.38052, 89.61052, 190.95164, 238.221], [272...","[[880.56696, 941.78612, 977.60968, 1010.96676,...","[[4161.39804, 4219.78984], [4402.63896, 4477.5..."
3,caf69,1230_12_24,360.850081,F,wt,ACC,RSU,0.48,3,"[[0.1412, 0.032200000000000006, 0.066240000000...","[[0.13560000000006767, 2.264799999999923, 0.21...","[[2.531079999999747, 0.12831999999980326, 0.71...","[240, 160, 60, 128, 84, 4, 320, 868, 12, 600, ...","[1120, 1840, 180, 680, 180, 280, 260, 880, 520...","[60, 80, 40, 100, 140, 80, 120, 160, 120, 180,...","[[0.18512, 83.80344, 179.555, 239.73936], [272...","[[880.32876, 934.98396, 980.92452, 1031.26084,...","[[4162.79644, 4215.862], [4403.55856, 4479.457..."
4,caf69,1230_12_24,360.850081,F,wt,ACC,RSU,0.60,4,"[[0.02679999999999999, 0.002840000000000009, 0...","[[2.4027999999999565, 0.18604000000004817, 0.0...","[[0.10267999999996391, 0.9769999999998618, 0.2...","[240, 160, 60, 128, 84, 4, 320, 868, 12, 600, ...","[1120, 1840, 180, 680, 180, 280, 260, 880, 520...","[60, 80, 40, 100, 140, 80, 120, 160, 120, 180,...","[[0.34636, 54.34036, 178.802, 233.04332], [272...","[[880.21284, 955.414, 990.77704, 1026.17852, 1...","[[4161.71068, 4219.3326], [4400.30232, 4476.90..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,caf69,1230_12_24,360.850081,F,wt,CA1,RSU,1.16,151,"[[0.0024400000000000255, 0.00627999999999998, ...","[[0.025319999999965148, 0.012320000000045184, ...","[[0.009720000000015716, 0.033280000000559085, ...","[240, 160, 60, 128, 84, 4, 320, 868, 12, 600, ...","[1120, 1840, 180, 680, 180, 280, 260, 880, 520...","[60, 80, 40, 100, 140, 80, 120, 160, 120, 180,...","[[0.14916, 16.96504, 29.65144, 40.43144, 61.21...","[[880.09252, 894.97804, 911.60024, 915.41852, ...","[[4160.01672, 4166.88364, 4173.26788, 4182.941..."
152,caf69,1230_12_24,360.850081,F,wt,CA1,RSU,1.00,152,"[[0.10776, 0.011160000000000003, 0.03587999999...","[[0.007439999999974134, 0.08691999999996369, 0...","[[0.012400000000525324, 0.013599999999314605, ...","[240, 160, 60, 128, 84, 4, 320, 868, 12, 600, ...","[1120, 1840, 180, 680, 180, 280, 260, 880, 520...","[60, 80, 40, 100, 140, 80, 120, 160, 120, 180,...","[[0.056, 7.75312, 14.05216, 20.2554, 27.2086, ...","[[880.07528, 885.93164, 892.60188, 898.38172, ...","[[4160.01664, 4163.90968, 4169.2696, 4174.6825..."
153,caf69,1230_12_24,360.850081,F,wt,CA1,RSU,0.92,153,"[[0.05124, 0.07404, 0.05124000000000001, 0.083...","[[0.025239999999939755, 0.4601599999999735, 0....","[[0.05871999999999389, 0.0122799999999188, 0.0...","[240, 160, 60, 128, 84, 4, 320, 868, 12, 600, ...","[1120, 1840, 180, 680, 180, 280, 260, 880, 520...","[60, 80, 40, 100, 140, 80, 120, 160, 120, 180,...","[[4e-05, 6.39956, 13.85064, 19.19524, 26.66008...","[[880.08684, 886.10796, 892.176, 898.57236, 90...","[[4160.11024, 4165.8288, 4171.31712, 4178.3822..."
154,caf69,1230_12_24,360.850081,F,wt,CA1,RSU,1.08,154,"[[0.11236000000000002, 0.34975999999999996, 0....","[[0.19704000000001543, 0.2617199999999684, 0.0...","[[0.17644000000018423, 0.010079999999106803, 0...","[240, 160, 60, 128, 84, 4, 320, 868, 12, 600, ...","[1120, 1840, 180, 680, 180, 280, 260, 880, 520...","[60, 80, 40, 100, 140, 80, 120, 160, 120, 180,...","[[0.1624, 20.36024, 45.24216, 74.41328, 94.078...","[[880.11384, 895.23348, 910.729, 918.66812, 93...","[[4160.09572, 4171.92024, 4184.43492, 4194.388..."
155,caf69,1230_12_24,360.850081,F,wt,CA1,RSU,0.64,155,"[[0.10976000000000002, 0.16003999999999996, 0....","[[0.4389600000000655, 0.3974799999999732, 1.02...","[[0.1762799999996787, 0.5155200000008335, 0.85...","[240, 160, 60, 128, 84, 4, 320, 868, 12, 600, ...","[1120, 1840, 180, 680, 180, 280, 260, 880, 520...","[60, 80, 40, 100, 140, 80, 120, 160, 120, 180,...","[[0.40856, 34.9484, 67.43688, 109.11444, 139.4...","[[880.59164, 913.87124, 942.3478, 976.0522, 10...","[[4160.11028, 4190.13772, 4213.1066, 4219.1392..."

Working on caf71
Has 2 files to go through
got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,caf71,0103_0_12,492.315579,M,app_ps1,V1,FS,0.16,0,"[[0.4530799999999999, 0.2665199999999004, 0.16...","[[0.10172000000000003, 0.010360000000000036, 0...","[[1.2389600000001337, 0.021600000000034925, 0....","[276, 168, 4, 188, 68, 28, 36, 4, 404, 64, 108...","[236, 28, 40, 252, 20, 284, 60, 172, 516, 572,...","[12, 72, 36, 40, 48, 76, 48]","[[1068.85344, 1115.32768, 1160.09708, 1201.879...","[[0.7562, 81.04344, 146.90468, 235.90028], [25...","[[3704.54484, 3715.8126], [6296.76888, 6318.79..."
1,caf71,0103_0_12,492.315579,M,app_ps1,V1,RSU,0.44,1,"[[0.0929599999999482, 0.024400000000014188, 0....","[[0.0043999999999999595, 0.014960000000000084,...","[[0.1728400000001784, 0.34287999999969543, 0.0...","[276, 168, 4, 188, 68, 28, 36, 4, 404, 64, 108...","[236, 28, 40, 252, 20, 284, 60, 172, 516, 572,...","[12, 72, 36, 40, 48, 76, 48]","[[1068.21376, 1081.03452, 1093.0162, 1112.9727...","[[0.78884, 22.37336, 61.50556, 81.46084, 105.0...","[[3704.01116, 3712.66504, 3715.92896], [6296.7..."
2,caf71,0103_0_12,492.315579,M,app_ps1,V1,FS,0.16,2,"[[0.03848000000016327, 0.04899999999997817, 0....","[[0.07455999999999996, 0.20316000000000012, 0....","[[0.13339999999971042, 0.23019999999996799, 0....","[276, 168, 4, 188, 68, 28, 36, 4, 404, 64, 108...","[236, 28, 40, 252, 20, 284, 60, 172, 516, 572,...","[12, 72, 36, 40, 48, 76, 48]","[[1068.1968, 1080.71884, 1098.09328, 1115.2402...","[[0.88156, 23.72888, 53.2826, 79.03732, 103.14...","[[3704.06532, 3714.93276, 3715.898], [6296.224..."
3,caf71,0103_0_12,492.315579,M,app_ps1,V1,FS,0.16,3,"[[0.8999599999999646, 0.8607600000000275, 0.96...","[[0.11132, 0.53604, 4.21732, 1.739600000000000...","[[0.6290399999998044, 0.24620000000004438, 0.1...","[276, 168, 4, 188, 68, 28, 36, 4, 404, 64, 108...","[236, 28, 40, 252, 20, 284, 60, 172, 516, 572,...","[12, 72, 36, 40, 48, 76, 48]","[[1069.78612, 1118.38836, 1181.43656, 1229.493...","[[0.0136, 51.80644, 110.68928, 147.39612, 192....","[[3704.97044, 3715.96648], [6296.55508, 6330.8..."
4,caf71,0103_0_12,492.315579,M,app_ps1,V1,FS,0.28,4,"[[0.18152000000009139, 1.4912799999999606, 0.1...","[[0.00428, 3.3762000000000003, 1.4484799999999...","[[0.12203999999974258, 0.3952800000001844, 0.5...","[276, 168, 4, 188, 68, 28, 36, 4, 404, 64, 108...","[236, 28, 40, 252, 20, 284, 60, 172, 516, 572,...","[12, 72, 36, 40, 48, 76, 48]","[[1068.56704, 1123.5734, 1193.43036, 1234.3438...","[[4e-05, 59.89308, 121.669, 167.38024, 235.721...","[[3705.32832, 3715.59004], [6296.24628, 6335.2..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,caf71,0103_0_12,492.315579,M,app_ps1,ACC,RSU,0.48,124,"[[177.9946], [23.491600000000062, 8.8694399999...","[[15.84196, 164.99964, 15.051320000000004], []...","[[], [], [], [7.841439999998329, 2.31372000000...","[276, 168, 4, 188, 68, 28, 36, 4, 404, 64, 108...","[236, 28, 40, 252, 20, 284, 60, 172, 516, 572,...","[12, 72, 36, 40, 48, 76, 48]","[[1145.19136, 1323.18596], [1385.52956, 1479.0...","[[8e-05, 195.893], [], [], [500.25244], [676.6...","[[3710.15608], [], [], [12140.55152, 12173.426..."
125,caf71,0103_0_12,492.315579,M,app_ps1,ACC,RSU,0.56,125,"[[0.027919999999994616, 0.08595999999988635, 0...","[[0.11864, 0.04744000000000001, 0.0378, 0.0555...","[[0.0464799999999741, 0.023760000000038417, 0....","[276, 168, 4, 188, 68, 28, 36, 4, 404, 64, 108...","[236, 28, 40, 252, 20, 284, 60, 172, 516, 572,...","[12, 72, 36, 40, 48, 76, 48]","[[1068.05492, 1073.92284, 1077.74524, 1079.979...","[[0.07804, 7.83032, 12.53948, 18.59888, 23.835...","[[3704.07056, 3708.36348, 3711.87864, 3715.677..."
126,caf71,0103_0_12,492.315579,M,app_ps1,ACC,RSU,0.48,126,"[[0.055280000000038854, 0.03719999999998436, 0...","[[0.018840000000000003, 0.34299999999999997, 0...","[[0.15267999999969106, 0.12348000000019965, 2....","[276, 168, 4, 188, 68, 28, 36, 4, 404, 64, 108...","[236, 28, 40, 252, 20, 284, 60, 172, 516, 572,...","[12, 72, 36, 40, 48, 76, 48]","[[1068.24404, 1088.5884, 1106.76852, 1128.3399...","[[4e-05, 42.25136, 91.6916, 144.49844, 213.219...","[[3705.36052, 3715.52772], [6296.0804, 6315.82..."
127,caf71,0103_0_12,492.315579,M,app_ps1,ACC,FS,0.32,127,"[[0.3530399999999645, 0.5828000000001339, 0.24...","[[0.35924, 0.6275200000000001, 0.7706, 1.14384...","[[0.026640000000043074, 1.2167599999997947, 0....","[276, 168, 4, 188, 68, 28, 36, 4, 404, 64, 108...","[236, 28, 40, 252, 20, 284, 60, 172, 516, 572,...","[12, 72, 36, 40, 48, 76, 48]","[[1068.27496, 1103.75076, 1139.05536, 1175.880...","[[0.01888, 85.30548, 221.91404, 235.82692], [2...","[[3704.24924, 3715.72452], [6296.13476, 6317.1..."
128,caf71,0103_0_12,492.315579,M,app_ps1,ACC,RSU,1.08,128,"[[0.7022799999999734, 0.411160000000109, 0.059...","[[0.8091599999999999, 0.7772000000000001, 0.63...","[[0.017079999999623396, 0.0678000000002612, 0....","[276, 168, 4, 188, 68, 28, 36, 4, 404, 64, 108...","[236, 28, 40, 252, 20, 284, 60, 172, 516, 572,...","[12, 72, 36, 40, 48, 76, 48]","[[1068.137, 1087.68372, 1110.13328, 1132.39824...","[[0.36328, 39.7974, 84.60196, 130.0754, 188.11...","[[3704.09448, 3715.876], [6296.0504, 6314.3559..."

got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,caf71,0103_12_20,492.81559,M,app_ps1,V1,FS,0.16,0,"[[0.11196, 0.013759999999999994, 0.11015999999...","[[0.44920000000000027, 0.20272000000000023, 0....","[[0.14176000000020395, 0.025599999999940337, 0...","[4, 20, 172, 32, 276, 320, 44, 204, 40, 144, 4...","[196, 248, 176, 676, 380, 1012, 240, 124, 72, ...","[36, 60, 76, 92]","[[0.13816, 3.43444], [244.0052, 263.98396], [2...","[[4.23356, 21.9416, 31.2486, 55.01244, 76.0457...","[[1888.53156, 1896.45692, 1905.576, 1912.47092..."
1,caf71,0103_12_20,492.81559,M,app_ps1,V1,FS,0.20,1,"[[0.05180000000000001, 0.009560000000000013, 0...","[[0.04455999999999971, 0.08443999999999985, 0....","[[0.14136000000007698, 0.11716000000001259, 0....","[4, 20, 172, 32, 276, 320, 44, 204, 40, 144, 4...","[196, 248, 176, 676, 380, 1012, 240, 124, 72, ...","[36, 60, 76, 92]","[[0.236, 3.5676], [244.10904, 263.93492], [296...","[[4.15704, 21.31628, 33.70428, 64.51656, 84.93...","[[1888.02144, 1896.01688, 1901.87152, 1907.033..."
2,caf71,0103_12_20,492.81559,M,app_ps1,V1,RSU,0.44,2,"[[0.01548000000000005, 0.04235999999999995, 2....","[[0.013799999999999812, 0.14480000000000004, 0...","[[0.16052000000013322, 0.2521600000000035, 0.0...","[4, 20, 172, 32, 276, 320, 44, 204, 40, 144, 4...","[196, 248, 176, 676, 380, 1012, 240, 124, 72, ...","[36, 60, 76, 92]","[[0.25408, 2.53788], [254.5532, 262.58408], [2...","[[5.51652, 193.009], [468.8392, 714.50056], [7...","[[1890.376, 1900.06604], [15243.03516, 15276.0..."
3,caf71,0103_12_20,492.81559,M,app_ps1,V1,RSU,0.52,3,"[[0.019320000000000004, 0.0844, 0.061240000000...","[[0.09835999999999956, 0.22824000000000044, 0....","[[0.17511999999987893, 0.008240000000114378, 0...","[4, 20, 172, 32, 276, 320, 44, 204, 40, 144, 4...","[196, 248, 176, 676, 380, 1012, 240, 124, 72, ...","[36, 60, 76, 92]","[[0.22704, 3.89872], [244.00996, 261.02664, 26...","[[4.65488, 18.62692, 30.2558, 43.88052, 63.566...","[[1888.5922, 1898.40756, 1907.23996, 1916.3815..."
4,caf71,0103_12_20,492.81559,M,app_ps1,V1,RSU,0.40,4,"[[0.17608000000000001, 0.061560000000000004, 0...","[[0.046800000000000175, 0.02859999999999996, 0...","[[0.056319999999914216, 0.4702800000000025, 0....","[4, 20, 172, 32, 276, 320, 44, 204, 40, 144, 4...","[196, 248, 176, 676, 380, 1012, 240, 124, 72, ...","[36, 60, 76, 92]","[[0.03408, 3.9602], [244.01068, 251.8808, 263....","[[4.0534, 8.61712, 13.48444, 17.3682, 21.04464...","[[1888.17884, 1894.4418, 1898.59924, 1901.3307..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,caf71,0103_12_20,492.81559,M,app_ps1,ACC,RSU,0.64,116,"[[0.4597200000000001, 0.43852, 1.51552, 1.0602...","[[0.6039200000000005, 0.047399999999999665, 2....","[[0.012799999999970169, 0.2278400000000147, 1....","[4, 20, 172, 32, 276, 320, 44, 204, 40, 144, 4...","[196, 248, 176, 676, 380, 1012, 240, 124, 72, ...","[36, 60, 76, 92]","[[0.48016, 3.9542], [244.46592, 263.763], [296...","[[4.536, 69.46428, 125.57564, 179.18552, 198.6...","[[1888.16004, 1917.88436, 1923.93784], [15240...."
117,caf71,0103_12_20,492.81559,M,app_ps1,ACC,RSU,0.68,117,"[[0.26336000000000004, 0.09127999999999997, 0....","[[0.016639999999999766, 0.49332000000000065, 0...","[[0.029680000000098516, 0.11832000000003973, 0...","[4, 20, 172, 32, 276, 320, 44, 204, 40, 144, 4...","[196, 248, 176, 676, 380, 1012, 240, 124, 72, ...","[36, 60, 76, 92]","[[0.13168, 3.98328], [244.02136, 254.60748, 26...","[[4.13908, 13.84576, 23.23572, 31.9468, 42.824...","[[1888.1442, 1898.4246, 1905.63464, 1913.56204..."
118,caf71,0103_12_20,492.81559,M,app_ps1,ACC,RSU,0.72,118,"[[0.010520000000000002, 0.050559999999999994, ...","[[0.2535999999999996, 0.5259999999999998, 0.12...","[[0.013959999999997308, 0.3347200000000612, 0....","[4, 20, 172, 32, 276, 320, 44, 204, 40, 144, 4...","[196, 248, 176, 676, 380, 1012, 240, 124, 72, ...","[36, 60, 76, 92]","[[0.0634, 3.98332], [244.02144, 254.6432, 263....","[[4.0178, 16.31572, 28.261, 39.5532, 53.34216,...","[[1888.01656, 1900.13576, 1909.75836, 1918.006..."
119,caf71,0103_12_20,492.81559,M,app_ps1,ACC,RSU,0.72,119,"[[0.06832, 0.16987999999999998, 0.15848, 0.439...","[[0.02432000000000034, 0.04600000000000026, 0....","[[0.13831999999979416, 0.13332000000013977, 0....","[4, 20, 172, 32, 276, 320, 44, 204, 40, 144, 4...","[196, 248, 176, 676, 380, 1012, 240, 124, 72, ...","[36, 60, 76, 92]","[[0.0634, 3.94376], [244.01308, 254.50808, 263...","[[4.01784, 16.94748, 28.85132, 40.7936, 56.559...","[[1888.03328, 1900.63544, 1910.66724, 1919.241..."
120,caf71,0103_12_20,492.81559,M,app_ps1,ACC,RSU,1.00,120,"[[0.0878000000000001, 0.35516000000000014, 0.4...","[[0.048040000000000305, 0.20611999999999941, 0...","[[1.834440000000086, 0.642319999999927, 1.1775...","[4, 20, 172, 32, 276, 320, 44, 204, 40, 144, 4...","[196, 248, 176, 676, 380, 1012, 240, 124, 72, ...","[36, 60, 76, 92]","[[2.03816, 3.9408], [244.02616, 262.956], [297...","[[4.24552, 50.90784, 105.6314, 172.73784, 199....","[[1888.157, 1923.50116], [15240.2012, 15264.68..."

Working on caf73
Has 2 files to go through
got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,caf73,0120_4_15,381.340833,F,app_ps1,ACC,FS,0.12,0,"[[0.36176000000159547, 0.008199999998396379, 0...","[[0.4761599999999999, 0.07040000000000002, 0.1...","[[6.707640000000026, 0.47119999999998186, 1.23...","[48, 24, 144, 44, 16, 4, 108, 20, 44, 76, 16, ...","[184, 2408, 616, 240, 1840, 1436, 1596, 884, 7...","[88, 28, 32, 48, 116, 108, 116, 64, 52, 68, 12...","[[14272.53596, 14300.17164, 14319.54984], [146...","[[0.95804, 41.12844, 137.58372, 183.94244], [2...","[[200.92152, 271.97708], [2680.30212, 2705.394..."
1,caf73,0120_4_15,381.340833,F,app_ps1,ACC,RSU,0.64,1,"[[0.3205600000001141, 0.004639999999199063, 0....","[[1.3215999999999999, 0.0458400000000001, 0.38...","[[0.003919999999993706, 0.0031199999999955708,...","[48, 24, 144, 44, 16, 4, 108, 20, 44, 76, 16, ...","[184, 2408, 616, 240, 1840, 1436, 1596, 884, 7...","[88, 28, 32, 48, 116, 108, 116, 64, 52, 68, 12...","[[14272.13436, 14287.89688, 14305.2274, 14319....","[[0.05872, 28.47888, 39.99624, 54.75452, 78.89...","[[184.00332, 202.53812, 218.45264, 233.25152, ..."
2,caf73,0120_4_15,381.340833,F,app_ps1,ACC,FS,0.16,2,"[[0.0036000000000058208, 0.002759999999398133,...","[[0.5197999999999999, 0.50628, 0.7922800000000...","[[0.7813600000000065, 1.1213599999999815, 0.92...","[48, 24, 144, 44, 16, 4, 108, 20, 44, 76, 16, ...","[184, 2408, 616, 240, 1840, 1436, 1596, 884, 7...","[88, 28, 32, 48, 116, 108, 116, 64, 52, 68, 12...","[[14272.49804, 14278.9274, 14284.15272, 14287....","[[4e-05, 37.62604, 77.068, 128.05336, 178.7518...","[[184.4488, 227.32988, 260.05456, 271.98], [26..."
3,caf73,0120_4_15,381.340833,F,app_ps1,ACC,RSU,0.84,3,"[[0.41519999999945867, 0.2381600000007893, 0.1...","[[0.03763999999999999, 0.10075999999999999, 0....","[[0.032479999999992515, 0.35444000000001097, 0...","[48, 24, 144, 44, 16, 4, 108, 20, 44, 76, 16, ...","[184, 2408, 616, 240, 1840, 1436, 1596, 884, 7...","[88, 28, 32, 48, 116, 108, 116, 64, 52, 68, 12...","[[14272.30848, 14279.2188, 14290.69884, 14307....","[[0.08772, 18.45384, 33.91624, 44.98556, 63.03...","[[184.109, 214.29816, 247.83584, 266.84708, 27..."
4,caf73,0120_4_15,381.340833,F,app_ps1,ACC,RSU,0.88,4,"[[0.16295999999965716, 0.10947999999916647, 0....","[[0.032440000000000004, 0.09292, 0.07663999999...","[[0.02027999999998542, 0.005160000000017817, 0...","[48, 24, 144, 44, 16, 4, 108, 20, 44, 76, 16, ...","[184, 2408, 616, 240, 1840, 1436, 1596, 884, 7...","[88, 28, 32, 48, 116, 108, 116, 64, 52, 68, 12...","[[14272.32112, 14278.94628, 14288.74524, 14297...","[[4e-05, 12.90344, 26.89948, 35.3516, 44.72392...","[[184.03332, 207.15568, 228.40364, 247.89004, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172,caf73,0120_4_15,381.340833,F,app_ps1,V1,RSU,0.80,172,"[[0.2864799999988463, 0.02576000000044587, 0.0...","[[0.39547999999999994, 0.15424000000000015, 0....","[[0.016000000000019554, 0.016840000000001965, ...","[48, 24, 144, 44, 16, 4, 108, 20, 44, 76, 16, ...","[184, 2408, 616, 240, 1840, 1436, 1596, 884, 7...","[88, 28, 32, 48, 116, 108, 116, 64, 52, 68, 12...","[[14272.0434, 14283.19588, 14294.49264, 14311....","[[0.89352, 22.36196, 39.07872, 60.3196, 76.361...","[[184.1496, 194.71456, 205.95348, 215.90736, 2..."
173,caf73,0120_4_15,381.340833,F,app_ps1,V1,FS,0.28,173,"[[0.004360000000815489, 0.10839999999916472, 0...","[[0.91128, 0.39403999999999995, 0.156600000000...","[[0.33899999999999864, 0.0781199999999842, 0.1...","[48, 24, 144, 44, 16, 4, 108, 20, 44, 76, 16, ...","[184, 2408, 616, 240, 1840, 1436, 1596, 884, 7...","[88, 28, 32, 48, 116, 108, 116, 64, 52, 68, 12...","[[14272.113, 14282.85176, 14290.24656, 14302.1...","[[0.12532, 11.73788, 23.52976, 35.61744, 46.66...","[[184.04176, 195.76468, 205.26344, 211.78396, ..."
174,caf73,0120_4_15,381.340833,F,app_ps1,V1,RSU,0.72,174,"[[0.03944000000046799, 0.16195999999945343, 0....","[[0.03312000000000004, 0.25948000000000004, 0....","[[0.13388000000000488, 0.17203999999998132, 0....","[48, 24, 144, 44, 16, 4, 108, 20, 44, 76, 16, ...","[184, 2408, 616, 240, 1840, 1436, 1596, 884, 7...","[88, 28, 32, 48, 116, 108, 116, 64, 52, 68, 12...","[[14272.04336, 14281.2226, 14286.70008, 14298....","[[0.75144, 18.44184, 38.24892, 55.67132, 72.56...","[[184.09824, 194.25508, 202.89048, 213.85892, ..."
175,caf73,0120_4_15,381.340833,F,app_ps1,V1,FS,0.16,175,"[[0.13792000000103144, 0.8143199999994977, 3.8...","[[0.21292, 1.01016, 0.016360000000000152, 1.44...","[[1.7444399999999973, 0.5122399999999914, 0.92...","[48, 24, 144, 44, 16, 4, 108, 20, 44, 76, 16, ...","[184, 2408, 616, 240, 1840, 1436, 1596, 884, 7...","[88, 28, 32, 48, 116, 108, 116, 64, 52, 68, 12...","[[14272.1184, 14319.72124], [14660.70868, 1468...","[[2.52948, 142.92224, 183.79708], [273.14268, ...","[[184.17044, 230.57576, 270.83456], [2680.6391..."
176,caf73,0120_4_15,381.340833,F,app_ps1,V1,FS,0.16,176,"[[0.5752799999991112, 1.4686800000017683, 0.97...","[[0.55476, 3.3423599999999993, 0.9396400000000...","[[1.6511200000000201, 0.8437999999999874, 0.24...","[48, 24, 144, 44, 16, 4, 108, 20, 44, 76, 16, ...","[184, 2408, 616, 240, 1840, 1436, 1596, 884, 7...","[88, 28, 32, 48, 116, 108, 116, 64, 52, 68, 12...","[[14273.01764, 14317.03848, 14319.8958], [1466...","[[0.2148, 54.88688, 86.07588, 124.45364, 155.8...","[[184.12424, 214.3012, 226.08836, 237.6458, 24..."

got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,caf73,0120_15_24,381.840833,F,app_ps1,ACC,RSU,0.72,0,"[[0.02388000000064494, 0.047200000000884756, 0...","[[0.14179999999999993, 0.08460000000000001, 0....","[[0.037160000000000026, 0.06619999999999993, 0...","[12, 16, 4, 56, 24, 20, 80, 88, 388, 64, 4, 8,...","[1640, 1180, 1072, 1912, 4, 1148, 1004, 4132, ...","[4, 116, 36, 124, 48, 8, 48, 72, 28, 144, 16, ...","[[14132.0086, 14136.18444, 14140.9542, 14143.9...","[[4.23676, 14.35404, 21.49772, 30.27972, 47.24...","[[0.42812, 3.66632], [1644.04056, 1652.42228, ..."
1,caf73,0120_15_24,381.840833,F,app_ps1,ACC,RSU,0.72,1,"[[0.12271999999938998, 0.1281200000012177, 0.0...","[[0.3424800000000001, 0.3540000000000001, 0.22...","[[0.9541999999999999, 0.13247999999999993, 0.1...","[12, 16, 4, 56, 24, 20, 80, 88, 388, 64, 4, 8,...","[1640, 1180, 1072, 1912, 4, 1148, 1004, 4132, ...","[4, 116, 36, 124, 48, 8, 48, 72, 28, 144, 16, ...","[[14132.11412, 14143.78388], [14200.04448, 142...","[[4.2378, 33.39644, 67.88796, 103.7728, 137.85...","[[0.06108, 3.84648], [1644.07836, 1669.59472, ..."
2,caf73,0120_15_24,381.840833,F,app_ps1,ACC,FS,0.24,2,"[[0.15931999999884283, 0.7316399999999703, 8.2...","[[0.17051999999999978, 0.33108000000000004, 3....","[[0.3538, 0.13356, 0.22375999999999996, 0.3360...","[12, 16, 4, 56, 24, 20, 80, 88, 388, 64, 4, 8,...","[1640, 1180, 1072, 1912, 4, 1148, 1004, 4132, ...","[4, 116, 36, 124, 48, 8, 48, 72, 28, 144, 16, ...","[[14132.1872, 14141.48088], [14201.1888, 14215...","[[4.06384, 70.54036, 145.16344, 224.168, 302.1...","[[0.12412, 3.63216], [1660.31184, 1758.82088, ..."
3,caf73,0120_15_24,381.840833,F,app_ps1,ACC,FS,0.16,3,"[[0.15767999999843596, 0.12092000000120606, 0....","[[0.8564799999999995, 3.550600000000001, 0.003...","[[1.2142, 0.9532799999999999, 0.17120000000000...","[12, 16, 4, 56, 24, 20, 80, 88, 388, 64, 4, 8,...","[1640, 1180, 1072, 1912, 4, 1148, 1004, 4132, ...","[4, 116, 36, 124, 48, 8, 48, 72, 28, 144, 16, ...","[[14132.1928, 14143.6796], [14200.8588, 14215....","[[7.15152, 67.7268, 141.56992, 226.65168, 303....","[[1.23056, 3.5716], [1644.41568, 1750.07904, 1..."
4,caf73,0120_15_24,381.840833,F,app_ps1,ACC,FS,0.16,4,"[[0.17560000000048603, 0.6539599999996426, 0.1...","[[0.9279600000000006, 1.9859199999999992, 4.42...","[[0.8920800000000001, 0.05775999999999981, 0.0...","[12, 16, 4, 56, 24, 20, 80, 88, 388, 64, 4, 8,...","[1640, 1180, 1072, 1912, 4, 1148, 1004, 4132, ...","[4, 116, 36, 124, 48, 8, 48, 72, 28, 144, 16, ...","[[14132.01724, 14143.96068], [14200.37044, 142...","[[4.23424, 48.2576, 114.16092, 178.90084, 226....","[[0.124, 3.57164], [1644.82344, 1718.94732, 17..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,caf73,0120_15_24,381.840833,F,app_ps1,V1,FS,0.32,208,"[[0.0991199999989476, 0.053520000001299195, 0....","[[0.17644000000000037, 0.7065999999999999, 0.6...","[[0.06287999999999999, 2.01444, 0.419560000000...","[12, 16, 4, 56, 24, 20, 80, 88, 388, 64, 4, 8,...","[1640, 1180, 1072, 1912, 4, 1148, 1004, 4132, ...","[4, 116, 36, 124, 48, 8, 48, 72, 28, 144, 16, ...","[[14132.25012, 14143.8942], [14200.10024, 1421...","[[4.00828, 34.01052, 57.4282, 69.98536, 88.143...","[[0.16996, 3.94736], [1644.11748, 1665.09, 168..."
209,caf73,0120_15_24,381.840833,F,app_ps1,V1,RSU,0.88,209,"[[0.0689200000015262, 0.011079999998401036, 0....","[[0.10536000000000012, 0.72072, 0.069200000000...","[[0.06564, 0.005159999999999998, 0.29635999999...","[12, 16, 4, 56, 24, 20, 80, 88, 388, 64, 4, 8,...","[1640, 1180, 1072, 1912, 4, 1148, 1004, 4132, ...","[4, 116, 36, 124, 48, 8, 48, 72, 28, 144, 16, ...","[[14132.0068, 14136.79956, 14141.83928, 14143....","[[4.08752, 13.88744, 20.99104, 32.21096, 41.44...","[[0.05384, 3.94224], [1644.05744, 1650.13736, ..."
210,caf73,0120_15_24,381.840833,F,app_ps1,V1,RSU,0.68,210,"[[0.37348000000019965, 0.0797999999995227, 0.3...","[[0.3220799999999997, 0.40176000000000034, 1.6...","[[0.27659999999999996, 0.48288, 0.248839999999...","[12, 16, 4, 56, 24, 20, 80, 88, 388, 64, 4, 8,...","[1640, 1180, 1072, 1912, 4, 1148, 1004, 4132, ...","[4, 116, 36, 124, 48, 8, 48, 72, 28, 144, 16, ...","[[14132.20484, 14143.94792], [14200.19984, 142...","[[4.03568, 54.38096, 106.61012, 149.59896, 199...","[[1.17516, 3.59684], [1644.05024, 1663.31428, ..."
211,caf73,0120_15_24,381.840833,F,app_ps1,V1,RSU,0.76,211,"[[0.07999999999992724, 0.27307999999902677, 0....","[[0.040280000000000094, 0.48808000000000007, 1...","[[0.050759999999999916, 0.09784000000000004, 0...","[12, 16, 4, 56, 24, 20, 80, 88, 388, 64, 4, 8,...","[1640, 1180, 1072, 1912, 4, 1148, 1004, 4132, ...","[4, 116, 36, 124, 48, 8, 48, 72, 28, 144, 16, ...","[[14132.0918, 14143.35672], [14200.1184, 14215...","[[4.92584, 55.7362, 105.54144, 144.82752, 193....","[[0.93776, 3.59684], [1644.02744, 1669.61844, ..."
212,caf73,0120_15_24,381.840833,F,app_ps1,V1,RSU,0.76,212,"[[0.072360000000117, 0.4545200000011391, 0.310...","[[0.20064000000000082, 0.2759199999999993, 0.8...","[[0.67832, 0.2644000000000001, 0.8693199999999...","[12, 16, 4, 56, 24, 20, 80, 88, 388, 64, 4, 8,...","[1640, 1180, 1072, 1912, 4, 1148, 1004, 4132, ...","[4, 116, 36, 124, 48, 8, 48, 72, 28, 144, 16, ...","[[14132.08068, 14142.82828], [14200.12156, 142...","[[4.32152, 65.49548, 127.38244, 185.03696, 247...","[[0.1786, 3.65272], [1644.39324, 1697.62028, 1..."

Working on caf74
Has 2 files to go through
got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,caf74,0125_48_60,419.379942,M,app_ps1,ACC,RSU,0.68,0,"[[0.045719999999619176, 0.01768000000038228, 0...","[[0.58592, 0.11987999999999999, 0.088400000000...","[[0.10620000000017171, 0.09796000000005733, 0....","[588, 28, 76, 108, 240, 36, 556, 192, 292, 20,...","[2392, 12, 204, 200, 36, 84, 144, 328, 92, 524...","[56, 36, 40, 32, 32, 20]","[[2392.08152, 2402.13356, 2412.92884, 2422.132...","[[0.31328, 20.0856, 37.20056, 51.27924, 67.238...","[[5448.19392, 5457.265, 5466.37512, 5473.74148..."
1,caf74,0125_48_60,419.379942,M,app_ps1,ACC,RSU,0.80,1,"[[0.40851999999995314, 0.05896000000029744, 0....","[[0.51508, 0.32508000000000004, 0.883479999999...","[[0.08156000000053609, 0.1525599999995393, 1.9...","[588, 28, 76, 108, 240, 36, 556, 192, 292, 20,...","[2392, 12, 204, 200, 36, 84, 144, 328, 92, 524...","[56, 36, 40, 32, 32, 20]","[[2392.24844, 2434.8414, 2468.62628, 2489.1880...","[[0.59792, 42.01792, 76.67276, 110.66524, 149....","[[5448.0058, 5470.73316, 5484.50748, 5502.5177..."
2,caf74,0125_48_60,419.379942,M,app_ps1,ACC,RSU,0.84,2,"[[42.86288000000013, 25.21355999999969, 18.163...","[[90.47932, 3.122159999999994, 57.181119999999...","[[9.663319999999658, 6.651719999999841, 6.7270...","[588, 28, 76, 108, 240, 36, 556, 192, 292, 20,...","[2392, 12, 204, 200, 36, 84, 144, 328, 92, 524...","[56, 36, 40, 32, 32, 20]","[[2451.10156, 2972.03484], [3024.65152, 3040.8...","[[4e-05, 2380.27788], [], [3660.19912, 3814.85...","[[5467.85364, 5498.81468], [], [19584.02476, 1..."
3,caf74,0125_48_60,419.379942,M,app_ps1,ACC,RSU,0.68,3,"[[1.2006799999999203, 0.7448399999998401, 1.06...","[[28.19152, 11.690959999999997, 17.4818, 12.32...","[[13.408320000000458, 0.9310399999994843, 0.12...","[588, 28, 76, 108, 240, 36, 556, 192, 292, 20,...","[2392, 12, 204, 200, 36, 84, 144, 328, 92, 524...","[56, 36, 40, 32, 32, 20]","[[2392.45184, 2586.07896, 2832.721, 2977.24024...","[[3.514, 340.26848, 717.82664, 974.5686, 1339....","[[5448.17628, 5499.28524], [5832.00732, 5867.2..."
4,caf74,0125_48_60,419.379942,M,app_ps1,ACC,RSU,0.76,4,"[[0.03448000000025786, 0.018119999999726133, 0...","[[0.2808, 0.08163999999999999, 0.0415600000000...","[[0.4451200000003155, 0.0342000000000553, 0.53...","[588, 28, 76, 108, 240, 36, 556, 192, 292, 20,...","[2392, 12, 204, 200, 36, 84, 144, 328, 92, 524...","[56, 36, 40, 32, 32, 20]","[[2392.0622, 2404.14372, 2423.58864, 2447.3115...","[[0.12468, 24.37872, 46.7874, 62.16848, 80.980...","[[5448.07256, 5463.83272, 5473.96172, 5483.953..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,caf74,0125_48_60,419.379942,M,app_ps1,V1,RSU,0.56,120,"[[3.7739999999998872, 0.27712000000019543, 2.3...","[[0.10067999999999999, 0.34551999999999994, 0....","[[0.24639999999999418, 0.023159999999734282, 0...","[588, 28, 76, 108, 240, 36, 556, 192, 292, 20,...","[2392, 12, 204, 200, 36, 84, 144, 328, 92, 524...","[56, 36, 40, 32, 32, 20]","[[2393.4586, 2437.0704, 2484.17608, 2504.8012,...","[[0.47904, 18.57256, 35.091, 57.70164, 82.7736...","[[5448.07552, 5469.1926, 5484.9318, 5503.57484..."
121,caf74,0125_48_60,419.379942,M,app_ps1,V1,FS,0.16,121,"[[0.25896000000011554, 0.2780000000002474, 0.2...","[[0.07388, 0.017000000000000015, 0.1758, 0.369...","[[4.230559999999969, 0.02775999999994383, 0.00...","[588, 28, 76, 108, 240, 36, 556, 192, 292, 20,...","[2392, 12, 204, 200, 36, 84, 144, 328, 92, 524...","[56, 36, 40, 32, 32, 20]","[[2392.20612, 2464.82264, 2508.21024, 2545.027...","[[0.14936, 26.86692, 40.90008, 63.97384, 110.7...","[[5449.29396, 5502.44664], [5832.00972, 5867.7..."
122,caf74,0125_48_60,419.379942,M,app_ps1,V1,RSU,0.64,122,"[[0.10188000000016473, 0.11515999999983251, 0....","[[0.09316000000000002, 1.5635599999999998, 0.7...","[[0.1618399999997564, 0.5148400000007314, 0.36...","[588, 28, 76, 108, 240, 36, 556, 192, 292, 20,...","[2392, 12, 204, 200, 36, 84, 144, 328, 92, 524...","[56, 36, 40, 32, 32, 20]","[[2392.285, 2431.72208, 2466.973, 2490.11868, ...","[[0.86232, 44.64776, 90.05148, 138.20896, 164....","[[5448.13872, 5469.77596, 5501.25988, 5502.412..."
123,caf74,0125_48_60,419.379942,M,app_ps1,V1,FS,0.16,123,"[[0.11659999999983484, 0.19671999999991385, 0....","[[1.12392, 0.26436000000000015, 0.862479999999...","[[0.10563999999976659, 0.03128000000015163, 0....","[588, 28, 76, 108, 240, 36, 556, 192, 292, 20,...","[2392, 12, 204, 200, 36, 84, 144, 328, 92, 524...","[56, 36, 40, 32, 32, 20]","[[2392.10008, 2472.66172, 2491.888, 2512.50952...","[[0.06696, 47.78736, 91.69352, 135.31728, 155....","[[5448.24168, 5460.44792, 5467.60528, 5473.936..."
124,caf74,0125_48_60,419.379942,M,app_ps1,V1,FS,0.16,124,"[[0.3133199999997487, 0.002800000000206637, 0....","[[0.11696000000000006, 0.15503999999999996, 0....","[[0.09355999999934284, 0.015560000000732543, 0...","[588, 28, 76, 108, 240, 36, 556, 192, 292, 20,...","[2392, 12, 204, 200, 36, 84, 144, 328, 92, 524...","[56, 36, 40, 32, 32, 20]","[[2392.10012, 2439.4366, 2458.5268, 2472.73972...","[[0.52852, 14.88396, 27.71668, 45.5976, 63.134...","[[5448.03016, 5456.07304, 5463.03044, 5466.537..."

got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,caf74,0125_60_72,419.879942,M,app_ps1,ACC,RSU,0.72,0,"[[0.10652000000004591, 0.019679999999993925, 0...","[[0.1172, 0.03544000000000003, 0.0056799999999...","[[0.1279599999999732, 0.08503999999999223, 0.0...","[104, 16, 68, 284, 24, 184, 136, 16, 252, 92, ...","[472, 156, 248, 52, 116, 516, 148, 784, 248, 1...","[184, 100, 76, 92]","[[836.05228, 843.13192, 849.18608, 855.70388, ...","[[0.152, 7.1336, 13.47732, 20.08276, 26.47872,...","[[472.07816, 478.35552, 483.59756, 490.15752, ..."
1,caf74,0125_60_72,419.879942,M,app_ps1,ACC,RSU,0.76,1,"[[0.3953999999999951, 0.3346000000000231, 0.06...","[[2.6898, 0.7023600000000001, 0.31672000000000...","[[0.06831999999997151, 0.951279999999997, 0.75...","[104, 16, 68, 284, 24, 184, 136, 16, 252, 92, ...","[472, 156, 248, 52, 116, 516, 148, 784, 248, 1...","[184, 100, 76, 92]","[[836.13144, 888.37976, 931.22908, 939.9562], ...","[[0.791, 60.4044, 117.56028, 163.30524, 219.95...","[[472.04984, 525.42708, 570.35928, 610.09916, ..."
2,caf74,0125_60_72,419.879942,M,app_ps1,ACC,RSU,0.68,2,"[[0.03452000000004318, 0.017200000000002547, 0...","[[0.58032, 3.2545600000000006, 9.25648, 0.3799...","[[0.5414799999999786, 5.347720000000038, 0.467...","[104, 16, 68, 284, 24, 184, 136, 16, 252, 92, ...","[472, 156, 248, 52, 116, 516, 148, 784, 248, 1...","[184, 100, 76, 92]","[[837.65708, 935.89248], [1002.92572, 1014.884...","[[3.77256, 231.05636, 443.69164, 471.44996], [...","[[472.21008, 599.73604, 649.9248], [10336.6166..."
3,caf74,0125_60_72,419.879942,M,app_ps1,ACC,RSU,0.72,3,"[[0.011439999999993233, 0.16091999999991913, 0...","[[0.018119999999999997, 0.08784, 0.03203999999...","[[0.05984000000000833, 0.1463600000000156, 0.1...","[104, 16, 68, 284, 24, 184, 136, 16, 252, 92, ...","[472, 156, 248, 52, 116, 516, 148, 784, 248, 1...","[184, 100, 76, 92]","[[836.16308, 848.4612, 866.70864, 882.07968, 8...","[[0.07308, 17.5856, 36.12836, 60.26956, 74.227...","[[472.01648, 483.401, 492.4544, 503.607, 513.0..."
4,caf74,0125_60_72,419.879942,M,app_ps1,ACC,RSU,0.72,4,"[[0.013360000000034233, 0.27715999999998076, 0...","[[0.49224, 0.54008, 0.5746, 0.0280000000000000...","[[0.21663999999998396, 0.022919999999999163, 0...","[104, 16, 68, 284, 24, 184, 136, 16, 252, 92, ...","[472, 156, 248, 52, 116, 516, 148, 784, 248, 1...","[184, 100, 76, 92]","[[836.60528, 857.51452, 876.9592, 890.71856, 9...","[[0.19684, 21.43652, 40.70544, 58.44296, 80.45...","[[472.02264, 485.14892, 500.4822, 524.28324, 5..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,caf74,0125_60_72,419.879942,M,app_ps1,V1,RSU,0.64,159,"[[0.2461199999999053, 0.0017200000000912041, 0...","[[0.09048, 0.1826000000000001, 0.17428, 0.4866...","[[0.1208000000000311, 0.22531999999995378, 0.0...","[104, 16, 68, 284, 24, 184, 136, 16, 252, 92, ...","[472, 156, 248, 52, 116, 516, 148, 784, 248, 1...","[184, 100, 76, 92]","[[837.407, 879.33688, 898.55612, 925.70284, 93...","[[0.8662, 44.29716, 82.32916, 132.16508, 176.7...","[[472.1076, 497.6672, 532.84576, 561.84196, 58..."
160,caf74,0125_60_72,419.879942,M,app_ps1,V1,FS,0.28,160,"[[0.021079999999983556, 0.20900000000006003, 0...","[[0.5136000000000001, 0.24539999999999995, 0.1...","[[0.01576000000000022, 0.19815999999997302, 0....","[104, 16, 68, 284, 24, 184, 136, 16, 252, 92, ...","[472, 156, 248, 52, 116, 516, 148, 784, 248, 1...","[184, 100, 76, 92]","[[836.19228, 847.0246, 857.58872, 863.54028, 8...","[[0.45944, 15.89832, 35.39152, 42.5668, 58.538...","[[472.29772, 476.26248, 487.409, 492.49608, 49..."
161,caf74,0125_60_72,419.879942,M,app_ps1,V1,FS,0.12,161,"[[0.0069200000000364525, 0.019279999999980646,...","[[0.08036, 0.023680000000000007, 0.01007999999...","[[0.07200000000000273, 0.009880000000009659, 0...","[104, 16, 68, 284, 24, 184, 136, 16, 252, 92, ...","[472, 156, 248, 52, 116, 516, 148, 784, 248, 1...","[184, 100, 76, 92]","[[836.04972, 839.11668, 842.21768, 845.18996, ...","[[0.00312, 5.07388, 10.12156, 13.97984, 17.675...","[[472.03404, 475.09288, 477.81636, 480.6998, 4..."
162,caf74,0125_60_72,419.879942,M,app_ps1,V1,FS,0.16,162,"[[0.02955999999994674, 0.04952000000002954, 0....","[[0.6140799999999998, 0.4956800000000001, 0.19...","[[0.041800000000023374, 0.11687999999998056, 0...","[104, 16, 68, 284, 24, 184, 136, 16, 252, 92, ...","[472, 156, 248, 52, 116, 516, 148, 784, 248, 1...","[184, 100, 76, 92]","[[836.30208, 847.24236, 855.96, 871.33588, 884...","[[0.6256, 19.46392, 43.33672, 69.41724, 84.135...","[[472.24712, 487.76308, 501.39796, 515.19, 531..."
163,caf74,0125_60_72,419.879942,M,app_ps1,V1,FS,0.12,163,"[[0.03687999999999647, 0.2440800000000536, 0.0...","[[0.0958, 0.07216, 0.04496, 0.0015199999999999...","[[0.05256000000002814, 0.02311999999994896, 0....","[104, 16, 68, 284, 24, 184, 136, 16, 252, 92, ...","[472, 156, 248, 52, 116, 516, 148, 784, 248, 1...","[184, 100, 76, 92]","[[836.01288, 839.05112, 842.045, 844.7808, 847...","[[0.01144, 5.2956, 9.20064, 12.39664, 15.62096...","[[472.02184, 474.66464, 477.27848, 479.47564, ..."

Working on caf75
Has 2 files to go through
got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,caf75,0125_53_64,388.546215,M,app_ps1,ACC,RSU,0.72,0,"[[0.05607999999983804, 0.012920000000121945, 0...","[[0.09631999999999999, 0.009920000000000012, 0...","[[0.015240000000630971, 0.0039999999999054126,...","[368, 12, 500, 8, 248, 384, 64, 4, 84, 220, 72...","[2364, 652, 4, 1372, 648, 524, 40, 20, 80, 56,...","[72, 56, 16, 80, 4]","[[2364.034, 2377.01508, 2389.32524, 2396.2672,...","[[0.05248, 7.21212, 19.55764, 33.5388, 45.3564...","[[6212.00296, 6217.04532, 6221.91356, 6226.138..."
1,caf75,0125_53_64,388.546215,M,app_ps1,ACC,RSU,0.60,1,"[[0.18699999999989814, 0.1888400000002548, 0.1...","[[0.30212, 0.15652, 0.41696, 0.011000000000000...","[[0.07172000000082335, 0.04327999999986787, 0....","[368, 12, 500, 8, 248, 384, 64, 4, 84, 220, 72...","[2364, 652, 4, 1372, 648, 524, 40, 20, 80, 56,...","[72, 56, 16, 80, 4]","[[2364.41356, 2404.8594, 2436.99204, 2461.4738...","[[0.05256, 40.40744, 81.1514, 120.86792, 151.2...","[[6212.6176, 6227.55816, 6240.0194, 6255.88052..."
2,caf75,0125_53_64,388.546215,M,app_ps1,ACC,RSU,0.68,2,"[[1.4669600000001992, 0.08280000000013388, 1.8...","[[0.34796000000000005, 0.06671999999999995, 0....","[[0.12399999999979627, 0.04187999999976455, 0....","[368, 12, 500, 8, 248, 384, 64, 4, 84, 220, 72...","[2364, 652, 4, 1372, 648, 524, 40, 20, 80, 56,...","[72, 56, 16, 80, 4]","[[2364.07284, 2397.00984, 2416.13668, 2450.905...","[[0.0526, 98.92768, 183.67944, 279.64284, 359....","[[6212.53084, 6240.54828, 6276.01284, 6283.635..."
3,caf75,0125_53_64,388.546215,M,app_ps1,ACC,RSU,0.64,3,"[[0.06935999999996056, 0.011079999999765278, 0...","[[0.10987999999999999, 0.010959999999999998, 0...","[[0.005879999999706342, 0.014960000000428408, ...","[368, 12, 500, 8, 248, 384, 64, 4, 84, 220, 72...","[2364, 652, 4, 1372, 648, 524, 40, 20, 80, 56,...","[72, 56, 16, 80, 4]","[[2364.0828, 2371.66316, 2381.05824, 2387.3708...","[[0.01556, 8.68356, 19.92896, 34.92092, 50.524...","[[6212.0118, 6214.06224, 6216.87232, 6220.9684..."
4,caf75,0125_53_64,388.546215,M,app_ps1,ACC,RSU,0.40,4,"[[0.006080000000110886, 0.05623999999988882, 0...","[[0.005639999999999999, 0.010360000000000001, ...","[[0.008160000000316359, 0.0028800000000046566,...","[368, 12, 500, 8, 248, 384, 64, 4, 84, 220, 72...","[2364, 652, 4, 1372, 648, 524, 40, 20, 80, 56,...","[72, 56, 16, 80, 4]","[[2364.08992, 2371.28948, 2381.66336, 2388.998...","[[0.0538, 4.25716, 7.65864, 13.45388, 17.43392...","[[6212.00908, 6214.0016, 6215.6542, 6217.887, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,caf75,0125_53_64,388.546215,M,app_ps1,V1,FS,0.32,98,"[[0.20163999999977023, 0.09308000000009997, 0....","[[0.96572, 0.16627999999999987, 0.181560000000...","[[0.07768000000032771, 0.1333199999999124, 0.6...","[368, 12, 500, 8, 248, 384, 64, 4, 84, 220, 72...","[2364, 652, 4, 1372, 648, 524, 40, 20, 80, 56,...","[72, 56, 16, 80, 4]","[[2364.07524, 2396.52516, 2432.88112, 2467.088...","[[0.01312, 58.7128, 181.56012, 311.47012, 385....","[[6212.13916, 6229.55472, 6245.17648, 6265.341..."
99,caf75,0125_53_64,388.546215,M,app_ps1,V1,RSU,0.64,99,"[[0.05912000000034823, 0.10339999999996508, 0....","[[3.6575200000000003, 0.010239999999999583, 0....","[[0.03675999999995838, 0.05680000000029395, 0....","[368, 12, 500, 8, 248, 384, 64, 4, 84, 220, 72...","[2364, 652, 4, 1372, 648, 524, 40, 20, 80, 56,...","[72, 56, 16, 80, 4]","[[2364.04692, 2384.73848, 2410.32924, 2445.604...","[[0.78652, 266.38384, 431.80404, 581.0692, 644...","[[6212.22088, 6220.07128, 6228.0642, 6234.7735..."
100,caf75,0125_53_64,388.546215,M,app_ps1,V1,RSU,0.56,100,"[[0.11524000000008527, 0.01823999999987791, 0....","[[0.476, 0.03971999999999998, 0.05668000000000...","[[0.03459999999995489, 0.0342000000000553, 1.5...","[368, 12, 500, 8, 248, 384, 64, 4, 84, 220, 72...","[2364, 652, 4, 1372, 648, 524, 40, 20, 80, 56,...","[72, 56, 16, 80, 4]","[[2364.359, 2425.3542, 2490.97832, 2606.19008,...","[[0.80464, 388.34524, 556.52592, 649.01148, 67...","[[6212.24104, 6258.91476, 6283.83604], [6809.3..."
101,caf75,0125_53_64,388.546215,M,app_ps1,V1,RSU,0.60,101,"[[0.004439999999704014, 0.0019600000000536966,...","[[0.059840000000000004, 0.009479999999999995, ...","[[0.016080000000329164, 0.025200000000040745, ...","[368, 12, 500, 8, 248, 384, 64, 4, 84, 220, 72...","[2364, 652, 4, 1372, 648, 524, 40, 20, 80, 56,...","[72, 56, 16, 80, 4]","[[2364.22688, 2369.16608, 2376.44328, 2384.814...","[[0.0016, 6.47332, 14.32256, 23.2614, 38.08208...","[[6212.04836, 6219.30812, 6222.58144, 6226.600..."
102,caf75,0125_53_64,388.546215,M,app_ps1,V1,FS,0.12,102,"[[1.2263600000001134, 1.8123599999998987, 0.32...","[[2.2502000000000004, 0.44723999999999986, 0.0...","[[3.1261199999999008, 3.131080000000111, 1.068...","[368, 12, 500, 8, 248, 384, 64, 4, 84, 220, 72...","[2364, 652, 4, 1372, 648, 524, 40, 20, 80, 56,...","[72, 56, 16, 80, 4]","[[2364.81376, 2458.51792, 2547.93148, 2622.887...","[[0.41076, 312.91648, 533.69412, 641.22876, 72...","[[6213.00364, 6280.84668, 6283.5484], [6823.25..."

got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,caf75,0125_65_76,389.046215,M,app_ps1,ACC,RSU,0.64,0,"[[1.52616, 3.98604, 0.09755999999999965, 0.280...","[[1.062560000000019, 1.3972400000000107, 1.590...","[[0.6703600000000733, 0.2359199999991688, 0.72...","[32, 24, 56, 20, 136, 36, 120, 40, 28, 12, 12,...","[76, 56, 28, 28, 24, 32, 44, 36, 36, 56, 16, 2...","[40, 12, 32, 84, 204, 32, 16, 132]","[[4e-05, 26.73832], [70.72144, 90.75324], [124...","[[469.57752, 534.47652], [967.43692, 1013.0119...","[[15624.14096, 15652.10272, 15662.2546], [1640..."
1,caf75,0125_65_76,389.046215,M,app_ps1,ACC,RSU,0.72,1,"[[0.018839999999999968, 0.11327999999999999, 0...","[[0.17599999999998772, 0.4663999999999646, 0.0...","[[0.27351999999882537, 0.3758800000014162, 0.0...","[32, 24, 56, 20, 136, 36, 120, 40, 28, 12, 12,...","[76, 56, 28, 28, 24, 32, 44, 36, 36, 56, 16, 2...","[40, 12, 32, 84, 204, 32, 16, 132]","[[0.37364, 22.47896, 31.76728], [68.045, 90.91...","[[460.01028, 491.82888, 518.69464, 535.89676],...","[[15624.38996, 15631.74648, 15635.3154, 15641...."
2,caf75,0125_65_76,389.046215,M,app_ps1,ACC,RSU,0.64,2,"[[0.10908000000000007, 1.524, 1.9002, 7.40136,...","[[0.03307999999998401, 0.1952800000000252, 0.2...","[[0.8235199999999168, 0.16416000000026543, 0.0...","[32, 24, 56, 20, 136, 36, 120, 40, 28, 12, 12,...","[76, 56, 28, 28, 24, 32, 44, 36, 36, 56, 16, 2...","[40, 12, 32, 84, 204, 32, 16, 132]","[[2.09008, 31.90712], [68.06208, 91.37668], [1...","[[460.69088, 535.359], [967.3112, 1005.46364, ...","[[15624.21208, 15633.42768, 15642.7752, 15653...."
3,caf75,0125_65_76,389.046215,M,app_ps1,ACC,RSU,0.64,3,"[[0.23276, 0.17084, 0.054800000000000015, 0.04...","[[0.0017200000000343607, 0.05216000000001486, ...","[[0.017079999999623396, 0.0973199999989447, 0....","[32, 24, 56, 20, 136, 36, 120, 40, 28, 12, 12,...","[76, 56, 28, 28, 24, 32, 44, 36, 36, 56, 16, 2...","[40, 12, 32, 84, 204, 32, 16, 132]","[[4e-05, 4.93392, 8.05412, 11.46896, 16.4096, ...","[[460.09036, 465.57244, 470.8856, 476.69612, 4...","[[15624.04432, 15627.28936, 15629.57516, 15631..."
4,caf75,0125_65_76,389.046215,M,app_ps1,ACC,RSU,0.68,4,"[[0.14748, 0.15476, 0.04244000000000003, 0.193...","[[0.8936800000000176, 0.08247999999997546, 0.8...","[[1.0996000000013737, 0.434079999999085, 0.884...","[32, 24, 56, 20, 136, 36, 120, 40, 28, 12, 12,...","[76, 56, 28, 28, 24, 32, 44, 36, 36, 56, 16, 2...","[40, 12, 32, 84, 204, 32, 16, 132]","[[0.17824, 21.62772, 31.91036], [68.1102, 91.3...","[[460.65256, 494.62916, 528.5854, 535.75864], ...","[[15624.06656, 15643.76416, 15656.19416, 15663..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,caf75,0125_65_76,389.046215,M,app_ps1,V1,RSU,0.80,201,"[[0.8942800000000001, 0.08796000000000004, 0.1...","[[0.17411999999995942, 0.4592000000000098, 0.0...","[[0.6083199999993667, 0.04396000000087952, 0.0...","[32, 24, 56, 20, 136, 36, 120, 40, 28, 12, 12,...","[76, 56, 28, 28, 24, 32, 44, 36, 36, 56, 16, 2...","[40, 12, 32, 84, 204, 32, 16, 132]","[[0.5114, 31.91396], [69.86288, 91.93092], [12...","[[460.0588, 490.25576, 521.68112, 535.65828], ...","[[15624.06156, 15635.8316, 15646.20172, 15657...."
202,caf75,0125_65_76,389.046215,M,app_ps1,V1,RSU,0.64,202,"[[28.936079999999997], [0.03315999999999519, 2...","[[4.358360000000005, 0.2560399999999845, 9.094...","[[1.8452000000015687, 0.004119999999602442, 0....","[32, 24, 56, 20, 136, 36, 120, 40, 28, 12, 12,...","[76, 56, 28, 28, 24, 32, 44, 36, 36, 56, 16, 2...","[40, 12, 32, 84, 204, 32, 16, 132]","[[1.3866, 30.32268], [80.70312, 89.82292], [13...","[[461.41548, 535.0164], [1003.2838, 1003.29468...","[[15624.68976, 15660.19512], [16401.16204, 164..."
203,caf75,0125_65_76,389.046215,M,app_ps1,V1,RSU,0.48,203,"[[0.5899200000000002, 0.4256399999999996, 0.77...","[[0.8615599999999972, 0.3152399999999602, 1.35...","[[3.045320000001084, 0.49835999999959313, 0.51...","[32, 24, 56, 20, 136, 36, 120, 40, 28, 12, 12,...","[76, 56, 28, 28, 24, 32, 44, 36, 36, 56, 16, 2...","[40, 12, 32, 84, 204, 32, 16, 132]","[[3.0176, 30.755], [70.342, 90.787], [124.5723...","[[461.3962, 532.76544, 534.99596], [964.27816,...","[[15624.00636, 15657.87004, 15663.95892], [164..."
204,caf75,0125_65_76,389.046215,M,app_ps1,V1,RSU,0.56,204,"[[0.29923999999999995, 0.638, 1.46004, 0.16780...","[[0.11276000000003705, 0.700999999999965, 0.26...","[[0.7265200000001641, 0.734440000000177, 0.158...","[32, 24, 56, 20, 136, 36, 120, 40, 28, 12, 12,...","[76, 56, 28, 28, 24, 32, 44, 36, 36, 56, 16, 2...","[40, 12, 32, 84, 204, 32, 16, 132]","[[0.00036, 31.99828], [68.12508, 91.85932], [1...","[[460.31888, 496.72872, 535.56276], [964.25452...","[[15624.04988, 15650.78096, 15663.791], [16400..."
205,caf75,0125_65_76,389.046215,M,app_ps1,V1,FS,0.16,205,"[[1.7687599999999999, 0.19032000000000027, 0.1...","[[0.8123199999999997, 0.13207999999997355, 0.4...","[[0.12376000000040221, 0.03883999999925436, 0....","[32, 24, 56, 20, 136, 36, 120, 40, 28, 12, 12,...","[76, 56, 28, 28, 24, 32, 44, 36, 36, 56, 16, 2...","[40, 12, 32, 84, 204, 32, 16, 132]","[[0.19056, 31.97324], [68.50912, 91.97016], [1...","[[461.32396, 518.47108, 535.52048], [966.76196...","[[15624.22776, 15640.42644, 15660.30552, 15663..."

Working on caf77
Has 2 files to go through
got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,caf77,0202_0_12,394.290556,F,wt,RSC,RSU,0.64,0,"[[0.2418800000000374, 0.02476000000001477, 0.0...","[[0.11387999999999465, 0.015399999999999636, 0...","[[0.022679999999999992, 0.005040000000000003, ...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.05848, 1168.25148, 1173.4232, 1181.2870...","[[360.05564, 367.81796, 375.11144, 380.25836, ...","[[0.0442, 4.72624, 9.19628, 13.87772, 18.55548..."
1,caf77,0202_0_12,394.290556,F,wt,RSC,FS,0.20,1,"[[0.012560000000121363, 0.009839999999940119, ...","[[0.0706000000000131, 0.06592000000000553, 0.0...","[[0.008800000000000002, 0.008599999999999997, ...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.01004, 1171.43504, 1178.32824, 1187.639...","[[360.01092, 365.66796, 370.51248, 375.96096, ...","[[0.08152, 3.07984, 6.19068, 9.4544, 11.90352,..."
2,caf77,0202_0_12,394.290556,F,wt,RSC,RSU,0.60,2,"[[0.0077599999999620195, 0.5819599999999809, 0...","[[0.12871999999998707, 0.20220000000000482, 0....","[[0.16252000000000005, 0.29452, 0.228959999999...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.01792, 1193.98832, 1232.2514, 1247.4974...","[[360.5516, 387.79168, 431.59536, 481.09448, 5...","[[0.25336, 20.02536, 37.143, 57.28428, 82.7180..."
3,caf77,0202_0_12,394.290556,F,wt,RSC,FS,0.20,3,"[[0.0057200000001103035, 0.005359999999882348,...","[[0.013959999999997308, 0.03595999999998867, 0...","[[0.019240000000000035, 0.01851999999999998, 0...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.31136, 1169.93604, 1179.29224, 1190.260...","[[360.11244, 370.6052, 377.4664, 385.50268, 39...","[[0.29288, 5.14128, 10.7572, 14.20384, 17.5305..."
4,caf77,0202_0_12,394.290556,F,wt,RSC,RSU,0.60,4,"[[0.0018800000000283035, 0.022559999999884894,...","[[0.026520000000004984, 0.052120000000002165, ...","[[0.015240000000000004, 0.1264, 0.009679999999...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.02772, 1174.26016, 1188.31032, 1198.342...","[[360.08292, 373.65036, 380.14248, 392.626, 40...","[[0.08208, 4.25244, 7.69452, 12.15988, 15.4188..."
5,caf77,0202_0_12,394.290556,F,wt,RSC,RSU,0.60,5,"[[0.008919999999989159, 0.28327999999987696, 0...","[[0.4799199999999928, 0.1724399999999946, 0.19...","[[0.12412000000000001, 0.09640000000000004, 0....","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.01284, 1187.323, 1215.89568, 1247.91276...","[[360.46796, 387.85024, 444.31328, 490.63648, ...","[[0.48988, 19.80256, 39.03748, 60.57364, 85.90..."
6,caf77,0202_0_12,394.290556,F,wt,RSC,RSU,0.96,6,"[[0.027079999999841675, 0.46412000000009357, 1...","[[0.004519999999956781, 0.04923999999999751, 0...","[[0.35224, 0.03660000000000002, 0.47432, 0.235...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.30212, 1200.69328, 1244.79156, 1247.841...","[[360.16412, 421.63064, 466.215, 499.69356, 54...","[[0.0516, 30.48084, 64.75208, 103.96748, 150.8..."
7,caf77,0202_0_12,394.290556,F,wt,RSC,RSU,0.88,7,"[[0.06780000000003383, 0.48095999999986816, 0....","[[0.7790400000000091, 0.8010799999999563, 0.00...","[[0.29292, 0.17132000000000003, 1.605, 0.76080...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.23432, 1212.02924, 1247.9266], [1341.50...","[[360.62252, 423.67232, 492.29752, 554.94052, ...","[[0.08952, 45.56068, 103.4508, 172.21888, 233...."
8,caf77,0202_0_12,394.290556,F,wt,RSC,RSU,0.84,8,"[[0.02152000000000953, 0.2073600000001079, 0.9...","[[1.9888799999999947, 0.05608000000000857, 1.1...","[[0.43756, 0.75624, 0.13816000000000006, 0.157...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.28948, 1201.7268, 1247.85488], [1340.35...","[[360.56908, 417.5808, 470.29916, 523.01316, 5...","[[4e-05, 41.91112, 89.75208, 147.78724, 206.01..."
9,caf77,0202_0_12,394.290556,F,wt,RSC,FS,0.20,9,"[[0.38772000000017215, 0.0033599999999296415, ...","[[0.4943200000000161, 0.6021999999999821, 0.70...","[[0.0020799999999999985, 0.25076000000000004, ...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1162.11144, 1192.43564, 1227.02612, 1247.920...","[[360.23552, 392.7282, 427.47084, 466.08428, 4...","[[0.1314, 25.02808, 49.01208, 72.75244, 93.887..."
10,caf77,0202_0_12,394.290556,F,wt,RSC,RSU,0.60,10,"[[0.12928000000010798, 2.3439599999999245, 0.9...","[[0.09300000000001774, 0.39100000000001955, 0....","[[0.12108000000000002, 0.15316000000000002, 0....","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.38656, 1201.335, 1247.52808, 1247.53152...","[[360.07732, 401.7092, 437.4056, 473.59808, 52...","[[0.253, 13.6334, 26.36648, 38.2938, 52.24304,..."
11,caf77,0202_0_12,394.290556,F,wt,RSC,FS,0.16,11,"[[0.3129599999999755, 1.4414800000001833, 0.81...","[[5.22696000000002, 0.1948799999999551, 9.8296...","[[0.49883999999999995, 1.1182400000000001, 1.0...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1170.86692, 1240.535], [1345.5126, 1381.6205...","[[362.64884, 704.73652], [851.8838, 1149.14936...","[[3.78616, 202.04988, 359.38332], [724.81084, ..."
12,caf77,0202_0_12,394.290556,F,wt,RSC,FS,0.20,12,"[[0.2683199999999033, 0.11112000000002809, 0.3...","[[0.09540000000004056, 0.43387999999998783, 0....","[[0.008039999999999992, 0.09288000000000002, 0...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.06052, 1172.6468, 1189.64196, 1200.3746...","[[360.0712, 372.86696, 388.78932, 404.28904, 4...","[[0.36316, 10.52508, 20.70076, 29.5774, 38.951..."
13,caf77,0202_0_12,394.290556,F,wt,RSC,FS,0.16,13,"[[0.25555999999983214, 1.0730800000001182, 0.4...","[[0.5753599999999892, 0.13440000000002783, 0.0...","[[0.315, 0.048160000000000036, 0.0079999999999...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.07336, 1179.73232, 1197.49764, 1206.466...","[[361.1698, 379.65236, 392.17376, 410.12028, 4...","[[4e-05, 12.65672, 28.03852, 40.59876, 52.5086..."
14,caf77,0202_0_12,394.290556,F,wt,ACC,RSU,0.68,14,"[[0.310799999999972, 0.41840000000001965, 0.00...","[[0.0034800000000245745, 0.005280000000027485,...","[[0.0172, 0.30232000000000003, 0.8039999999999...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.39304, 1187.74936, 1237.38732, 1247.715...","[[361.21356, 406.22388, 458.62656, 502.04276, ...","[[4e-05, 37.82384, 98.18516, 163.36592, 224.12..."
15,caf77,0202_0_12,394.290556,F,wt,ACC,RSU,0.68,15,"[[0.018039999999928114, 0.0359600000001592, 0....","[[5.685320000000047, 2.9628399999999715, 1.260...","[[10.832799999999999, 10.32644, 4.734960000000...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.77424, 1223.47052, 1244.80976], [1343.4...","[[361.30832, 458.30104, 502.4842, 553.03084, 5...","[[2.68256, 261.37324, 357.74228], [720.68944, ..."
16,caf77,0202_0_12,394.290556,F,wt,ACC,RSU,0.72,16,"[[0.018039999999928114, 0.028040000000146392, ...","[[2.6387599999999907, 0.0036000000000058208, 0...","[[0.0038799999999998835, 0.012760000000000105,...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.77432, 1210.29072, 1244.81504], [1343.4...","[[360.25012, 402.73716, 460.86536, 538.36704, ...","[[1.65856, 40.3198, 67.35856, 107.62944, 148.2..."
17,caf77,0202_0_12,394.290556,F,wt,ACC,RSU,0.72,17,"[[0.38203999999996086, 0.011400000000094224, 0...","[[0.038239999999973406, 0.17831999999998516, 0...","[[0.1524399999999999, 0.29880000000000007, 0.1...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.7602, 1188.7812, 1208.21144, 1233.1818,...","[[360.0742, 386.69868, 414.66552, 444.37084, 4...","[[0.63492, 27.62692, 43.01368, 58.31924, 82.10..."
18,caf77,0202_0_12,394.290556,F,wt,ACC,FS,0.36,18,"[[0.04600000000004911, 0.4574399999999059, 0.0...","[[0.12796000000003005, 1.5521999999999707, 0.2...","[[0.14572, 0.05424000000000001, 0.63224, 0.091...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.27252, 1185.18056, 1207.266, 1235.90616...","[[360.6112, 400.40364, 423.293, 449.50428, 478...","[[0.19936, 21.35196, 42.61004, 71.68712, 92.97..."
19,caf77,0202_0_12,394.290556,F,wt,V1,RSU,0.52,19,"[[1.2093599999998332, 0.3987600000000384, 0.14...","[[0.04079999999999018, 2.3354400000000055, 1.6...","[[0.024520000000000014, 0.5572, 0.121519999999...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.05644, 1205.80368, 1247.85296], [1340.3...","[[360.23288, 401.80812, 453.62524, 494.8512, 5...","[[0.1896, 37.43252, 63.47704, 103.67384, 133.2..."
20,caf77,0202_0_12,394.290556,F,wt,V1,RSU,0.64,20,"[[0.02980000000002292, 0.16239999999993415, 0....","[[0.08604000000002543, 0.12251999999995178, 0....","[[0.023680000000000007, 0.013679999999999998, ...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.28568, 1180.81292, 1198.67752, 1219.314...","[[360.1524, 376.64568, 390.43244, 409.71996, 4...","[[0.1432, 16.44708, 30.13952, 43.97176, 58.074..."
21,caf77,0202_0_12,394.290556,F,wt,V1,RSU,0.72,21,"[[1.3209999999999127, 2.2399199999999837, 0.13...","[[0.23340000000001737, 0.12763999999998532, 0....","[[0.11664, 0.18451999999999996, 0.175200000000...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.02836, 1208.5112, 1247.94664], [1340.00...","[[360.0542, 414.13632, 477.29232, 548.95428, 6...","[[0.20724, 31.27808, 51.837, 87.382, 116.49548..."
22,caf77,0202_0_12,394.290556,F,wt,V1,RSU,0.64,22,"[[0.044520000000147775, 0.076759999999922, 0.3...","[[0.431919999999991, 0.0614800000000173, 0.120...","[[0.11943999999999999, 0.05952000000000002, 0....","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.05632, 1184.95328, 1216.38392, 1246.133...","[[360.42932, 383.92364, 410.16132, 448.58172, ...","[[0.25744, 21.50544, 40.05796, 56.52692, 73.96..."
23,caf77,0202_0_12,394.290556,F,wt,V1,RSU,0.72,23,"[[0.4682799999998224, 0.005600000000185901, 1....","[[0.345359999999971, 0.05988000000002103, 0.08...","[[0.012199999999999989, 0.40619999999999995, 0...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.06364, 1180.284, 1194.58912, 1211.1476,...","[[360.187, 374.18036, 387.4086, 408.9896, 424....","[[0.18956, 5.81656, 10.28976, 14.44896, 24.824..."
24,caf77,0202_0_12,394.290556,F,wt,V1,RSU,0.60,24,"[[0.06888000000003558, 0.3491200000000845, 0.0...","[[0.2442399999999907, 0.055920000000014625, 0....","[[0.07488, 0.6773199999999999, 0.1352800000000...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.08016, 1167.68084, 1175.09532, 1183.378...","[[360.57092, 370.62908, 375.92556, 382.12696, ...","[[0.27552, 5.41868, 11.9452, 19.51084, 26.0540..."
25,caf77,0202_0_12,394.290556,F,wt,V1,RSU,0.40,25,"[[0.4228800000000774, 0.28315999999995256, 0.0...","[[0.8124000000000251, 0.020080000000007203, 0....","[[0.020079999999999987, 0.06688000000000005, 0...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1161.2756, 1184.75476, 1205.69144, 1227.6972...","[[360.6072, 376.9312, 387.3158, 399.96364, 418...","[[0.61176, 8.1028, 13.42404, 20.0126, 30.01444..."
26,caf77,0202_0_12,394.290556,F,wt,V1,RSU,0.72,26,"[[0.008080000000063592, 0.016279999999824213, ...","[[0.010879999999986012, 0.15964000000002443, 0...","[[0.13591999999999999, 0.05488000000000004, 0....","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.07204, 1166.86448, 1172.24032, 1179.270...","[[360.2104, 366.7664, 371.93016, 377.32464, 38...","[[0.13748, 4.4974, 8.55548, 12.95808, 17.877, ..."
27,caf77,0202_0_12,394.290556,F,wt,V1,RSU,0.56,27,"[[1.6043600000000424, 1.4767199999998866, 0.07...","[[0.7483199999999783, 0.5575200000000109, 0.95...","[[0.08275999999999994, 0.06908000000000003, 0....","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.11832, 1217.10628, 1247.29924], [1340.7...","[[360.00972, 424.20608, 465.1252, 500.974, 571...","[[1.23736, 41.99408, 71.105, 117.4424, 175.103..."
28,caf77,0202_0_12,394.290556,F,wt,V1,RSU,0.64,28,"[[0.15768000000002758, 0.026720000000068467, 1...","[[0.10099999999999909, 0.13560000000001082, 0....","[[1.09416, 0.12796000000000007, 0.209879999999...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1162.30836, 1204.9324, 1237.2084, 1247.84944...","[[360.08276, 382.04908, 420.389, 454.26912, 46...","[[0.28064, 12.94796, 30.54456, 41.04624, 44.55..."
29,caf77,0202_0_12,394.290556,F,wt,V1,RSU,0.52,29,"[[0.07151999999996406, 0.07252000000016778, 1....","[[0.6476799999999798, 0.42508000000003676, 0.8...","[[0.17928000000000002, 0.82404, 0.841919999999...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.13944, 1207.062, 1247.519], [1340.09052...","[[360.02992, 423.26872, 478.1384, 531.19644, 5...","[[0.2074, 31.01552, 56.23048, 85.6316, 117.754..."
30,caf77,0202_0_12,394.290556,F,wt,V1,RSU,0.52,30,"[[0.09583999999995285, 0.8063999999999396, 0.1...","[[0.29032000000000835, 0.276800000000037, 0.00...","[[1.172, 0.09356000000000009, 0.06867999999999...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.30124, 1196.00496, 1229.3554, 1247.0450...","[[360.15876, 396.4322, 443.72248, 475.6186, 50...","[[4e-05, 18.74152, 41.83656, 51.80732, 78.1874..."
31,caf77,0202_0_12,394.290556,F,wt,V1,RSU,0.60,31,"[[0.24796000000014828, 0.0025599999999030842, ...","[[0.0026799999999980173, 0.0867200000000139, 0...","[[0.04035999999999999, 0.05816000000000002, 0....","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.149, 1182.55044, 1195.9334, 1207.99612,...","[[360.166, 376.87768, 396.03332, 413.10968, 42...","[[0.09468, 7.83712, 13.3576, 23.33412, 30.9023..."
32,caf77,0202_0_12,394.290556,F,wt,V1,RSU,0.60,32,"[[0.49315999999998894, 0.10092000000008738, 0....","[[0.22120000000001028, 0.025360000000034688, 0...","[[0.70928, 0.7664399999999999, 0.1058799999999...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.84432, 1181.41024, 1199.79784, 1224.678...","[[360.25548, 383.20704, 411.50476, 438.44968, ...","[[0.10636, 17.23048, 37.0586, 50.0172, 67.6264..."
33,caf77,0202_0_12,394.290556,F,wt,V1,RSU,0.52,33,"[[0.10167999999998756, 0.25307999999995445, 0....","[[0.26636000000002014, 0.5340400000000045, 1.0...","[[0.21040000000000003, 1.52212, 0.246999999999...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.64024, 1205.23152, 1243.51748, 1247.763...","[[360.00572, 415.71672, 463.6042, 509.64316, 5...","[[0.66036, 30.32076, 59.51664, 99.5194, 146.87..."
34,caf77,0202_0_12,394.290556,F,wt,V1,RSU,0.64,34,"[[0.040759999999863794, 0.019760000000133005, ...","[[0.039720000000045275, 0.005159999999989395, ...","[[0.024319999999999998, 0.07576, 0.0474, 0.001...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.01168, 1163.38104, 1165.81712, 1168.159...","[[360.03432, 363.35424, 366.73324, 369.60612, ...","[[0.00124, 2.54236, 4.26148, 5.9824, 7.2146, 9..."
35,caf77,0202_0_12,394.290556,F,wt,V1,RSU,0.64,35,"[[0.005599999999958527, 0.2192400000001271, 0....","[[0.015880000000038308, 0.029240000000015698, ...","[[0.13388, 0.06059999999999999, 0.115640000000...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.06648, 1169.03444, 1175.79924, 1183.881...","[[360.0728, 370.22128, 377.78028, 386.55808, 3...","[[0.15052, 5.15744, 10.20312, 15.17684, 23.599..."
36,caf77,0202_0_12,394.290556,F,wt,V1,RSU,0.64,36,"[[1.2180399999999736, 0.28719999999998436, 2.9...","[[0.3104799999999841, 0.4447600000000307, 0.35...","[[0.5908800000000001, 0.06091999999999986, 0.0...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1161.69824, 1225.69568, 1247.49076], [1347.2...","[[363.54084, 445.05188, 482.30992, 521.10332, ...","[[1.77476, 37.12872, 48.84596, 71.13172, 115.5..."
37,caf77,0202_0_12,394.290556,F,wt,V1,RSU,0.64,37,"[[0.47664000000008855, 1.005959999999959, 0.28...","[[0.2570800000000304, 0.1252399999999625, 0.02...","[[0.017479999999999996, 0.44196, 0.19035999999...","[88, 48, 32, 32, 32, 108, 60, 108, 516, 1080, ...","[360, 320, 380, 760, 600, 280, 240, 360, 440, ...","[360, 120, 260, 140, 80, 80, 80, 80, 120, 40, ...","[[1160.1662, 1184.07476, 1200.20432, 1215.8346...","[[360.50104, 376.82796, 388.64976, 406.97912, ...","[[0.23696, 7.85268, 18.76308, 26.8568, 37.3333..."

got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,caf77,0202_12_24,394.790567,F,wt,RSC,RSU,0.60,0,"[[1.0212399999999917, 0.9769600000000054, 0.91...","[[0.24408, 0.01856000000000002, 0.48668, 0.035...","[[0.09172000000000935, 0.038919999999961874, 0...","[544, 28, 16, 16, 8, 180, 16, 84, 20, 8, 84, 2...","[92, 384, 320, 392, 180, 824, 52, 124, 396, 10...","[16, 100, 72, 88, 28, 24, 80, 64, 64, 112, 76,...","[[92.61512, 127.2806, 171.38028, 218.86828, 25...","[[4e-05, 44.21656, 91.03152], [636.00064, 682....","[[1020.11756, 1035.70584], [2120.03912, 2134.4..."
1,caf77,0202_12_24,394.790567,F,wt,RSC,FS,0.20,1,"[[0.14303999999999917, 0.008479999999991605, 0...","[[0.0041200000000000125, 0.01868000000000003, ...","[[0.024400000000014188, 0.05743999999992866, 0...","[544, 28, 16, 16, 8, 180, 16, 84, 20, 8, 84, 2...","[92, 384, 320, 392, 180, 824, 52, 124, 396, 10...","[16, 100, 72, 88, 28, 24, 80, 64, 64, 112, 76,...","[[92.01712, 98.9186, 102.8434, 104.2708, 106.6...","[[0.25176, 6.72508, 10.78296, 15.56384, 19.765...","[[1020.01148, 1026.71792, 1032.8778, 1035.9960..."
2,caf77,0202_12_24,394.790567,F,wt,RSC,RSU,0.64,2,"[[1.1126800000000117, 0.30795999999999424, 0.1...","[[1.6905199999999998, 1.6650799999999997, 0.10...","[[1.0062399999999343, 0.08612000000005082, 0.9...","[544, 28, 16, 16, 8, 180, 16, 84, 20, 8, 84, 2...","[92, 384, 320, 392, 180, 824, 52, 124, 396, 10...","[16, 100, 72, 88, 28, 24, 80, 64, 64, 112, 76,...","[[92.39392, 141.1196, 228.75132, 334.93164, 38...","[[0.7608, 91.11596], [636.295, 694.80008, 751....","[[1021.78336, 1035.67768], [2120.55436, 2142.3..."
3,caf77,0202_12_24,394.790567,F,wt,RSC,RSU,0.60,3,"[[0.17823999999998819, 0.24344000000000676, 0....","[[0.0033999999999999586, 0.18016, 0.0345600000...","[[0.06995999999992364, 0.019160000000056243, 0...","[544, 28, 16, 16, 8, 180, 16, 84, 20, 8, 84, 2...","[92, 384, 320, 392, 180, 824, 52, 124, 396, 10...","[16, 100, 72, 88, 28, 24, 80, 64, 64, 112, 76,...","[[92.21568, 103.47164, 117.09632, 132.276, 152...","[[0.55432, 24.6764, 58.64764, 82.51312, 91.175...","[[1020.0836, 1032.33424, 1035.69016], [2120.16..."
4,caf77,0202_12_24,394.790567,F,wt,RSC,RSU,0.64,4,"[[0.7000799999999998, 0.034960000000012315, 0....","[[0.44872, 0.22195999999999994, 1.64372, 0.568...","[[0.06695999999999458, 0.03687999999999647, 0....","[544, 28, 16, 16, 8, 180, 16, 84, 20, 8, 84, 2...","[92, 384, 320, 392, 180, 824, 52, 124, 396, 10...","[16, 100, 72, 88, 28, 24, 80, 64, 64, 112, 76,...","[[92.02716, 102.24252, 113.99516, 119.88464, 1...","[[0.10736, 24.09896, 54.7354, 85.81088, 91.394...","[[1020.10808, 1035.8818], [2120.06172, 2131.77..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,caf77,0202_12_24,394.790567,F,wt,V1,RSU,0.64,66,"[[0.011039999999994166, 0.15948000000000206, 0...","[[0.08212000000000003, 0.07179999999999997, 0....","[[0.06335999999998876, 0.13975999999991018, 0....","[544, 28, 16, 16, 8, 180, 16, 84, 20, 8, 84, 2...","[92, 384, 320, 392, 180, 824, 52, 124, 396, 10...","[16, 100, 72, 88, 28, 24, 80, 64, 64, 112, 76,...","[[92.23688, 95.42252, 96.56084, 98.13212, 99.1...","[[0.21452, 17.37912, 35.17248, 60.75128, 84.40...","[[1020.02632, 1027.41484, 1035.76724], [2120.0..."
67,caf77,0202_12_24,394.790567,F,wt,V1,RSU,0.72,67,"[[0.4156799999999947, 0.03784000000000276, 0.0...","[[0.13544, 0.125, 0.13379999999999997, 0.17196...","[[0.03276000000005297, 0.10679999999990741, 0....","[544, 28, 16, 16, 8, 180, 16, 84, 20, 8, 84, 2...","[92, 384, 320, 392, 180, 824, 52, 124, 396, 10...","[16, 100, 72, 88, 28, 24, 80, 64, 64, 112, 76,...","[[92.3896, 95.84524, 97.93528, 99.75428, 102.3...","[[0.07644, 10.7248, 24.21124, 35.27284, 46.154...","[[1020.09956, 1026.87408, 1033.07872, 1035.910..."
68,caf77,0202_12_24,394.790567,F,wt,V1,RSU,0.52,68,"[[0.12875999999999976, 0.10656000000000176, 0....","[[0.74668, 0.7007599999999999, 0.0228000000000...","[[0.2656000000000631, 0.19047999999997955, 0.0...","[544, 28, 16, 16, 8, 180, 16, 84, 20, 8, 84, 2...","[92, 384, 320, 392, 180, 824, 52, 124, 396, 10...","[16, 100, 72, 88, 28, 24, 80, 64, 64, 112, 76,...","[[92.01212, 112.07, 146.25308, 185.97448, 220....","[[0.04536, 33.37352, 56.58712, 76.33756, 91.70...","[[1022.01308, 1035.19356], [2120.68872, 2168.9..."
69,caf77,0202_12_24,394.790567,F,wt,V1,RSU,0.72,69,"[[0.5665200000000112, 0.09923999999999467, 1.0...","[[0.11831999999999998, 0.045560000000000045, 0...","[[0.029200000000059845, 0.019440000000031432, ...","[544, 28, 16, 16, 8, 180, 16, 84, 20, 8, 84, 2...","[92, 384, 320, 392, 180, 824, 52, 124, 396, 10...","[16, 100, 72, 88, 28, 24, 80, 64, 64, 112, 76,...","[[92.00764, 96.24156, 98.42792, 101.2212, 105....","[[0.61388, 18.78496, 42.77004, 64.36616, 88.01...","[[1020.05788, 1027.70968, 1034.70664, 1035.887..."
70,caf77,0202_12_24,394.790567,F,wt,V1,RSU,0.64,70,"[[0.8367199999999997, 0.20387999999999806, 0.1...","[[1.1059999999999999, 0.31696000000000013, 0.0...","[[0.043400000000019645, 0.1552399999999352, 0....","[544, 28, 16, 16, 8, 180, 16, 84, 20, 8, 84, 2...","[92, 384, 320, 392, 180, 824, 52, 124, 396, 10...","[16, 100, 72, 88, 28, 24, 80, 64, 64, 112, 76,...","[[92.10596, 95.5364, 96.66448, 98.392, 100.945...","[[0.08336, 15.63892, 30.6322, 50.07592, 69.395...","[[1020.03088, 1029.369, 1035.93396], [2120.169..."

Working on caf81
Has 2 files to go through
got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,caf81,0304_0_12,455.222708,F,wt,ACC,FS,0.32,0,"[[0.16840000000001965, 0.009080000000039945, 0...","[[0.026479999999999948, 0.24988, 0.00208000000...","[[0.2535999999999987, 0.31216000000000577, 0.6...","[312, 360, 48, 128, 116, 116, 516, 4, 4, 16, 1...","[40, 288, 356, 368, 236, 112, 72, 80, 128, 52,...","[116, 20, 28, 72, 48, 52, 56, 76, 28, 48, 108,...","[[832.43908, 852.1962, 880.3516, 906.3532, 931...","[[0.47316, 34.81084, 39.69284], [157.74616, 20...","[[40.41708, 66.44916, 80.87576, 86.12592, 105...."
1,caf81,0304_0_12,455.222708,F,wt,ACC,FS,0.32,1,"[[0.04323999999996886, 0.06180000000006203, 0....","[[0.42768, 0.06612000000000001, 0.171759999999...","[[0.22068000000000154, 0.1751599999999982, 0.0...","[312, 360, 48, 128, 116, 116, 516, 4, 4, 16, 1...","[40, 288, 356, 368, 236, 112, 72, 80, 128, 52,...","[116, 20, 28, 72, 48, 52, 56, 76, 28, 48, 108,...","[[832.11644, 840.51012, 850.13628, 869.01448, ...","[[4e-05, 22.19244, 39.79336], [156.00376, 186....","[[40.01864, 55.32036, 73.00912, 79.69344, 83.0..."
2,caf81,0304_0_12,455.222708,F,wt,ACC,FS,0.16,2,"[[0.06479999999999109, 0.3080800000000181, 0.0...","[[0.321, 0.049679999999999946, 0.0947200000000...","[[1.7091200000000057, 1.4200400000000002, 0.25...","[312, 360, 48, 128, 116, 116, 516, 4, 4, 16, 1...","[40, 288, 356, 368, 236, 112, 72, 80, 128, 52,...","[116, 20, 28, 72, 48, 52, 56, 76, 28, 48, 108,...","[[832.06832, 843.71944, 853.59692, 864.85524, ...","[[0.43168, 18.61468, 39.70812], [156.06228, 17...","[[40.26416, 61.80556, 72.49596, 82.15688, 91.1..."
3,caf81,0304_0_12,455.222708,F,wt,ACC,FS,0.32,3,"[[0.3530799999999772, 0.030279999999947904, 0....","[[0.19499999999999998, 0.15568000000000004, 0....","[[0.1372, 0.44476000000000226, 0.0465200000000...","[312, 360, 48, 128, 116, 116, 516, 4, 4, 16, 1...","[40, 288, 356, 368, 236, 112, 72, 80, 128, 52,...","[116, 20, 28, 72, 48, 52, 56, 76, 28, 48, 108,...","[[832.04564, 844.72284, 869.196, 887.6118, 907...","[[0.089, 36.5878, 39.83392], [156.60152, 191.3...","[[40.41948, 63.60624, 82.81596, 99.1862, 108.9..."
4,caf81,0304_0_12,455.222708,F,wt,ACC,FS,0.20,4,"[[0.01776000000006661, 0.021239999999920656, 0...","[[0.05524000000000001, 0.014599999999999946, 0...","[[0.034959999999998104, 0.3509600000000006, 0....","[312, 360, 48, 128, 116, 116, 516, 4, 4, 16, 1...","[40, 288, 356, 368, 236, 112, 72, 80, 128, 52,...","[116, 20, 28, 72, 48, 52, 56, 76, 28, 48, 108,...","[[832.04432, 835.87184, 837.90524, 840.37388, ...","[[0.45276, 10.79292, 32.8426, 38.5304], [156.0...","[[40.02924, 68.41896, 71.75392, 77.10592, 79.8..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,caf81,0304_0_12,455.222708,F,wt,RSC,RSU,1.08,182,"[[1.5208800000000338, 0.16311999999993532, 0.0...","[[0.8556799999999996, 1.4667200000000005, 0.49...","[[1.3756799999999956, 0.19612000000000052, 0.8...","[312, 360, 48, 128, 116, 116, 516, 4, 4, 16, 1...","[40, 288, 356, 368, 236, 112, 72, 80, 128, 52,...","[116, 20, 28, 72, 48, 52, 56, 76, 28, 48, 108,...","[[832.1046, 862.48712, 899.53364, 959.59804, 1...","[[7.1828, 39.41708], [156.26088, 206.82164, 30...","[[42.34304, 155.27084], [447.31348, 457.94648]..."
183,caf81,0304_0_12,455.222708,F,wt,RSC,RSU,0.96,183,"[[0.10835999999994783, 0.10419999999999163, 0....","[[2.38552, 4.03704, 5.02036, 3.87096, 0.813919...","[[0.8956799999999987, 0.3820400000000035, 0.30...","[312, 360, 48, 128, 116, 116, 516, 4, 4, 16, 1...","[40, 288, 356, 368, 236, 112, 72, 80, 128, 52,...","[116, 20, 28, 72, 48, 52, 56, 76, 28, 48, 108,...","[[832.6642, 861.84976, 893.66172, 945.9044, 99...","[[3.05088, 39.40264], [156.97416, 218.68096, 3...","[[43.53308, 155.48988], [444.29368, 458.9934],..."
184,caf81,0304_0_12,455.222708,F,wt,RSC,RSU,0.68,184,"[[0.17599999999993088, 0.0029600000000300497, ...","[[0.5299999999999999, 0.04844000000000004, 0.0...","[[0.75488, 0.0033600000000006958, 0.0071999999...","[312, 360, 48, 128, 116, 116, 516, 4, 4, 16, 1...","[40, 288, 356, 368, 236, 112, 72, 80, 128, 52,...","[116, 20, 28, 72, 48, 52, 56, 76, 28, 48, 108,...","[[832.38508, 869.36576, 897.58496, 932.11868, ...","[[4e-05, 12.82944, 26.28428, 39.98608], [156.8...","[[40.08968, 58.14576, 77.86184, 89.9986, 103.9..."
185,caf81,0304_0_12,455.222708,F,wt,RSC,RSU,1.24,185,"[[0.19227999999998246, 0.0908799999999701, 0.1...","[[0.06699999999999995, 0.01324000000000003, 0....","[[0.29095999999999833, 0.5536400000000015, 0.8...","[312, 360, 48, 128, 116, 116, 516, 4, 4, 16, 1...","[40, 288, 356, 368, 236, 112, 72, 80, 128, 52,...","[116, 20, 28, 72, 48, 52, 56, 76, 28, 48, 108,...","[[832.17628, 893.93984, 940.271, 998.82444, 10...","[[0.52788, 39.03076], [159.53724, 219.48244, 2...","[[40.04592, 92.87112, 139.09828, 153.24148], [..."
186,caf81,0304_0_12,455.222708,F,wt,RSC,RSU,0.72,186,"[[0.03335999999990236, 0.3391599999999926, 0.4...","[[0.050000000000000044, 0.47444, 0.36539999999...","[[0.011319999999997776, 0.2794799999999995, 0....","[312, 360, 48, 128, 116, 116, 516, 4, 4, 16, 1...","[40, 288, 356, 368, 236, 112, 72, 80, 128, 52,...","[116, 20, 28, 72, 48, 52, 56, 76, 28, 48, 108,...","[[832.315, 897.7488, 966.87032, 1027.65424, 10...","[[1.19476, 39.74828], [156.30812, 216.82788, 2...","[[40.28508, 94.98808, 140.94332, 155.55464], [..."

got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,caf81,0304_12_24,455.72272,F,wt,ACC,FS,0.32,0,"[[0.35803999999999997, 0.01195999999999997, 0....","[[0.32167999999990116, 0.02876000000003387, 0....","[[0.3128400000000511, 0.3267999999999347, 0.06...","[16, 36, 112, 56, 120, 120, 268, 112, 136, 68,...","[140, 132, 984, 468, 204, 240, 120, 316, 336, ...","[52, 48, 52, 56, 68, 32, 32, 4, 76, 36, 156, 2...","[[0.447, 15.48852], [40.44456, 74.97184, 75.78...","[[672.64164, 708.4934, 739.546, 766.7736, 792....","[[812.16116, 836.45664, 863.56332], [3924.0237..."
1,caf81,0304_12_24,455.72272,F,wt,ACC,FS,0.32,1,"[[0.07135999999999998, 0.24612, 0.105319999999...","[[0.2437600000000657, 0.08907999999996719, 0.2...","[[0.020599999999944885, 0.8419600000000855, 0....","[16, 36, 112, 56, 120, 120, 268, 112, 136, 68,...","[140, 132, 984, 468, 204, 240, 120, 316, 336, ...","[52, 48, 52, 56, 68, 32, 32, 4, 76, 36, 156, 2...","[[0.57116, 15.7912], [40.71076, 75.9294], [152...","[[672.2334, 714.48544, 745.88124, 779.81764, 8...","[[812.03052, 851.22824, 862.95532], [3924.4508..."
2,caf81,0304_12_24,455.72272,F,wt,ACC,FS,0.32,2,"[[0.01971999999999996, 0.3829600000000002, 0.1...","[[0.00851999999997588, 1.369640000000004, 0.08...","[[0.37603999999998905, 0.01535999999998694, 0....","[16, 36, 112, 56, 120, 120, 268, 112, 136, 68,...","[140, 132, 984, 468, 204, 240, 120, 316, 336, ...","[52, 48, 52, 56, 68, 32, 32, 4, 76, 36, 156, 2...","[[1.86992, 15.91416], [40.57664, 74.50764, 75....","[[672.05948, 705.943, 736.01268, 760.0948, 795...","[[812.16152, 836.14496, 863.61088], [3924.0303..."
3,caf81,0304_12_24,455.72272,F,wt,ACC,FS,0.16,3,"[[0.040759999999999685], [0.0796800000000033, ...","[[0.05263999999999669, 0.054720000000088476, 0...","[[0.029960000000073705, 0.01343999999994594, 0...","[16, 36, 112, 56, 120, 120, 268, 112, 136, 68,...","[140, 132, 984, 468, 204, 240, 120, 316, 336, ...","[52, 48, 52, 56, 68, 32, 32, 4, 76, 36, 156, 2...","[[6.26072, 6.30148], [60.07308, 74.96384], [15...","[[679.28608, 770.84044, 811.72056], [866.69672...","[[815.02572, 863.65496], [3924.97172, 3967.274..."
4,caf81,0304_12_24,455.72272,F,wt,ACC,FS,0.32,4,"[[0.006, 0.11236, 0.10308, 0.01519999999999999...","[[0.2519999999999527, 0.05364000000008673, 0.0...","[[0.04488000000003467, 0.08435999999994692, 0....","[16, 36, 112, 56, 120, 120, 268, 112, 136, 68,...","[140, 132, 984, 468, 204, 240, 120, 316, 336, ...","[52, 48, 52, 56, 68, 32, 32, 4, 76, 36, 156, 2...","[[4e-05, 6.33688, 13.41992, 15.84728], [40.009...","[[672.01256, 682.77416, 694.81548, 705.63204, ...","[[812.0262, 818.01108, 823.88232, 829.3154, 83..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233,caf81,0304_12_24,455.72272,F,wt,RSC,RSU,0.68,233,"[[0.42328, 0.4474000000000001, 0.0781999999999...","[[0.27480000000002747, 0.4941599999999653, 0.0...","[[0.041999999999916326, 0.1811999999999898, 0....","[16, 36, 112, 56, 120, 120, 268, 112, 136, 68,...","[140, 132, 984, 468, 204, 240, 120, 316, 336, ...","[52, 48, 52, 56, 68, 32, 32, 4, 76, 36, 156, 2...","[[4e-05, 15.69064], [40.11448, 51.39788, 64.52...","[[672.08136, 689.98512, 701.04524, 720.6004, 7...","[[812.20572, 826.29952, 847.91652, 863.20708, ..."
234,caf81,0304_12_24,455.72272,F,wt,RSC,RSU,0.88,234,"[[0.34287999999999985, 0.11288000000000009, 0....","[[0.5190000000000055, 1.609640000000013, 1.427...","[[0.4556799999999157, 3.552120000000059, 1.372...","[16, 36, 112, 56, 120, 120, 268, 112, 136, 68,...","[140, 132, 984, 468, 204, 240, 120, 316, 336, ...","[52, 48, 52, 56, 68, 32, 32, 4, 76, 36, 156, 2...","[[1.08108, 15.8428], [41.00332, 74.3416], [152...","[[673.27, 782.4082, 809.71912], [864.47004, 94...","[[812.79244, 862.31016], [3924.128, 3970.61584..."
235,caf81,0304_12_24,455.72272,F,wt,RSC,RSU,0.56,235,"[[0.061160000000000006, 0.23636000000000001, 0...","[[0.07531999999991967, 0.08496000000002368, 0....","[[0.644239999999968, 0.27336000000002514, 0.21...","[16, 36, 112, 56, 120, 120, 268, 112, 136, 68,...","[140, 132, 984, 468, 204, 240, 120, 316, 336, ...","[52, 48, 52, 56, 68, 32, 32, 4, 76, 36, 156, 2...","[[0.02632, 15.57544], [40.901, 62.8048, 75.965...","[[672.09616, 703.81268, 734.6154, 765.78644, 7...","[[812.20948, 838.00176, 863.8718], [3924.03144..."
236,caf81,0304_12_24,455.72272,F,wt,RSC,RSU,0.64,236,"[[0.49556, 0.06435999999999997, 0.487719999999...","[[0.04796000000010281, 0.016639999999938482, 0...","[[1.7442399999999907, 1.4621599999999262, 0.73...","[16, 36, 112, 56, 120, 120, 268, 112, 136, 68,...","[140, 132, 984, 468, 204, 240, 120, 316, 336, ...","[52, 48, 52, 56, 68, 32, 32, 4, 76, 36, 156, 2...","[[0.74272, 15.03744], [40.13452, 74.81316], [1...","[[672.88916, 717.17508, 763.73436, 802.4902, 8...","[[812.60796, 853.53352, 863.80208], [3924.1282..."
237,caf81,0304_12_24,455.72272,F,wt,RSC,RSU,0.68,237,"[[], [0.5721200000000053, 2.576439999999998, 2...","[[6.2487599999999475, 5.401200000000017, 3.330...","[[0.15744000000006508, 0.029519999999934043, 3...","[16, 36, 112, 56, 120, 120, 268, 112, 136, 68,...","[140, 132, 984, 468, 204, 240, 120, 316, 336, ...","[52, 48, 52, 56, 68, 32, 32, 4, 76, 36, 156, 2...","[[4.82216], [40.40808, 73.52192], [153.7526, 2...","[[672.74756, 808.89764], [867.222, 995.31028],...","[[815.04396, 862.84152], [3928.77852, 3967.536..."

Working on caf82
Has 2 files to go through
got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,caf82,0304_0_12,455.222222,M,wt,CA1,RSU,0.48,0,"[[0.03760000000011132, 0.03168000000005122, 0....","[[0.01096, 0.07524, 0.005720000000000003, 0.03...","[[0.0032800000000179352, 0.03128000000000952, ...","[40, 52, 20, 36, 36, 28, 492, 104, 52, 44, 20,...","[252, 672, 864, 528, 760, 276, 856, 84, 304, 3...","[80, 56, 128, 60, 64, 28, 16, 40, 20, 64, 56, ...","[[3524.038, 3525.80924, 3527.76136, 3529.5994,...","[[4e-05, 2.56612, 5.01764, 7.29336, 10.33444, ...","[[252.0638, 253.30816, 254.6784, 255.92744, 25..."
1,caf82,0304_0_12,455.222222,M,wt,CA1,RSU,1.08,1,"[[0.015040000000226428, 0.0032400000000052387,...","[[0.01372000000000001, 0.023919999999999997, 0...","[[0.05795999999998003, 0.017960000000016407, 0...","[40, 52, 20, 36, 36, 28, 492, 104, 52, 44, 20,...","[252, 672, 864, 528, 760, 276, 856, 84, 304, 3...","[80, 56, 128, 60, 64, 28, 16, 40, 20, 64, 56, ...","[[3524.02668, 3527.24056, 3530.15088, 3533.926...","[[0.10776, 6.24768, 12.45904, 18.46532, 23.795...","[[252.00756, 256.07348, 259.15864, 263.57312, ..."
2,caf82,0304_0_12,455.222222,M,wt,CA1,RSU,0.92,2,"[[0.0039999999999054126, 0.09048000000029788, ...","[[0.010439999999999977, 0.0022400000000000198,...","[[0.019679999999993925, 0.06476000000000681, 0...","[40, 52, 20, 36, 36, 28, 492, 104, 52, 44, 20,...","[252, 672, 864, 528, 760, 276, 856, 84, 304, 3...","[80, 56, 128, 60, 64, 28, 16, 40, 20, 64, 56, ...","[[3524.00972, 3530.87308, 3537.68384, 3544.283...","[[0.15132, 15.05276, 26.91112, 38.9008, 54.290...","[[252.09868, 257.20476, 265.67392, 271.82108, ..."
3,caf82,0304_0_12,455.222222,M,wt,CA1,RSU,0.44,3,"[[0.026040000000193686, 0.32184000000006563, 0...","[[0.40012, 1.40536, 0.5062399999999998, 0.5457...","[[0.28328000000001907, 0.5963999999999885, 0.0...","[40, 52, 20, 36, 36, 28, 492, 104, 52, 44, 20,...","[252, 672, 864, 528, 760, 276, 856, 84, 304, 3...","[80, 56, 128, 60, 64, 28, 16, 40, 20, 64, 56, ...","[[3524.0696, 3542.56472, 3556.203, 3563.85872]...","[[0.01932, 100.64736, 205.28612, 251.8878], [3...","[[252.48716, 310.1344, 329.7356], [1004.41812,..."
4,caf82,0304_0_12,455.222222,M,wt,CA1,RSU,0.56,4,"[[0.03580000000010841, 0.04300000000012005, 0....","[[0.36228, 0.02799999999999997, 0.001800000000...","[[0.2679200000000037, 0.12271999999998684, 0.3...","[40, 52, 20, 36, 36, 28, 492, 104, 52, 44, 20,...","[252, 672, 864, 528, 760, 276, 856, 84, 304, 3...","[80, 56, 128, 60, 64, 28, 16, 40, 20, 64, 56, ...","[[3524.05984, 3530.9352, 3541.33608, 3550.9360...","[[0.01928, 9.4782, 34.40572, 42.35692, 50.2692...","[[252.37976, 273.6206, 300.9088, 325.34004, 33..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,caf82,0304_0_12,455.222222,M,wt,ACC,RSU,1.00,95,"[[0.010839999999916472, 1.3253600000002734, 0....","[[2.9774800000000003, 0.3829199999999999, 1.33...","[[0.010279999999994516, 0.004800000000017235, ...","[40, 52, 20, 36, 36, 28, 492, 104, 52, 44, 20,...","[252, 672, 864, 528, 760, 276, 856, 84, 304, 3...","[80, 56, 128, 60, 64, 28, 16, 40, 20, 64, 56, ...","[[3531.02108, 3562.9962], [3592.7524, 3643.526...","[[4e-05, 96.523, 174.40824, 250.97376], [339.0...","[[252.27068, 331.71224], [1006.40108, 1058.132..."
96,caf82,0304_0_12,455.222222,M,wt,ACC,RSU,0.96,96,"[[0.02500000000009095, 0.016319999999723223, 0...","[[0.39652, 0.038959999999999995, 0.46264, 0.07...","[[0.04912000000001626, 0.016279999999994743, 0...","[40, 52, 20, 36, 36, 28, 492, 104, 52, 44, 20,...","[252, 672, 864, 528, 760, 276, 856, 84, 304, 3...","[80, 56, 128, 60, 64, 28, 16, 40, 20, 64, 56, ...","[[3524.14548, 3543.51668, 3563.888], [3592.203...","[[0.064, 15.04224, 27.86628, 43.13244, 60.7393...","[[252.182, 262.91856, 272.958, 286.48932, 298...."
97,caf82,0304_0_12,455.222222,M,wt,ACC,RSU,0.68,97,"[[0.1028400000000147, 0.014639999999872089, 0....","[[0.014880000000000004, 0.31216, 0.01496000000...","[[0.12299999999999045, 0.01632000000000744, 0....","[40, 52, 20, 36, 36, 28, 492, 104, 52, 44, 20,...","[252, 672, 864, 528, 760, 276, 856, 84, 304, 3...","[80, 56, 128, 60, 64, 28, 16, 40, 20, 64, 56, ...","[[3524.02812, 3536.87632, 3554.29708, 3563.939...","[[0.06416, 14.61188, 26.34924, 34.98876, 52.39...","[[252.1082, 257.96256, 270.39488, 282.42508, 2..."
98,caf82,0304_0_12,455.222222,M,wt,ACC,RSU,1.64,98,"[[10.039080000000013, 16.208920000000035], [16...","[[76.8834, 69.59964000000001, 10.2725999999999...","[[7.046640000000025, 56.780280000000005], [10....","[40, 52, 20, 36, 36, 28, 492, 104, 52, 44, 20,...","[252, 672, 864, 528, 760, 276, 856, 84, 304, 3...","[80, 56, 128, 60, 64, 28, 16, 40, 20, 64, 56, ...","[[3534.8288, 3561.0768], [3595.22656, 3626.209...","[[6.88284, 238.16148], [352.35988, 958.131], [...","[[254.28488, 318.1118], [1015.86072, 1059.1561..."
99,caf82,0304_0_12,455.222222,M,wt,ACC,RSU,1.80,99,"[[7.58084000000008, 1.2207600000001548, 5.8239...","[[10.11672, 74.60064000000001, 3.7600799999999...","[[16.89996000000002], [4.587799999999902, 0.14...","[40, 52, 20, 36, 36, 28, 492, 104, 52, 44, 20,...","[252, 672, 864, 528, 760, 276, 856, 84, 304, 3...","[80, 56, 128, 60, 64, 28, 16, 40, 20, 64, 56, ...","[[3527.517, 3562.11948], [3616.724, 3642.1054]...","[[80.43184, 188.54776], [334.73984, 985.57416]...","[[287.86868, 304.76864], [1006.00336, 1050.951..."

got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,caf82,0304_12_24,455.722234,M,wt,CA1,RSU,0.52,0,"[[0.040840000000002874, 0.06359999999995125, 0...","[[0.05367999999999995, 0.1014400000000002, 0.2...","[[0.1184, 0.04052, 0.26724, 0.0072400000000000...","[248, 28, 8, 20, 308, 44, 176, 68, 24, 164, 12...","[676, 108, 20, 320, 136, 328, 372, 592, 208, 4...","[12, 48, 12, 132, 32, 84, 24, 28, 176, 72, 36,...","[[844.20736, 853.76356, 864.2778, 875.91252, 8...","[[12.19676, 22.35932, 33.88884, 47.00288, 59.2...","[[0.03452, 11.08652, 11.97492], [688.02468, 69..."
1,caf82,0304_12_24,455.722234,M,wt,CA1,RSU,0.68,1,"[[0.006559999999922184, 0.05348000000003594, 0...","[[0.054400000000001114, 0.03387999999999991, 0...","[[0.04448, 0.035280000000000006, 0.22216000000...","[248, 28, 8, 20, 308, 44, 176, 68, 24, 164, 12...","[676, 108, 20, 320, 136, 328, 372, 592, 208, 4...","[12, 48, 12, 132, 32, 84, 24, 28, 176, 72, 36,...","[[844.04952, 850.15144, 856.11064, 863.23464, ...","[[12.13872, 19.04692, 25.54216, 31.23144, 37.3...","[[0.03624, 5.4912, 10.47472, 11.96732], [688.0..."
2,caf82,0304_12_24,455.722234,M,wt,CA1,RSU,0.68,2,"[[0.003760000000056607, 0.03887999999994918, 0...","[[0.006279999999998509, 0.17092000000000063, 0...","[[0.025639999999999996, 0.010319999999999996, ...","[248, 28, 8, 20, 308, 44, 176, 68, 24, 164, 12...","[676, 108, 20, 320, 136, 328, 372, 592, 208, 4...","[12, 48, 12, 132, 32, 84, 24, 28, 176, 72, 36,...","[[844.011, 849.27548, 854.59828, 859.41732, 86...","[[12.18204, 16.69484, 22.40316, 27.55968, 33.2...","[[0.14024, 4.98256, 9.41468, 11.91844], [688.0..."
3,caf82,0304_12_24,455.722234,M,wt,CA1,RSU,0.72,3,"[[0.21247999999991407, 0.040960000000040964, 0...","[[0.30776000000000003, 0.04219999999999935, 0....","[[0.0422, 0.055, 0.0266, 0.08048, 0.13548, 0.0...","[248, 28, 8, 20, 308, 44, 176, 68, 24, 164, 12...","[676, 108, 20, 320, 136, 328, 372, 592, 208, 4...","[12, 48, 12, 132, 32, 84, 24, 28, 176, 72, 36,...","[[844.01412, 852.31992, 859.68692, 867.85688, ...","[[12.19356, 21.22724, 30.5602, 38.36428, 46.98...","[[0.0002, 8.40788, 11.96776], [688.11608, 695...."
4,caf82,0304_12_24,455.722234,M,wt,CA1,FS,0.36,4,"[[0.348920000000021, 0.007319999999936044, 0.0...","[[0.03184000000000076, 0.021279999999999077, 0...","[[0.20528000000000002, 0.06572, 0.008559999999...","[248, 28, 8, 20, 308, 44, 176, 68, 24, 164, 12...","[676, 108, 20, 320, 136, 328, 372, 592, 208, 4...","[12, 48, 12, 132, 32, 84, 24, 28, 176, 72, 36,...","[[844.01764, 848.7732, 854.69264, 859.01652, 8...","[[12.19084, 15.52896, 20.42884, 25.00364, 29.2...","[[0.0972, 4.35112, 9.23936, 11.97896], [688.00..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105,caf82,0304_12_24,455.722234,M,wt,ACC,RSU,0.96,105,"[[5.666759999999954, 1.80007999999998, 6.71703...","[[0.4963999999999995, 0.42135999999999996, 0.6...","[[0.47448, 0.007839999999999958, 0.61144, 0.64...","[248, 28, 8, 20, 308, 44, 176, 68, 24, 164, 12...","[676, 108, 20, 320, 136, 328, 372, 592, 208, 4...","[12, 48, 12, 132, 32, 84, 24, 28, 176, 72, 36,...","[[844.04876, 941.11276, 1004.52276, 1071.31448...","[[12.6354, 40.81288, 79.19828, 134.59852, 166....","[[0.0616, 10.9484], [688.3478, 727.76492, 735...."
106,caf82,0304_12_24,455.722234,M,wt,ACC,RSU,0.96,106,"[[3.9048400000000356, 0.5942000000000007, 2.71...","[[0.013840000000000074, 0.05352000000000068, 0...","[[0.12880000000000003, 2.48372, 1.30248, 0.120...","[248, 28, 8, 20, 308, 44, 176, 68, 24, 164, 12...","[676, 108, 20, 320, 136, 328, 372, 592, 208, 4...","[12, 48, 12, 132, 32, 84, 24, 28, 176, 72, 36,...","[[844.29972, 948.37332, 1026.6408, 1090.64356]...","[[12.09696, 37.68656, 79.02988, 135.3734, 168....","[[0.0616, 11.44564], [688.4902, 725.4644, 735...."
107,caf82,0304_12_24,455.722234,M,wt,ACC,RSU,1.00,107,"[[2.4176800000000185, 1.979159999999979, 1.784...","[[0.1825600000000005, 0.33455999999999975, 0.0...","[[0.8868400000000001, 1.4480399999999998, 0.62...","[248, 28, 8, 20, 308, 44, 176, 68, 24, 164, 12...","[676, 108, 20, 320, 136, 328, 372, 592, 208, 4...","[12, 48, 12, 132, 32, 84, 24, 28, 176, 72, 36,...","[[844.04892, 931.7742, 998.18084, 1071.01044, ...","[[12.94364, 40.74836, 68.95392, 122.76148, 157...","[[0.01108, 10.4976], [688.50048, 726.88608, 73..."
108,caf82,0304_12_24,455.722234,M,wt,ACC,RSU,0.68,108,"[[20.127360000000067, 5.204239999999913, 9.428...","[[1.6662400000000002, 4.300839999999999, 0.015...","[[3.915, 0.05835999999999952, 0.08376000000000...","[248, 28, 8, 20, 308, 44, 176, 68, 24, 164, 12...","[676, 108, 20, 320, 136, 328, 372, 592, 208, 4...","[12, 48, 12, 132, 32, 84, 24, 28, 176, 72, 36,...","[[865.90644, 1078.54812], [1120.76492, 1139.34...","[[12.5228, 272.96392, 442.5658, 683.32484, 687...","[[0.06156, 11.76328], [696.56568, 734.7118], [..."
109,caf82,0304_12_24,455.722234,M,wt,ACC,RSU,0.64,109,"[[0.002119999999990796, 0.037840000000073815, ...","[[0.004519999999999413, 0.0064400000000013335,...","[[0.045399999999999996, 0.011639999999999998, ...","[248, 28, 8, 20, 308, 44, 176, 68, 24, 164, 12...","[676, 108, 20, 320, 136, 328, 372, 592, 208, 4...","[12, 48, 12, 132, 32, 84, 24, 28, 176, 72, 36,...","[[844.05116, 846.90448, 849.54808, 852.41752, ...","[[12.01136, 15.36372, 18.39376, 21.9854, 25.57...","[[0.01224, 3.08208, 5.39452, 7.84752, 10.88616..."

Working on zbr106
Has 6 files to go through
got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,zbr106,0221_0_12,98.622512,M,wt,V1,RSU,0.76,0,"[[0.11876, 0.02123999999999998, 0.083080000000...","[[0.7358799999999519, 0.4877200000000812, 0.05...","[[0.9954000000002452, 0.49868000000014945, 0.2...","[792, 304, 144, 5420, 3636, 8, 68, 104, 988, 1...","[196, 224, 616, 684, 1124, 544, 668, 500, 160,...","[20, 100, 80, 20, 44, 56, 440, 120, 84, 104, 1...","[[0.08976, 18.03968, 35.30632, 47.91956, 63.12...","[[792.56876, 841.92328, 908.02688, 980.30056, ...","[[2277.09752, 2295.93484], [3001.24996, 3077.0..."
1,zbr106,0221_0_12,98.622512,M,wt,V1,RSU,0.56,1,"[[0.014280000000000001, 1.0784799999999999, 0....","[[1.3526000000000522, 1.1402799999999615, 0.21...","[[0.05060000000003129, 2.2959599999999227, 0.4...","[792, 304, 144, 5420, 3636, 8, 68, 104, 988, 1...","[196, 224, 616, 684, 1124, 544, 668, 500, 160,...","[20, 100, 80, 20, 44, 56, 440, 120, 84, 104, 1...","[[0.09928, 30.2444, 61.79096, 96.6552, 121.348...","[[793.41824, 851.88208, 911.4118, 975.83248, 9...","[[2276.20736, 2295.86192], [3001.03476, 3044.6..."
2,zbr106,0221_0_12,98.622512,M,wt,V1,FS,0.20,2,"[[0.04604, 0.20424000000000003, 0.31396, 0.110...","[[1.1351999999999407, 0.8500000000000227, 0.01...","[[0.02768000000014581, 0.008479999999963184, 0...","[792, 304, 144, 5420, 3636, 8, 68, 104, 988, 1...","[196, 224, 616, 684, 1124, 544, 668, 500, 160,...","[20, 100, 80, 20, 44, 56, 440, 120, 84, 104, 1...","[[0.0236, 5.04116, 14.13396, 22.18204, 32.7755...","[[793.76556, 843.95932, 985.83252], [1295.6773...","[[2276.026, 2282.56512, 2288.57524, 2293.02628..."
3,zbr106,0221_0_12,98.622512,M,wt,V1,RSU,0.64,3,"[[0.06648, 0.026520000000000016, 0.19256, 0.00...","[[0.06971999999996115, 0.056040000000052714, 0...","[[0.0026800000000548607, 0.11367999999993117, ...","[792, 304, 144, 5420, 3636, 8, 68, 104, 988, 1...","[196, 224, 616, 684, 1124, 544, 668, 500, 160,...","[20, 100, 80, 20, 44, 56, 440, 120, 84, 104, 1...","[[0.09684, 7.85236, 14.55024, 19.7712, 30.0364...","[[792.09348, 803.322, 820.71932, 838.99316, 84...","[[2276.014, 2293.69868, 2295.91664], [3000.454..."
4,zbr106,0221_0_12,98.622512,M,wt,V1,FS,0.24,4,"[[0.08564000000000001, 0.01432, 0.002840000000...","[[0.15156000000001768, 0.3206000000000131, 0.0...","[[0.5027199999999539, 0.01731999999992695, 0.4...","[792, 304, 144, 5420, 3636, 8, 68, 104, 988, 1...","[196, 224, 616, 684, 1124, 544, 668, 500, 160,...","[20, 100, 80, 20, 44, 56, 440, 120, 84, 104, 1...","[[0.0778, 6.42788, 13.23212, 18.2098, 26.99832...","[[792.07912, 800.84816, 815.40788, 830.5386, 8...","[[2276.42036, 2290.60768, 2295.8764], [3000.04..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,zbr106,0221_0_12,98.622512,M,wt,RSPv,RSU,0.60,129,"[[0.16624, 0.05892, 0.30311999999999995, 0.001...","[[0.00864000000001397, 0.023199999999974352, 0...","[[0.06599999999980355, 0.31336000000010245, 0....","[792, 304, 144, 5420, 3636, 8, 68, 104, 988, 1...","[196, 224, 616, 684, 1124, 544, 668, 500, 160,...","[20, 100, 80, 20, 44, 56, 440, 120, 84, 104, 1...","[[0.00088, 7.87944, 15.411, 22.96724, 32.1114,...","[[792.06292, 798.76816, 806.49932, 814.71816, ...","[[2276.01128, 2287.20304, 2295.99432], [3000.3..."
130,zbr106,0221_0_12,98.622512,M,wt,RSPv,RSU,0.44,130,"[[0.16188, 0.08092000000000002, 0.080919999999...","[[0.08091999999999189, 0.08096000000000458, 0....","[[0.0809199999998782, 0.08096000000023196, 0.0...","[792, 304, 144, 5420, 3636, 8, 68, 104, 988, 1...","[196, 224, 616, 684, 1124, 544, 668, 500, 160,...","[20, 100, 80, 20, 44, 56, 440, 120, 84, 104, 1...","[[0.06572, 7.5922, 17.3038, 26.61068, 36.1604,...","[[792.05848, 801.04208, 810.51132, 819.414, 82...","[[2276.00248, 2284.74376, 2293.88972, 2295.994..."
131,zbr106,0221_0_12,98.622512,M,wt,RSPv,RSU,0.64,131,"[[0.009840000000000002, 0.0017199999999999993,...","[[0.5173600000000533, 0.07399999999995543, 0.4...","[[0.31043999999974403, 0.009919999999965512, 0...","[792, 304, 144, 5420, 3636, 8, 68, 104, 988, 1...","[196, 224, 616, 684, 1124, 544, 668, 500, 160,...","[20, 100, 80, 20, 44, 56, 440, 120, 84, 104, 1...","[[0.04248, 3.647, 10.28756, 14.09544, 16.33532...","[[792.11812, 812.55596, 826.02196, 842.9188, 8...","[[2276.14564, 2287.44584, 2295.99764], [3000.1..."
132,zbr106,0221_0_12,98.622512,M,wt,RSPv,RSU,0.48,132,"[[0.16184, 0.16188, 0.08091999999999999, 0.080...","[[0.16187999999999647, 0.08091999999999189, 0....","[[0.1618799999996554, 0.16188000000011016, 0.3...","[792, 304, 144, 5420, 3636, 8, 68, 104, 988, 1...","[196, 224, 616, 684, 1124, 544, 668, 500, 160,...","[20, 100, 80, 20, 44, 56, 440, 120, 84, 104, 1...","[[0.06572, 11.63868, 22.48324, 33.32784, 44.90...","[[792.1394, 802.8226, 813.82956, 824.18904, 83...","[[2276.00244, 2285.71496, 2295.58936, 2295.994..."
133,zbr106,0221_0_12,98.622512,M,wt,RSPv,FS,0.36,133,"[[0.031200000000000006, 0.12428, 0.06191999999...","[[0.12319999999999709, 0.0029600000000300497, ...","[[0.14919999999983702, 0.08015999999997803, 0....","[792, 304, 144, 5420, 3636, 8, 68, 104, 988, 1...","[196, 224, 616, 684, 1124, 544, 668, 500, 160,...","[20, 100, 80, 20, 44, 56, 440, 120, 84, 104, 1...","[[0.283, 11.90564, 25.13468, 41.36752, 53.7608...","[[792.101, 810.68012, 827.67212, 847.15796, 86...","[[2276.11564, 2292.61544, 2295.90292], [3000.3..."

got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,zbr106,0221_12_24,99.122523,M,wt,V1,RSU,0.76,0,"[[0.20548, 0.12448000000000004, 0.080199999999...","[[0.05975999999998294, 0.010880000000042855, 0...","[[0.6275200000000041, 0.3461600000000544, 0.21...","[1020, 1692, 1360, 1720, 980, 644, 828]","[556, 264, 608, 368, 560, 232, 1200, 548, 388,...","[104, 48, 116, 100, 64, 64, 12, 76, 148, 68, 1...","[[0.3114, 23.83736, 48.56048, 66.62164, 94.272...","[[1020.02748, 1063.92712, 1135.40272, 1186.776...","[[1577.70524, 1638.67308, 1678.88612], [1976.6..."
1,zbr106,0221_12_24,99.122523,M,wt,V1,FS,0.24,1,"[[0.28636000000000017, 0.17283999999999988, 0....","[[0.1413199999999506, 0.37804000000005544, 0.1...","[[1.3579999999999472, 1.746560000000045, 0.273...","[1020, 1692, 1360, 1720, 980, 644, 828]","[556, 264, 608, 368, 560, 232, 1200, 548, 388,...","[104, 48, 116, 100, 64, 64, 12, 76, 148, 68, 1...","[[2.65292, 28.5244, 51.75464, 89.56068, 125.93...","[[1020.14736, 1062.67072, 1121.68432, 1282.878...","[[1576.74272, 1599.44176, 1610.73076, 1618.487..."
2,zbr106,0221_12_24,99.122523,M,wt,V1,RSU,0.64,2,"[[0.44352, 0.7088399999999999, 0.37012, 0.1217...","[[0.09299999999996089, 0.031799999999975626, 0...","[[0.2921200000000681, 0.2135200000000168, 0.34...","[1020, 1692, 1360, 1720, 980, 644, 828]","[556, 264, 608, 368, 560, 232, 1200, 548, 388,...","[104, 48, 116, 100, 64, 64, 12, 76, 148, 68, 1...","[[0.09688, 27.49808, 37.51196, 52.5984, 68.400...","[[1020.01476, 1030.41576, 1047.63976, 1068.861...","[[1576.07592, 1600.54768, 1620.28976, 1636.673..."
3,zbr106,0221_12_24,99.122523,M,wt,V1,FS,0.28,3,"[[0.0038800000000000223, 0.19852, 0.13964, 0.2...","[[0.026520000000004984, 0.022199999999998, 0.0...","[[0.2236400000001595, 0.004719999999906577, 0....","[1020, 1692, 1360, 1720, 980, 644, 828]","[556, 264, 608, 368, 560, 232, 1200, 548, 388,...","[104, 48, 116, 100, 64, 64, 12, 76, 148, 68, 1...","[[0.15352, 13.199, 27.14676, 35.79324, 44.6858...","[[1020.0158, 1024.43816, 1030.40324, 1038.8275...","[[1576.08288, 1588.39704, 1601.40404, 1609.300..."
4,zbr106,0221_12_24,99.122523,M,wt,V1,FS,0.36,4,"[[0.6785599999999999, 0.21992000000000012, 0.7...","[[0.09180000000003474, 0.3451599999999644, 0.0...","[[2.382400000000189, 0.17051999999989675, 0.03...","[1020, 1692, 1360, 1720, 980, 644, 828]","[556, 264, 608, 368, 560, 232, 1200, 548, 388,...","[104, 48, 116, 100, 64, 64, 12, 76, 148, 68, 1...","[[0.11736, 45.96112, 82.44676, 107.63416, 133....","[[1020.20916, 1047.44388, 1092.69436, 1135.689...","[[1577.56632, 1616.41904, 1641.72412, 1677.229..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,zbr106,0221_12_24,99.122523,M,wt,RSPv,RSU,0.44,120,"[[0.08091999999999999, 0.08095999999999999, 0....","[[0.08091999999999189, 0.08091999999999189, 0....","[[0.0809199999998782, 0.08096000000000458, 0.0...","[1020, 1692, 1360, 1720, 980, 644, 828]","[556, 264, 608, 368, 560, 232, 1200, 548, 388,...","[104, 48, 116, 100, 64, 64, 12, 76, 148, 68, 1...","[[0.04212, 8.86436, 17.76756, 26.347, 35.33108...","[[1020.04448, 1028.46152, 1038.41628, 1047.076...","[[1576.07456, 1584.9778, 1593.63824, 1603.1890..."
121,zbr106,0221_12_24,99.122523,M,wt,RSPv,RSU,0.64,121,"[[1.4399199999999999, 0.9848400000000002, 1.06...","[[0.08724000000006527, 0.43423999999993157, 0....","[[0.12312000000019907, 0.03427999999985332, 0....","[1020, 1692, 1360, 1720, 980, 644, 828]","[556, 264, 608, 368, 560, 232, 1200, 548, 388,...","[104, 48, 116, 100, 64, 64, 12, 76, 148, 68, 1...","[[1.40468, 93.87972, 149.81876, 180.26392, 215...","[[1020.12352, 1059.7164, 1104.92812, 1138.5758...","[[1576.78444, 1602.31448, 1615.437, 1628.48672..."
122,zbr106,0221_12_24,99.122523,M,wt,RSPv,RSU,0.68,122,"[[24.67456, 0.020479999999999166, 4.7921599999...","[[0.039640000000076725, 0.1693599999999833, 0....","[[0.01499999999987267, 0.8552400000000944, 0.0...","[1020, 1692, 1360, 1720, 980, 644, 828]","[556, 264, 608, 368, 560, 232, 1200, 548, 388,...","[104, 48, 116, 100, 64, 64, 12, 76, 148, 68, 1...","[[1.47744, 197.00488, 253.79284, 258.63312, 34...","[[1020.54748, 1105.69504, 1156.56696, 1223.157...","[[1578.28716, 1678.52848], [1978.01016, 2020.9..."
123,zbr106,0221_12_24,99.122523,M,wt,RSPv,RSU,0.48,123,"[[0.08092, 0.08096, 0.08091999999999999, 0.080...","[[0.08091999999999189, 0.08091999999999189, 0....","[[0.08096000000000458, 0.08092000000010557, 0....","[1020, 1692, 1360, 1720, 980, 644, 828]","[556, 264, 608, 368, 560, 232, 1200, 548, 388,...","[104, 48, 116, 100, 64, 64, 12, 76, 148, 68, 1...","[[0.12304, 8.78344, 18.81972, 28.12756, 37.354...","[[1020.1254, 1029.43268, 1038.98276, 1047.7235...","[[1576.07452, 1585.70624, 1595.17608, 1604.969..."
124,zbr106,0221_12_24,99.122523,M,wt,RSPv,RSU,0.40,124,"[[0.06592000000000003, 0.56424, 0.212160000000...","[[0.19871999999998025, 0.3182799999999588, 0.0...","[[0.022519999999985885, 0.44632000000001426, 0...","[1020, 1692, 1360, 1720, 980, 644, 828]","[556, 264, 608, 368, 560, 232, 1200, 548, 388,...","[104, 48, 116, 100, 64, 64, 12, 76, 148, 68, 1...","[[0.29388, 19.50168, 37.71984, 50.8866, 68.343...","[[1020.12904, 1042.16596, 1065.40816, 1092.904...","[[1576.30976, 1597.97748, 1612.4644, 1624.3205..."

got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,zbr106,0222_0_12,99.622523,M,wt,V1,FS,0.24,0,"[[0.021560000000000003, 0.05612, 0.04999999999...","[[0.007959999999911815, 0.22248000000035972, 0...","[[0.10280000000011569, 0.21624000000019805, 0....","[596, 1728, 3412, 3708, 448, 172, 4312, 1804, ...","[604, 592, 636, 380, 296, 192, 756, 236, 808, ...","[112, 32, 84, 28, 24, 56, 40, 216, 8, 60, 140,...","[[0.0614, 8.85636, 24.98576, 36.31316, 49.0253...","[[2688.0838, 2806.57132, 2954.41328, 3113.0076...","[[3294.33204, 3310.5748, 3314.91588, 3325.6337..."
1,zbr106,0222_0_12,99.622523,M,wt,V1,RSU,0.64,1,"[[0.07436000000000001, 0.007279999999999981, 0...","[[0.06259999999974752, 0.001160000000254513, 0...","[[0.19668000000001484, 0.04815999999982523, 0....","[596, 1728, 3412, 3708, 448, 172, 4312, 1804, ...","[604, 592, 636, 380, 296, 192, 756, 236, 808, ...","[112, 32, 84, 28, 24, 56, 40, 216, 8, 60, 140,...","[[0.11468, 4.20184, 6.95772, 17.3862, 22.08724...","[[2688.25948, 2698.69652, 2707.6396, 2716.4509...","[[3292.04068, 3314.23608, 3330.19244, 3348.959..."
2,zbr106,0222_0_12,99.622523,M,wt,V1,FS,0.28,2,"[[0.09492, 0.02176, 0.015279999999999988, 0.02...","[[0.189719999999852, 0.009320000000116124, 0.0...","[[0.00367999999980384, 0.004039999999804422, 0...","[596, 1728, 3412, 3708, 448, 172, 4312, 1804, ...","[604, 592, 636, 380, 296, 192, 756, 236, 808, ...","[112, 32, 84, 28, 24, 56, 40, 216, 8, 60, 140,...","[[0.00824, 4.09192, 7.19368, 14.0894, 21.16968...","[[2688.06548, 2695.30064, 2703.14876, 2711.267...","[[3292.03288, 3304.9992, 3314.26144, 3320.4076..."
3,zbr106,0222_0_12,99.622523,M,wt,V1,RSU,0.64,3,"[[0.024120000000000003, 0.005839999999999998, ...","[[0.036040000000411965, 0.08819999999968786, 0...","[[0.021279999999933352, 0.10179999999991196, 0...","[596, 1728, 3412, 3708, 448, 172, 4312, 1804, ...","[604, 592, 636, 380, 296, 192, 756, 236, 808, ...","[112, 32, 84, 28, 24, 56, 40, 216, 8, 60, 140,...","[[0.08216, 3.94392, 6.55036, 10.73512, 16.5632...","[[2688.0534, 2695.2856, 2706.431, 2716.0188, 2...","[[3292.00428, 3307.0004, 3312.69244, 3323.8756..."
4,zbr106,0222_0_12,99.622523,M,wt,V1,RSU,0.56,4,"[[0.052760000000000015, 0.02739999999999998, 0...","[[0.1375199999997676, 0.05308000000013635, 0.3...","[[0.02232000000003609, 0.0967200000000048, 0.0...","[596, 1728, 3412, 3708, 448, 172, 4312, 1804, ...","[604, 592, 636, 380, 296, 192, 756, 236, 808, ...","[112, 32, 84, 28, 24, 56, 40, 216, 8, 60, 140,...","[[0.11796, 6.28288, 20.20976, 28.62108, 36.701...","[[2688.14168, 2702.08592, 2715.0956, 2728.3692...","[[3292.01832, 3311.79288, 3331.82864, 3355.290..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,zbr106,0222_0_12,99.622523,M,wt,RSPv,FS,0.28,114,"[[0.012879999999999999, 0.033519999999999994, ...","[[0.03168000000005122, 0.016840000000229338, 0...","[[0.012160000000221771, 0.012439999999969586, ...","[596, 1728, 3412, 3708, 448, 172, 4312, 1804, ...","[604, 592, 636, 380, 296, 192, 756, 236, 808, ...","[112, 32, 84, 28, 24, 56, 40, 216, 8, 60, 140,...","[[0.00168, 1.3396, 2.28324, 4.51944, 6.10724, ...","[[2688.2648, 2691.4206, 2693.72192, 2699.89172...","[[3292.0298, 3296.73488, 3302.52616, 3306.1462..."
115,zbr106,0222_0_12,99.622523,M,wt,RSPv,RSU,0.40,115,"[[0.09816, 0.0029599999999999904, 0.0443999999...","[[0.0195200000002842, 0.001959999999598949, 0....","[[0.03427999999985332, 0.0027199999999538704, ...","[596, 1728, 3412, 3708, 448, 172, 4312, 1804, ...","[604, 592, 636, 380, 296, 192, 756, 236, 808, ...","[112, 32, 84, 28, 24, 56, 40, 216, 8, 60, 140,...","[[0.04896, 4.1108, 7.64424, 15.93336, 22.4768,...","[[2688.08036, 2692.83992, 2700.93336, 2707.748...","[[3292.12188, 3304.74056, 3312.46048, 3319.602..."
116,zbr106,0222_0_12,99.622523,M,wt,RSPv,RSU,0.68,116,"[[0.051519999999999996, 0.06620000000000001, 0...","[[0.007160000000112632, 0.033959999999751744, ...","[[0.005079999999907159, 0.022079999999732536, ...","[596, 1728, 3412, 3708, 448, 172, 4312, 1804, ...","[604, 592, 636, 380, 296, 192, 756, 236, 808, ...","[112, 32, 84, 28, 24, 56, 40, 216, 8, 60, 140,...","[[0.00044, 5.42092, 14.91552, 26.63356, 33.557...","[[2688.26136, 2703.7654, 2717.2978, 2732.44144...","[[3292.00048, 3308.673, 3322.59848, 3335.74176..."
117,zbr106,0222_0_12,99.622523,M,wt,RSPv,RSU,0.40,117,"[[0.04292, 0.008120000000000016, 0.04135999999...","[[0.6607199999998556, 0.4634399999999914, 0.03...","[[0.13679999999976644, 0.4106800000004114, 0.0...","[596, 1728, 3412, 3708, 448, 172, 4312, 1804, ...","[604, 592, 636, 380, 296, 192, 756, 236, 808, ...","[112, 32, 84, 28, 24, 56, 40, 216, 8, 60, 140,...","[[0.10428, 5.30476, 15.5336, 26.63736, 37.3460...","[[2688.74632, 2703.7152, 2722.65796, 2742.6939...","[[3292.15308, 3312.60448, 3326.31012, 3346.582..."
118,zbr106,0222_0_12,99.622523,M,wt,RSPv,RSU,0.52,118,"[[0.08144000000000001, 0.06256, 0.013240000000...","[[0.05511999999998807, 0.028440000000045984, 0...","[[0.03264000000035594, 0.012999999999919964, 0...","[596, 1728, 3412, 3708, 448, 172, 4312, 1804, ...","[604, 592, 636, 380, 296, 192, 756, 236, 808, ...","[112, 32, 84, 28, 24, 56, 40, 216, 8, 60, 140,...","[[0.0424, 5.09408, 8.09496, 11.93268, 15.30488...","[[2688.33668, 2696.21696, 2704.09352, 2714.509...","[[3292.2454, 3300.10108, 3306.61508, 3309.6206..."

got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,zbr106,0222_12_24,100.122535,M,wt,V1,RSU,0.48,0,"[[0.07003999999999999, 0.09543999999999997, 0....","[[0.02628000000004249, 0.0021600000000034925, ...","[[0.06916000000001077, 0.2604799999999159, 0.0...","[596, 1728, 3412, 3708, 448, 172, 4312, 1804, ...","[604, 592, 636, 380, 296, 192, 756, 236, 808, ...","[112, 32, 84, 28, 24, 56, 40, 216, 8, 60, 140,...","[[0.26672, 8.71628, 14.91456, 21.99, 25.79796,...","[[2688.08264, 2691.25932, 2693.86388, 2696.012...","[[3292.06768, 3301.78336, 3309.48916, 3319.336..."
1,zbr106,0222_12_24,100.122535,M,wt,V1,FS,0.24,1,"[[0.008480000000000043, 0.006479999999999986, ...","[[0.06739999999990687, 0.2781599999998434, 0.1...","[[0.007119999999758875, 0.04580000000032669, 0...","[596, 1728, 3412, 3708, 448, 172, 4312, 1804, ...","[604, 592, 636, 380, 296, 192, 756, 236, 808, ...","[112, 32, 84, 28, 24, 56, 40, 216, 8, 60, 140,...","[[0.42116, 13.86412, 22.64568, 28.31656, 32.70...","[[2688.02336, 2692.2048, 2695.89296, 2701.6955...","[[3292.01188, 3299.75272, 3309.18304, 3318.508..."
2,zbr106,0222_12_24,100.122535,M,wt,V1,FS,0.36,2,"[[0.1396, 0.55244, 0.20843999999999996, 0.1120...","[[0.015640000000075815, 0.20579999999972642, 0...","[[0.005120000000260916, 0.01731999999992695, 0...","[596, 1728, 3412, 3708, 448, 172, 4312, 1804, ...","[604, 592, 636, 380, 296, 192, 756, 236, 808, ...","[112, 32, 84, 28, 24, 56, 40, 216, 8, 60, 140,...","[[0.0136, 20.6498, 28.48412, 38.09388, 48.8116...","[[2688.11796, 2692.3064, 2696.38928, 2703.0129...","[[3292.12544, 3301.7042, 3312.46916, 3322.0194..."
3,zbr106,0222_12_24,100.122535,M,wt,V1,RSU,0.60,3,"[[0.031200000000000006, 0.005319999999999991, ...","[[0.37548000000015236, 0.0929599999999482, 0.1...","[[0.30115999999998166, 0.016920000000027358, 0...","[596, 1728, 3412, 3708, 448, 172, 4312, 1804, ...","[604, 592, 636, 380, 296, 192, 756, 236, 808, ...","[112, 32, 84, 28, 24, 56, 40, 216, 8, 60, 140,...","[[0.4078, 12.59108, 24.5654, 35.40948, 44.6776...","[[2688.31304, 2693.80084, 2700.98156, 2704.735...","[[3292.12148, 3302.80352, 3312.22372, 3324.279..."
4,zbr106,0222_12_24,100.122535,M,wt,V1,RSU,0.68,4,"[[0.013440000000000007, 0.09988000000000002, 0...","[[0.03692000000000917, 0.03540000000020882, 0....","[[0.025319999999737774, 0.05984000000034939, 0...","[596, 1728, 3412, 3708, 448, 172, 4312, 1804, ...","[604, 592, 636, 380, 296, 192, 756, 236, 808, ...","[112, 32, 84, 28, 24, 56, 40, 216, 8, 60, 140,...","[[0.27612, 20.55024, 31.34496, 44.33872, 57.66...","[[2688.051, 2697.19332, 2707.84712, 2725.63784...","[[3292.4454, 3313.57468, 3332.30824, 3349.3121..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,zbr106,0222_12_24,100.122535,M,wt,RSPv,RSU,0.76,121,"[[0.007959999999999995, 0.43108, 0.01492000000...","[[0.7990800000002309, 0.056599999999889405, 0....","[[0.5408400000001166, 0.026519999999891297, 0....","[596, 1728, 3412, 3708, 448, 172, 4312, 1804, ...","[604, 592, 636, 380, 296, 192, 756, 236, 808, ...","[112, 32, 84, 28, 24, 56, 40, 216, 8, 60, 140,...","[[0.12888, 11.32624, 23.24832, 35.21696, 49.32...","[[2688.21004, 2711.71428, 2759.1894, 2792.8850...","[[3292.02196, 3317.94384, 3345.20252, 3360.361..."
122,zbr106,0222_12_24,100.122535,M,wt,RSPv,FS,0.28,122,"[[0.02636, 0.005319999999999998, 0.11148000000...","[[0.14996000000019194, 0.13071999999965556, 0....","[[0.010160000000269065, 0.013719999999921129, ...","[596, 1728, 3412, 3708, 448, 172, 4312, 1804, ...","[604, 592, 636, 380, 296, 192, 756, 236, 808, ...","[112, 32, 84, 28, 24, 56, 40, 216, 8, 60, 140,...","[[0.00952, 4.81312, 13.72472, 17.5952, 21.2864...","[[2688.26712, 2692.74536, 2706.5302, 2716.6539...","[[3292.01772, 3295.52528, 3298.8098, 3301.8079..."
123,zbr106,0222_12_24,100.122535,M,wt,RSPv,RSU,0.64,123,"[[0.10715999999999999, 0.35864, 0.145239999999...","[[0.04128000000036991, 0.06239999999979773, 0....","[[0.023920000000089203, 0.06264000000010128, 0...","[596, 1728, 3412, 3708, 448, 172, 4312, 1804, ...","[604, 592, 636, 380, 296, 192, 756, 236, 808, ...","[112, 32, 84, 28, 24, 56, 40, 216, 8, 60, 140,...","[[0.02804, 15.32996, 24.53724, 32.07484, 39.29...","[[2688.38948, 2694.97752, 2705.96144, 2715.761...","[[3292.00564, 3301.39184, 3311.24636, 3321.173..."
124,zbr106,0222_12_24,100.122535,M,wt,RSPv,FS,0.12,124,"[[0.053959999999999994, 0.020199999999999996, ...","[[0.20424000000002707, 0.01739999999972497, 0....","[[0.02264000000013766, 0.19419999999990978, 0....","[596, 1728, 3412, 3708, 448, 172, 4312, 1804, ...","[604, 592, 636, 380, 296, 192, 756, 236, 808, ...","[112, 32, 84, 28, 24, 56, 40, 216, 8, 60, 140,...","[[0.07536, 8.56928, 17.81216, 22.41628, 26.507...","[[2688.06536, 2693.62772, 2701.60392, 2707.356...","[[3292.12556, 3311.1714, 3329.32008, 3348.8746..."
125,zbr106,0222_12_24,100.122535,M,wt,RSPv,RSU,0.64,125,"[[0.011600000000000055, 0.7155999999999999, 0....","[[0.0688399999999092, 0.4412000000002081, 0.16...","[[0.23008000000027096, 0.6846000000000458, 0.0...","[596, 1728, 3412, 3708, 448, 172, 4312, 1804, ...","[604, 592, 636, 380, 296, 192, 756, 236, 808, ...","[112, 32, 84, 28, 24, 56, 40, 216, 8, 60, 140,...","[[0.961, 26.51664, 38.53352, 63.05904, 89.5400...","[[2688.0144, 2706.85328, 2730.611, 2746.3008, ...","[[3292.40784, 3309.62048, 3330.40176, 3348.157..."

got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,zbr106,0223_0_12,100.622535,M,wt,V1,FS,0.28,0,"[[0.0498800000000017, 0.14859999999998763, 0.3...","[[0.05756, 0.52624, 0.08123999999999998, 0.737...","[[0.5546000000003914, 0.7602399999996123, 0.23...","[3456, 4668, 204, 516, 4592, 3544, 328, 1256, ...","[144, 736, 748, 1244, 344, 228, 1112, 236, 596...","[80, 108, 92, 160, 60, 36, 104, 56, 36, 208, 4...","[[144.67524, 170.39712, 189.85136, 220.17332, ...","[[0.1194, 21.53244, 42.89692, 69.04064, 92.526...","[[4336.88488, 4380.09452, 4410.22576, 4415.849..."
1,zbr106,0223_0_12,100.622535,M,wt,V1,FS,0.32,1,"[[0.09656000000001086, 0.004919999999998481, 0...","[[0.02396000000000001, 0.015639999999999987, 0...","[[0.052639999999883, 0.00488000000041211, 0.02...","[3456, 4668, 204, 516, 4592, 3544, 328, 1256, ...","[144, 736, 748, 1244, 344, 228, 1112, 236, 596...","[80, 108, 92, 160, 60, 36, 104, 56, 36, 208, 4...","[[144.04772, 148.18512, 155.00284, 158.74268, ...","[[0.11928, 5.21376, 10.46992, 16.10732, 20.790...","[[4336.03424, 4343.52576, 4351.6204, 4358.0650..."
2,zbr106,0223_0_12,100.622535,M,wt,V1,RSU,0.56,2,"[[0.00380000000001246, 0.03211999999999193, 0....","[[0.04723999999999999, 0.010520000000000002, 0...","[[0.21907999999984895, 0.08880000000044674, 0....","[3456, 4668, 204, 516, 4592, 3544, 328, 1256, ...","[144, 736, 748, 1244, 344, 228, 1112, 236, 596...","[80, 108, 92, 160, 60, 36, 104, 56, 36, 208, 4...","[[144.40184, 156.2984, 163.34712, 171.78516, 1...","[[0.11996, 13.17804, 23.12124, 34.57356, 49.82...","[[4336.03392, 4350.94572, 4360.68364, 4373.233..."
3,zbr106,0223_0_12,100.622535,M,wt,V1,RSU,0.72,3,"[[0.25407999999998765, 0.05916000000001986, 0....","[[2.4844, 0.4790800000000002, 0.28200000000000...","[[0.7676000000001295, 0.7177199999996446, 0.07...","[3456, 4668, 204, 516, 4592, 3544, 328, 1256, ...","[144, 736, 748, 1244, 344, 228, 1112, 236, 596...","[80, 108, 92, 160, 60, 36, 104, 56, 36, 208, 4...","[[145.10316, 168.62872, 200.3602, 234.08064, 2...","[[0.14484, 49.57924, 89.97072, 138.97244], [36...","[[4336.66756, 4410.0904], [5204.68556, 5306.02..."
4,zbr106,0223_0_12,100.622535,M,wt,V1,RSU,0.64,4,"[[0.08104000000000156, 0.251199999999983, 0.39...","[[0.48719999999999997, 0.11764000000000008, 0....","[[0.17068000000017491, 0.02912000000014814, 0....","[3456, 4668, 204, 516, 4592, 3544, 328, 1256, ...","[144, 736, 748, 1244, 344, 228, 1112, 236, 596...","[80, 108, 92, 160, 60, 36, 104, 56, 36, 208, 4...","[[144.12296, 154.24656, 163.07124, 171.30068, ...","[[0.14664, 11.69804, 24.80632, 37.25908, 47.80...","[[4336.6682, 4352.4226, 4360.48916, 4370.8406,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,zbr106,0223_0_12,100.622535,M,wt,RSPv,FS,0.28,124,"[[0.014240000000000919, 0.3658400000000199, 0....","[[0.003720000000000001, 0.003040000000000001, ...","[[0.006080000000110886, 0.007639999999810243, ...","[3456, 4668, 204, 516, 4592, 3544, 328, 1256, ...","[144, 736, 748, 1244, 344, 228, 1112, 236, 596...","[80, 108, 92, 160, 60, 36, 104, 56, 36, 208, 4...","[[144.01152, 147.00544, 153.20476, 156.24776, ...","[[0.11916, 4.9554, 8.39608, 13.34844, 16.57752...","[[4336.0196, 4340.622, 4344.93572, 4350.12904,..."
125,zbr106,0223_0_12,100.622535,M,wt,RSPv,RSU,0.64,125,"[[0.2852399999999875, 0.039320000000003574, 0....","[[0.01655999999999999, 0.18444000000000002, 0....","[[0.05335999999988417, 0.0192799999995259, 0.0...","[3456, 4668, 204, 516, 4592, 3544, 328, 1256, ...","[144, 736, 748, 1244, 344, 228, 1112, 236, 596...","[80, 108, 92, 160, 60, 36, 104, 56, 36, 208, 4...","[[144.10264, 155.97152, 165.31884, 175.81436, ...","[[0.138, 11.13684, 22.50928, 31.11476, 43.0467...","[[4337.07268, 4354.66872, 4364.01264, 4376.245..."
126,zbr106,0223_0_12,100.622535,M,wt,RSPv,RSU,0.44,126,"[[0.16187999999999647, 0.08091999999999189, 0....","[[0.08091999999999999, 0.16188000000000002, 0....","[[0.1618799999996554, 0.08092000000033295, 0.0...","[3456, 4668, 204, 516, 4592, 3544, 328, 1256, ...","[144, 736, 748, 1244, 344, 228, 1112, 236, 596...","[80, 108, 92, 160, 60, 36, 104, 56, 36, 208, 4...","[[144.0122, 152.91504, 162.62724, 171.77292, 1...","[[0.0302, 9.17568, 17.99744, 27.06204, 35.7219...","[[4336.06696, 4344.727, 4353.38708, 4362.4518,..."
127,zbr106,0223_0_12,100.622535,M,wt,RSPv,RSU,0.48,127,"[[0.08091999999999189, 0.08091999999999189, 0....","[[0.2428, 0.08096000000000003, 0.0809199999999...","[[0.08091999999942345, 0.08092000000033295, 0....","[3456, 4668, 204, 516, 4592, 3544, 328, 1256, ...","[144, 736, 748, 1244, 344, 228, 1112, 236, 596...","[80, 108, 92, 160, 60, 36, 104, 56, 36, 208, 4...","[[144.0122, 153.48156, 162.78908, 172.25852, 1...","[[0.03016, 9.58032, 18.88768, 28.76164, 38.635...","[[4336.14788, 4344.727, 4353.62988, 4363.01832..."
128,zbr106,0223_0_12,100.622535,M,wt,RSPv,RSU,0.48,128,"[[0.07551999999998316, 0.13640000000000896, 0....","[[0.029679999999999984, 0.0174, 0.17056, 0.011...","[[0.010800000000017462, 0.01743999999962398, 0...","[3456, 4668, 204, 516, 4592, 3544, 328, 1256, ...","[144, 736, 748, 1244, 344, 228, 1112, 236, 596...","[80, 108, 92, 160, 60, 36, 104, 56, 36, 208, 4...","[[144.41452, 162.81764, 186.19892, 198.0122, 2...","[[0.14052, 16.925, 34.59592, 56.96092, 76.3992...","[[4336.046, 4363.3682, 4390.42648, 4415.397], ..."

got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,zbr106,0223_12_24,101.122546,M,wt,V1,RSU,0.60,0,"[[0.5920800000000099, 0.04864000000009128, 0.2...","[[0.41859999999999997, 0.4032000000000001, 0.0...","[[0.2985599999999806, 0.23888000000002307, 0.0...","[1604, 1128, 2004, 336, 128, 96, 1772, 1340, 4...","[248, 440, 896, 440, 392, 268, 408, 76, 1084, ...","[48, 172, 168, 4, 64, 56, 24, 228, 8, 200, 76,...","[[932.5568, 957.49352, 983.47544, 1005.00784, ...","[[0.276, 25.90856, 57.50984, 88.7922, 124.7734...","[[248.01032, 272.8228, 287.41624, 295.47528], ..."
1,zbr106,0223_12_24,101.122546,M,wt,V1,RSU,0.60,1,"[[1.7777200000000448, 1.1441999999999553, 0.17...","[[0.49392, 0.19479999999999986, 1.350679999999...","[[0.5840400000000159, 0.5223200000000077, 0.86...","[1604, 1128, 2004, 336, 128, 96, 1772, 1340, 4...","[248, 440, 896, 440, 392, 268, 408, 76, 1084, ...","[48, 172, 168, 4, 64, 56, 24, 228, 8, 200, 76,...","[[932.01572, 972.66652, 1008.32384, 1055.43224...","[[0.53324, 43.59684, 101.17864, 156.55636, 214...","[[248.00364, 295.79508], [760.11532, 796.11652..."
2,zbr106,0223_12_24,101.122546,M,wt,V1,FS,0.28,2,"[[0.048959999999965476, 0.13171999999997297, 0...","[[0.05284, 0.02656, 0.39791999999999994, 0.081...","[[0.022919999999999163, 0.07927999999998292, 0...","[1604, 1128, 2004, 336, 128, 96, 1772, 1340, 4...","[248, 440, 896, 440, 392, 268, 408, 76, 1084, ...","[48, 172, 168, 4, 64, 56, 24, 228, 8, 200, 76,...","[[932.1254, 949.65548, 973.78932, 991.80892, 1...","[[0.08492, 44.43544, 81.2882, 127.95472, 163.9...","[[250.27404, 284.60088, 295.75196], [761.16588..."
3,zbr106,0223_12_24,101.122546,M,wt,V1,RSU,0.56,3,"[[0.37819999999999254, 0.14764000000002397, 0....","[[0.03052, 0.21244, 0.09112000000000003, 0.227...","[[0.01383999999998764, 0.009600000000006048, 0...","[1604, 1128, 2004, 336, 128, 96, 1772, 1340, 4...","[248, 440, 896, 440, 392, 268, 408, 76, 1084, ...","[48, 172, 168, 4, 64, 56, 24, 228, 8, 200, 76,...","[[932.3488, 943.78228, 950.36492, 960.12916, 9...","[[0.00048, 15.51972, 30.17724, 54.29444, 71.17...","[[248.22496, 269.7854, 286.8134, 295.98628], [..."
4,zbr106,0223_12_24,101.122546,M,wt,V1,RSU,0.64,4,"[[0.04516000000000986, 0.0746000000000322, 0.1...","[[0.021560000000000024, 0.06435999999999997, 0...","[[0.35568000000000666, 0.11943999999999733, 1....","[1604, 1128, 2004, 336, 128, 96, 1772, 1340, 4...","[248, 440, 896, 440, 392, 268, 408, 76, 1084, ...","[48, 172, 168, 4, 64, 56, 24, 228, 8, 200, 76,...","[[932.01848, 949.0548, 972.66868, 997.39072, 1...","[[0.78732, 35.97896, 71.99836, 114.2544, 152.8...","[[248.03948, 277.04572, 295.86892], [760.03424..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,zbr106,0223_12_24,101.122546,M,wt,RSPv,FS,0.28,108,"[[0.011279999999942447, 0.01508000000001175, 0...","[[0.024719999999999992, 0.04204000000000001, 0...","[[0.4133599999999831, 0.02304000000000883, 0.1...","[1604, 1128, 2004, 336, 128, 96, 1772, 1340, 4...","[248, 440, 896, 440, 392, 268, 408, 76, 1084, ...","[48, 172, 168, 4, 64, 56, 24, 228, 8, 200, 76,...","[[932.07032, 934.78388, 943.62584, 949.6658, 9...","[[0.07004, 5.73396, 11.37744, 16.15716, 21.095...","[[248.0148, 252.23884, 257.803, 263.5412, 266...."
109,zbr106,0223_12_24,101.122546,M,wt,RSPv,RSU,0.60,109,"[[0.22943999999995413, 0.036960000000021864, 0...","[[0.39679999999999993, 0.2043600000000001, 0.0...","[[0.12092000000001235, 0.23748000000000502, 0....","[1604, 1128, 2004, 336, 128, 96, 1772, 1340, 4...","[248, 440, 896, 440, 392, 268, 408, 76, 1084, ...","[48, 172, 168, 4, 64, 56, 24, 228, 8, 200, 76,...","[[932.08316, 945.52124, 958.62208, 973.1864, 9...","[[0.15444, 12.16828, 30.5068, 46.39004, 64.539...","[[248.78776, 260.17192, 268.63468, 273.04988, ..."
110,zbr106,0223_12_24,101.122546,M,wt,RSPv,RSU,0.44,110,"[[0.16187999999999647, 0.08096000000000458, 0....","[[0.08091999999999999, 0.08096, 0.323800000000...","[[0.08091999999999189, 0.08096000000000458, 0....","[1604, 1128, 2004, 336, 128, 96, 1772, 1340, 4...","[248, 440, 896, 440, 392, 268, 408, 76, 1084, ...","[48, 172, 168, 4, 64, 56, 24, 228, 8, 200, 76,...","[[932.03444, 940.85712, 949.67984, 958.34068, ...","[[0.05288, 9.36148, 18.02252, 26.68356, 35.344...","[[248.0676, 256.80964, 265.30888, 274.21284, 2..."
111,zbr106,0223_12_24,101.122546,M,wt,RSPv,RSU,0.68,111,"[[0.21928000000002612, 0.18127999999990152, 0....","[[0.0015999999999999903, 0.18672, 0.4291200000...","[[0.40863999999999123, 0.25219999999998777, 0....","[1604, 1128, 2004, 336, 128, 96, 1772, 1340, 4...","[248, 440, 896, 440, 392, 268, 408, 76, 1084, ...","[48, 172, 168, 4, 64, 56, 24, 228, 8, 200, 76,...","[[932.35428, 958.07328, 986.57984, 1017.29744,...","[[0.15292, 22.244, 42.96064, 68.1706, 90.81184...","[[248.7418, 270.3708, 284.32924, 295.86064], [..."
112,zbr106,0223_12_24,101.122546,M,wt,RSPv,RSU,0.48,112,"[[0.08096000000000458, 0.08096000000000458, 0....","[[0.08096, 0.08096, 0.08091999999999999, 0.080...","[[0.08096000000000458, 0.08092000000002031, 0....","[1604, 1128, 2004, 336, 128, 96, 1772, 1340, 4...","[248, 440, 896, 440, 392, 268, 408, 76, 1084, ...","[48, 172, 168, 4, 64, 56, 24, 228, 8, 200, 76,...","[[932.0344, 942.07124, 951.62244, 961.2546, 97...","[[0.05284, 9.4424, 18.67008, 27.97868, 37.3682...","[[248.06756, 257.29528, 266.44208, 275.99356, ..."

Working on zbr113
Has 1 files to go through
got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,zbr113,0513_0_12,90.527164,M,app_ps1,V1,RSU,1.04,0,"[[0.0028000000000076852, 0.0035599999999931242...","[[0.27515999999741325, 0.6890000000021246, 0.4...","[[0.060800000002927845, 0.023399999998218846, ...","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[140.8896, 174.05208, 215.17308, 257.6592, 26...","[[21728.02644, 21742.42936, 21754.9526, 21770....","[[21876.02556, 21892.48048, 21939.21292, 21955..."
1,zbr113,0513_0_12,90.527164,M,app_ps1,V1,RSU,0.52,1,"[[0.17371999999997456, 0.020080000000007203, 0...","[[0.1264000000010128, 0.6417599999986123, 0.06...","[[0.060960000002523884, 0.0054799999998067506,...","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[140.76696, 152.05096, 160.791, 170.76132, 17...","[[21728.11404, 21739.78504, 21749.93264, 21761...","[[21876.02556, 21885.92936, 21895.02964, 21903..."
2,zbr113,0513_0_12,90.527164,M,app_ps1,V1,RSU,0.60,2,"[[0.20012000000002672, 0.0027599999999949887, ...","[[0.0031999999991967343, 0.021360000002459856,...","[[0.007639999999810243, 0.01764000000184751, 0...","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[140.68952, 172.6374, 218.5468, 263.57656, 26...","[[21728.01588, 21732.15368, 21736.69372, 21741...","[[21876.0618, 21881.34388, 21886.76776, 21908...."
3,zbr113,0513_0_12,90.527164,M,app_ps1,V1,RSU,0.52,3,"[[0.7935200000000009, 4.23048, 3.0991999999999...","[[0.6890000000021246, 0.4117599999990489, 0.41...","[[0.08947999999872991, 0.6671999999998661, 0.0...","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[142.498, 321.6146, 373.47584, 451.78508], [6...","[[21728.3016, 21775.76244, 21825.94696, 21869....","[[21876.5224, 21927.08904, 21955.92728], [2284..."
4,zbr113,0513_0_12,90.527164,M,app_ps1,RSPv,RSU,0.60,4,"[[0.004959999999982756, 0.018160000000023047, ...","[[0.07219999999870197, 0.038800000002083834, 0...","[[0.005760000000009313, 0.019039999999222346, ...","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[140.70524, 144.94264, 149.39692, 153.67188, ...","[[21728.00088, 21732.58864, 21737.1672, 21742....","[[21876.13304, 21881.92436, 21887.321, 21892.3..."
5,zbr113,0513_0_12,90.527164,M,app_ps1,RSPv,RSU,0.48,5,"[[0.02248000000000161, 0.009559999999993352, 0...","[[4.452439999997296, 0.4662800000005518, 1.038...","[[1.5850000000027649, 0.6179999999985739, 0.55...","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[140.7218, 158.05344, 181.84104, 199.19764, 2...","[[21728.80812, 21833.59876, 21875.8752], [2228...","[[21876.48636, 21896.56896, 21909.70492, 21926..."
6,zbr113,0513_0_12,90.527164,M,app_ps1,RSPv,RSU,0.48,6,"[[0.0553600000000074, 0.02276000000000522, 0.1...","[[0.7278799999985495, 0.7329600000011851, 2.44...","[[0.6991200000011304, 0.14140000000043074, 2.9...","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[140.6984, 155.77136, 181.78636, 199.80372, 2...","[[21731.79964, 21842.25896, 21875.1712], [2228...","[[21876.48632, 21899.526, 21913.81216, 21933.4..."
7,zbr113,0513_0_12,90.527164,M,app_ps1,RSPv,RSU,0.56,7,"[[0.04048000000000229, 0.042360000000002174, 0...","[[0.25407999999879394, 0.057199999999284046, 0...","[[0.03087999999843305, 0.028040000001055887, 0...","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[140.79292, 148.82632, 155.92504, 163.39096, ...","[[21728.10684, 21735.56088, 21743.66304, 21752...","[[21876.13388, 21884.76252, 21891.65356, 21897..."
8,zbr113,0513_0_12,90.527164,M,app_ps1,RSPv,RSU,0.76,8,"[[0.00435999999999126, 0.4379200000000196, 0.1...","[[0.04392000000007101, 0.21120000000155414, 0....","[[0.01599999999962165, 0.007040000000415603, 0...","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[141.38324, 198.99836, 255.4416, 300.58576, 3...","[[21728.00548, 21736.0624, 21745.20732, 21754....","[[21876.137, 21884.51716, 21892.36756, 21897.1..."
9,zbr113,0513_0_12,90.527164,M,app_ps1,RSPv,RSU,0.64,9,"[[0.051639999999991915, 0.08003999999999678, 0...","[[0.2101199999997334, 0.06484000000273227, 0.0...","[[0.029839999999239808, 0.011080000000220025, ...","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[140.6988, 145.64216, 151.36208, 158.53096, 1...","[[21728.00536, 21735.23384, 21741.08532, 21746...","[[21876.1608, 21884.87052, 21889.10012, 21890...."
10,zbr113,0513_0_12,90.527164,M,app_ps1,RSPv,RSU,0.60,10,"[[0.7474799999999959, 0.2844400000000178, 0.04...","[[0.13564000000042142, 0.3817200000012235, 0.1...","[[0.037239999997837, 0.012080000000423752, 0.0...","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[140.6882, 190.92104, 234.0516, 269.56116, 30...","[[21728.02052, 21738.12512, 21747.59736, 21756...","[[21876.13692, 21888.58368, 21893.6588, 21901...."
11,zbr113,0513_0_12,90.527164,M,app_ps1,RSPv,RSU,0.68,11,"[[0.1149599999999964, 0.042839999999984, 0.018...","[[1.3251199999976961, 0.3088800000004994, 0.32...","[[0.04235999999946216, 0.3040800000017043, 2.4...","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[140.74028, 184.96, 210.00912, 238.87976, 263...","[[21728.16572, 21817.47308, 21875.66992], [222...","[[21877.69028, 21903.18704, 21919.9848, 21936...."
12,zbr113,0513_0_12,90.527164,M,app_ps1,RSPv,RSU,0.84,12,"[[0.5574799999999982, 0.029480000000006612, 0....","[[0.1758399999998801, 1.5887199999997392, 0.86...","[[0.42344000000230153, 0.7486399999979767, 0.2...","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[140.76684, 179.948, 210.70324, 235.86368, 26...","[[21728.70184, 21764.94072, 21817.48644, 21851...","[[21876.26432, 21905.73904, 21937.28116, 21954..."
13,zbr113,0513_0_12,90.527164,M,app_ps1,CA1,RSU,0.60,13,"[[0.06631999999999039, 0.023480000000006385, 1...","[[0.037599999999656575, 1.0864399999991292, 1....","[[0.4996800000008079, 0.2500399999989895, 0.66...","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[142.30112, 225.67332, 267.80548, 293.66228, ...","[[21728.32572, 21833.54744, 21874.374], [22282...","[[21878.801, 21954.72412], [22849.65872, 22963..."
14,zbr113,0513_0_12,90.527164,M,app_ps1,CA1,RSU,0.60,14,"[[0.3393599999999992, 0.08371999999999957, 0.3...","[[0.05691999999908148, 0.09744000000137021, 0....","[[0.005559999997785781, 0.1740800000006857, 0....","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[140.93348, 160.84692, 178.12708, 190.7664, 2...","[[21728.0104, 21739.28812, 21753.99256, 21765....","[[21876.31304, 21891.75572, 21905.41916, 21915..."
15,zbr113,0513_0_12,90.527164,M,app_ps1,CA1,FS,0.32,15,"[[0.17871999999999844, 0.05719999999999459, 0....","[[0.029279999998834683, 0.03944000000046799, 0...","[[0.033400000000256114, 0.030240000000048894, ...","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[140.68968, 150.6962, 162.96004, 174.71948, 1...","[[21728.02868, 21733.63392, 21739.36656, 21744...","[[21876.0402, 21881.9966, 21887.35516, 21892.4..."
16,zbr113,0513_0_12,90.527164,M,app_ps1,CA1,RSU,0.68,16,"[[0.04959999999999809, 0.010120000000000573, 0...","[[0.028879999998025596, 0.05644000000029337, 0...","[[0.03499999999985448, 0.11103999999977532, 0....","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[140.9358, 149.21792, 163.35744, 181.9372, 19...","[[21728.07932, 21739.28648, 21752.58664, 21762...","[[21876.07592, 21888.8382, 21895.06696, 21900...."
17,zbr113,0513_0_12,90.527164,M,app_ps1,CA1,RSU,0.84,17,"[[0.06924000000000774, 0.1963999999999828, 0.0...","[[1.747640000001411, 0.07031999999890104, 0.30...","[[0.41563999999925727, 0.07940000000235159, 0....","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[140.70352, 155.51012, 170.56324, 184.6638, 2...","[[21728.73076, 21756.74368, 21778.6944, 21804....","[[21876.21692, 21895.35716, 21906.10272, 21917..."
18,zbr113,0513_0_12,90.527164,M,app_ps1,CA1,RSU,0.60,18,"[[0.29359999999999786, 0.13124000000001956, 0....","[[0.04583999999886146, 0.019280000000435393, 0...","[[0.3798000000024331, 0.045199999996839324, 0....","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[140.77316, 160.56804, 170.17384, 179.38308, ...","[[21728.42264, 21748.64116, 21765.5834, 21780....","[[21876.11136, 21888.45404, 21896.5144, 21904...."
19,zbr113,0513_0_12,90.527164,M,app_ps1,CA1,RSU,1.00,19,"[[0.034279999999995425, 0.05763999999999214, 0...","[[0.004000000000814907, 0.011480000001029111, ...","[[0.11396000000240747, 0.09771999999793479, 0....","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[140.73956, 162.56808, 184.6978, 198.01604, 2...","[[21728.04456, 21732.40984, 21737.09184, 21740...","[[21876.3418, 21891.25, 21896.06256, 21903.125..."
20,zbr113,0513_0_12,90.527164,M,app_ps1,ACad,FS,0.20,20,"[[0.308400000000006, 0.4242799999999818, 0.346...","[[0.04655999999886262, 0.012480000001232838, 0...","[[0.08724000000074739, 0.1104799999993702, 0.0...","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[140.68912, 220.52584, 269.17848, 295.9146, 3...","[[21728.03184, 21732.36112, 21737.17704, 21742...","[[21876.02252, 21881.61864, 21889.0158, 21954...."
21,zbr113,0513_0_12,90.527164,M,app_ps1,ACad,RSU,0.64,21,"[[17.010040000000004, 0.726680000000016, 2.080...","[[0.02463999999963562, 0.1210800000008021, 0.2...","[[0.7298799999989569, 1.8172400000003108, 0.09...","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[144.92816, 242.84072, 267.77328, 290.80372, ...","[[21728.35412, 21749.29008, 21776.06128, 21800...","[[21876.10376, 21937.88296, 21955.03364], [228..."
22,zbr113,0513_0_12,90.527164,M,app_ps1,ACad,RSU,0.68,22,"[[0.015879999999981464, 0.13304000000002247, 0...","[[0.031199999997625127, 0.046760000001086155, ...","[[0.042480000000068685, 0.08852000000115368, 0...","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[140.9172, 172.13084, 194.20648, 215.97256, 2...","[[21728.026, 21741.32196, 21751.59236, 21762.4...","[[21876.11116, 21888.35156, 21900.84796, 21914..."
23,zbr113,0513_0_12,90.527164,M,app_ps1,ACad,RSU,0.56,23,"[[1.7210800000000006, 0.6872400000000027, 0.09...","[[0.11915999999837368, 0.04628000000229804, 0....","[[0.36067999999795575, 0.004320000000006985, 0...","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[141.03268, 198.23468, 228.80268, 243.55132, ...","[[21728.23776, 21742.26204, 21753.10752, 21771...","[[21878.26856, 21931.27092, 21954.753], [22848..."
24,zbr113,0513_0_12,90.527164,M,app_ps1,ACad,RSU,0.64,24,"[[0.0146000000000015, 0.08799999999999386, 0.0...","[[0.038720000000466825, 0.014520000000629807, ...","[[0.0020800000020244624, 0.02943999999843072, ...","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[140.68524, 147.06436, 153.53312, 160.22536, ...","[[21728.02636, 21734.53616, 21740.90204, 21747...","[[21876.10936, 21881.0466, 21889.2016, 21892.5..."
25,zbr113,0513_0_12,90.527164,M,app_ps1,ACad,FS,0.28,25,"[[0.036200000000008004, 0.09144000000000574, 0...","[[0.010999999998603016, 0.020000000000436557, ...","[[0.008160000001225853, 0.009040000000823056, ...","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[140.69188, 148.124, 154.08892, 161.27996, 16...","[[21728.11332, 21732.78232, 21737.12556, 21741...","[[21876.11568, 21879.99972, 21885.26908, 21889..."
26,zbr113,0513_0_12,90.527164,M,app_ps1,ACad,RSU,0.60,26,"[[0.18448000000000775, 0.009559999999993352, 0...","[[0.0665999999982887, 0.17699999999967986, 0.0...","[[0.008079999999608845, 0.020119999997405102, ...","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[141.01412, 173.63092, 200.66856, 219.07904, ...","[[21728.53668, 21739.84304, 21752.5916, 21763....","[[21876.1454, 21893.4998, 21916.36032, 21936.0..."
27,zbr113,0513_0_12,90.527164,M,app_ps1,ACad,RSU,0.52,27,"[[0.4692799999999977, 1.364360000000005, 1.476...","[[0.11263999999937369, 0.20112000000153785, 0....","[[0.2534799999993993, 0.005640000003040768, 0....","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[141.61784, 204.24476, 262.05948, 267.2934, 2...","[[21728.04032, 21741.35456, 21753.77148, 21768...","[[21876.5176, 21913.65188, 21954.98308], [2284..."
28,zbr113,0513_0_12,90.527164,M,app_ps1,ACad,RSU,0.80,28,"[[1.9087999999999852, 0.02116000000000895, 2.1...","[[0.03784000000086962, 0.04095999999844935, 0....","[[0.03935999999885098, 0.047959999999875436, 0...","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[263.32088, 437.9852, 451.96968], [849.21276,...","[[21728.12432, 21734.40084, 21740.788, 21746.9...","[[21876.02248, 21882.62612, 21890.90336, 21909..."
29,zbr113,0513_0_12,90.527164,M,app_ps1,ACad,RSU,0.76,29,"[[0.09151999999997429, 0.002720000000010714, 0...","[[0.23168000000077882, 0.0021199999973759986, ...","[[0.008720000001630979, 0.0015199999979813583,...","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[140.8232, 146.05544, 155.71664, 165.2718, 17...","[[21728.07384, 21735.5592, 21743.99164, 21751....","[[21876.07652, 21885.30808, 21889.44288, 21894..."
30,zbr113,0513_0_12,90.527164,M,app_ps1,ACad,RSU,0.72,30,"[[52.19300000000001, 20.308480000000003, 0.322...","[[0.10071999999854597, 0.4184800000002724, 0.2...","[[0.8614400000005844, 0.8650799999995797, 0.04...","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[145.48528, 449.75516], [615.70728, 1015.8026...","[[21733.10564, 21784.65164, 21831.71036, 21875...","[[21876.18808, 21915.66744, 21946.00868], [228..."
31,zbr113,0513_0_12,90.527164,M,app_ps1,ACad,RSU,0.72,31,"[[0.04040000000000532, 0.18375999999997816, 0....","[[0.11767999999938183, 0.48751999999876716, 0....","[[1.1927600000017264, 0.15355999999883352, 0.1...","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[140.76076, 150.87004, 158.50612, 175.36068, ...","[[21728.07544, 21746.3468, 21756.633, 21773.79...","[[21876.11064, 21891.7538, 21904.78352, 21919...."
32,zbr113,0513_0_12,90.527164,M,app_ps1,ACad,RSU,0.68,32,"[[0.6229999999999905, 0.00532000000001176, 0.9...","[[0.11476000000038766, 0.7196000000003551, 0.2...","[[0.0842400000001362, 0.20808000000033644, 0.1...","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[140.80116, 175.30252, 201.87088, 232.59096, ...","[[21728.39876, 21751.43296, 21777.0804, 21802....","[[21876.11072, 21898.9786, 21922.9946, 21943.4..."
33,zbr113,0513_0_12,90.527164,M,app_ps1,ACad,RSU,0.72,33,"[[0.08155999999999608, 0.005240000000014788, 0...","[[0.4038799999980256, 0.022920000003068708, 0....","[[0.001720000000204891, 0.003359999998792773, ...","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[140.73468, 149.8304, 160.22788, 171.37728, 1...","[[21728.12512, 21734.94532, 21741.30108, 21748...","[[21876.0936, 21884.64516, 21893.99848, 21900...."
34,zbr113,0513_0_12,90.527164,M,app_ps1,ACad,RSU,0.64,34,"[[0.7353999999999985, 0.1256800000000169, 0.92...","[[0.5626000000011118, 0.28875999999945634, 1.5...","[[1.1155199999993783, 0.004839999997784616, 0....","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[140.89236, 202.7894, 233.46108, 270.41224, 2...","[[21729.4964, 21769.34352, 21797.36424, 21837....","[[21876.46956, 21898.36872, 21922.3592, 21939...."
35,zbr113,0513_0_12,90.527164,M,app_ps1,ACad,RSU,0.64,35,"[[0.1994799999999941, 0.02496000000002141, 0.0...","[[0.28127999999924214, 0.3939600000012433, 0.4...","[[0.03403999999864027, 0.5085600000020349, 0.8...","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[141.49632, 157.16152, 172.95384, 192.3606, 2...","[[21728.28944, 21756.10592, 21796.81504, 21836...","[[21876.51336, 21895.31024, 21955.13496], [228..."
36,zbr113,0513_0_12,90.527164,M,app_ps1,ACad,RSU,0.52,36,"[[0.07735999999999876, 0.08096000000000458, 0....","[[0.11300000000119326, 1.0994399999981397, 0.1...","[[0.36428000000159955, 0.010959999999613501, 0...","[452, 532, 1932, 4848, 2228, 6616, 1276, 820, ...","[148, 568, 568, 520, 408, 436, 256, 32, 592, 8...","[80, 116, 16, 120, 128, 52, 60, 72, 64, 148, 7...","[[141.06776, 186.48388, 210.26244, 224.41136, ...","[[21728.1486, 21751.2782, 21769.40388, 21788.1...","[[21876.17396, 21895.82144, 21907.7022, 21917...."

Working on zbr114
Has 2 files to go through
got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,zbr114,0426_0_12,73.413623,F,app_ps1,V1,RSU,0.64,0,"[[0.42427999999995336, 0.13548000000002958, 0....","[[0.19912000000000063, 0.0028800000000046566, ...","[[0.012399999999999523, 0.0038799999999952206,...","[1280, 1236, 128, 448, 7044, 608, 1488, 468, 3...","[28, 68, 44, 136, 160, 112, 76, 124, 616, 172,...","[28, 44, 28, 24, 144, 72, 68, 24, 176, 152, 72...","[[1020.0494, 1031.2734, 1036.49532, 1041.30156...","[[44.09672, 51.90648, 58.12824, 65.40404, 71.9...","[[72.08708, 82.06636, 90.68392, 99.97656], [26..."
1,zbr114,0426_0_12,73.413623,F,app_ps1,V1,RSU,0.56,1,"[[0.017879999999991014, 0.11116000000004078, 0...","[[0.0046399999999948704, 0.17999999999999972, ...","[[0.24296000000001072, 0.017479999999991946, 0...","[1280, 1236, 128, 448, 7044, 608, 1488, 468, 3...","[28, 68, 44, 136, 160, 112, 76, 124, 616, 172,...","[28, 44, 28, 24, 144, 72, 68, 24, 176, 152, 72...","[[1020.05252, 1030.1708, 1035.56404, 1039.4092...","[[44.0598, 52.0408, 60.98108, 68.74876, 71.967...","[[72.24676, 84.64944, 93.50756, 99.6026], [268..."
2,zbr114,0426_0_12,73.413623,F,app_ps1,V1,RSU,0.56,2,"[[1.1539600000000974, 0.19087999999999283, 0.0...","[[0.028759999999998342, 0.29736000000000473, 0...","[[1.0403199999999941, 0.12463999999999942, 0.2...","[1280, 1236, 128, 448, 7044, 608, 1488, 468, 3...","[28, 68, 44, 136, 160, 112, 76, 124, 616, 172,...","[28, 44, 28, 24, 144, 72, 68, 24, 176, 152, 72...","[[1020.1732, 1038.61092, 1058.45216, 1079.1993...","[[44.0584, 58.57024, 71.84156], [120.46604, 14...","[[72.01936, 90.09952, 99.80284], [268.67032, 2..."
3,zbr114,0426_0_12,73.413623,F,app_ps1,V1,RSU,0.64,3,"[[4.434479999999894, 1.8495200000002114, 0.409...","[[1.1457600000000028, 0.1961999999999975, 0.11...","[[0.5364000000000004, 0.894599999999997, 1.527...","[1280, 1236, 128, 448, 7044, 608, 1488, 468, 3...","[28, 68, 44, 136, 160, 112, 76, 124, 616, 172,...","[28, 44, 28, 24, 144, 72, 68, 24, 176, 152, 72...","[[1020.17264, 1057.95384, 1077.78376, 1089.399...","[[46.53312, 70.12064], [122.27872, 184.66932],...","[[74.8266, 99.55768], [268.05624, 309.87788], ..."
4,zbr114,0426_0_12,73.413623,F,app_ps1,V1,RSU,0.64,4,"[[0.013120000000071741, 0.031559999999899446, ...","[[0.01899999999999835, 0.00560000000000116, 0....","[[0.2634000000000043, 0.10291999999999746, 0.0...","[1280, 1236, 128, 448, 7044, 608, 1488, 468, 3...","[28, 68, 44, 136, 160, 112, 76, 124, 616, 172,...","[28, 44, 28, 24, 144, 72, 68, 24, 176, 152, 72...","[[1020.0096, 1029.3278, 1033.99416, 1038.51988...","[[44.05324, 50.56088, 57.32124, 64.36744, 71.8...","[[72.00032, 80.86032, 87.5456, 95.85736, 99.94..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,zbr114,0426_0_12,73.413623,F,app_ps1,ACad,RSU,0.76,115,"[[0.004959999999982756, 0.04944000000000415, 0...","[[0.0517200000000031, 0.1669999999999945, 0.06...","[[0.24523999999999546, 0.008720000000010941, 0...","[1280, 1236, 128, 448, 7044, 608, 1488, 468, 3...","[28, 68, 44, 136, 160, 112, 76, 124, 616, 172,...","[28, 44, 28, 24, 144, 72, 68, 24, 176, 152, 72...","[[1020.09032, 1029.20676, 1035.51668, 1042.894...","[[44.68132, 58.69612, 71.86704, 71.97084], [12...","[[72.29248, 85.4476, 97.59552, 99.97248], [268..."
116,zbr114,0426_0_12,73.413623,F,app_ps1,ACad,RSU,0.64,116,"[[0.10104000000001179, 0.04100000000005366, 0....","[[0.48763999999999896, 0.11227999999999838, 0....","[[0.34208000000000993, 0.07739999999999725, 0....","[1280, 1236, 128, 448, 7044, 608, 1488, 468, 3...","[28, 68, 44, 136, 160, 112, 76, 124, 616, 172,...","[28, 44, 28, 24, 144, 72, 68, 24, 176, 152, 72...","[[1020.22332, 1033.81176, 1041.2406, 1053.4017...","[[44.02532, 64.31412, 71.48312], [120.36004, 1...","[[72.32936, 91.55072, 99.71688], [268.17804, 2..."
117,zbr114,0426_0_12,73.413623,F,app_ps1,ACad,RSU,0.64,117,"[[0.0986800000000585, 0.22727999999995063, 0.2...","[[0.11968000000000245, 0.08499999999999375, 0....","[[1.7435600000000022, 0.00843999999999312, 0.3...","[1280, 1236, 128, 448, 7044, 608, 1488, 468, 3...","[28, 68, 44, 136, 160, 112, 76, 124, 616, 172,...","[28, 44, 28, 24, 144, 72, 68, 24, 176, 152, 72...","[[1020.10656, 1047.08588, 1071.22376, 1075.469...","[[44.26312, 69.73388], [120.10996, 152.1656, 1...","[[72.88848, 99.60172], [268.16952, 311.70968],..."
118,zbr114,0426_0_12,73.413623,F,app_ps1,ACad,RSU,0.60,118,"[[0.006160000000022592, 0.12627999999995154, 0...","[[0.11968000000000245, 0.08500000000000085, 0....","[[0.3641199999999998, 0.005400000000008731, 0....","[1280, 1236, 128, 448, 7044, 608, 1488, 468, 3...","[28, 68, 44, 136, 160, 112, 76, 124, 616, 172,...","[28, 44, 28, 24, 144, 72, 68, 24, 176, 152, 72...","[[1020.19916, 1046.5736, 1070.42452, 1074.0395...","[[44.2632, 70.37752], [120.11008, 150.88164, 1...","[[74.64052, 99.6018], [269.7558, 311.70972], [..."
119,zbr114,0426_0_12,73.413623,F,app_ps1,ACad,RSU,0.60,119,"[[0.062360000000012406, 0.28952000000003864, 0...","[[0.382080000000002, 0.2505199999999945, 0.120...","[[0.7497999999999934, 0.0018000000000029104, 0...","[1280, 1236, 128, 448, 7044, 608, 1488, 468, 3...","[28, 68, 44, 136, 160, 112, 76, 124, 616, 172,...","[28, 44, 28, 24, 144, 72, 68, 24, 176, 152, 72...","[[1020.09564, 1033.99852, 1041.80536, 1053.529...","[[44.347, 66.25268, 71.53668], [120.10488, 138...","[[72.67152, 93.31576, 99.72668], [268.11936, 2..."

got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,zbr114,0426_12_24,73.913634,F,app_ps1,V1,RSU,0.60,0,"[[0.021199999999999997, 0.030520000000000005, ...","[[0.037119999999958964, 0.15768000000025495, 0...","[[0.019879999999830034, 0.6748400000005859, 0....","[876, 268, 840, 448, 540, 488, 476, 284, 1544,...","[264, 260, 184, 252, 96, 136, 240, 180, 208, 1...","[88, 40, 76, 96, 24, 80, 80, 120, 56, 60, 84, ...","[[0.01192, 29.98304, 58.06952, 84.75724, 121.8...","[[4356.31628, 4382.3398, 4403.69272, 4424.2521...","[[4620.17408, 4642.45124, 4677.62428, 4707.969..."
1,zbr114,0426_12_24,73.913634,F,app_ps1,V1,RSU,0.60,1,"[[0.49804000000000004, 0.06655999999999995, 0....","[[0.14804000000003725, 0.12923999999929947, 0....","[[0.04524000000037631, 0.10815999999977066, 0....","[876, 268, 840, 448, 540, 488, 476, 284, 1544,...","[264, 260, 184, 252, 96, 136, 240, 180, 208, 1...","[88, 40, 76, 96, 24, 80, 80, 120, 56, 60, 84, ...","[[0.21568, 20.22744, 36.71696, 53.05004, 71.10...","[[4356.13276, 4377.89888, 4410.2028, 4444.4907...","[[4620.26456, 4652.82228, 4679.65876, 4697.681..."
2,zbr114,0426_12_24,73.913634,F,app_ps1,V1,RSU,0.60,2,"[[0.71388, 0.06028000000000011, 0.090559999999...","[[0.8950000000004366, 0.287359999999353, 0.200...","[[0.010199999999713327, 0.12816000000020722, 1...","[876, 268, 840, 448, 540, 488, 476, 284, 1544,...","[264, 260, 184, 252, 96, 136, 240, 180, 208, 1...","[88, 40, 76, 96, 24, 80, 80, 120, 56, 60, 84, ...","[[0.23416, 25.38416, 50.4936, 81.4434, 113.394...","[[4358.1268, 4454.35536, 4533.44112, 4612.4760...","[[4620.4716, 4683.99744, 4698.97224, 4707.7934..."
3,zbr114,0426_12_24,73.913634,F,app_ps1,V1,RSU,0.60,3,"[[0.1754, 0.09523999999999994, 0.0895600000000...","[[0.08339999999952852, 0.09464000000025408, 0....","[[0.13807999999971798, 0.039240000000063446, 0...","[876, 268, 840, 448, 540, 488, 476, 284, 1544,...","[264, 260, 184, 252, 96, 136, 240, 180, 208, 1...","[88, 40, 76, 96, 24, 80, 80, 120, 56, 60, 84, ...","[[0.2624, 5.8462, 10.50508, 14.62652, 18.0068,...","[[4356.0546, 4366.29732, 4378.62868, 4391.3962...","[[4620.01548, 4630.61808, 4641.36272, 4649.697..."
4,zbr114,0426_12_24,73.913634,F,app_ps1,V1,RSU,0.68,4,"[[0.003959999999999991, 0.08052000000000001, 0...","[[0.7067600000000311, 0.011080000000220025, 0....","[[0.09128000000055181, 0.09591999999975087, 0....","[876, 268, 840, 448, 540, 488, 476, 284, 1544,...","[264, 260, 184, 252, 96, 136, 240, 180, 208, 1...","[88, 40, 76, 96, 24, 80, 80, 120, 56, 60, 84, ...","[[0.16592, 8.81976, 15.00444, 21.45672, 30.697...","[[4356.06996, 4377.1628, 4395.80304, 4413.4199...","[[4620.21876, 4641.4614, 4661.46456, 4679.4963..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,zbr114,0426_12_24,73.913634,F,app_ps1,ACad,RSU,0.64,64,"[[0.0022799999999999995, 0.013720000000000001,...","[[0.5134800000005271, 0.07463999999981752, 0.1...","[[], [0.007160000000112632, 0.0106799999994109...","[876, 268, 840, 448, 540, 488, 476, 284, 1544,...","[264, 260, 184, 252, 96, 136, 240, 180, 208, 1...","[88, 40, 76, 96, 24, 80, 80, 120, 56, 60, 84, ...","[[0.0022, 1.54132, 3.13704, 5.76716, 8.24612, ...","[[4356.003, 4363.3036, 4369.13776, 4376.1962, ...","[[], [5428.01108, 5436.82728, 5442.61396, 5450..."
65,zbr114,0426_12_24,73.913634,F,app_ps1,ACad,RSU,0.48,65,"[[0.02312, 0.10620000000000002, 0.173799999999...","[[0.02048000000013417, 0.08096000000023196, 0....","[[0.7280799999998635, 0.3705999999992855, 0.63...","[876, 268, 840, 448, 540, 488, 476, 284, 1544,...","[264, 260, 184, 252, 96, 136, 240, 180, 208, 1...","[88, 40, 76, 96, 24, 80, 80, 120, 56, 60, 84, ...","[[0.0026, 5.47184, 11.85652, 16.10296, 23.6154...","[[4356.23416, 4368.13764, 4378.7996, 4389.3541...","[[4620.14464, 4665.09636, 4693.02644, 4707.459..."
66,zbr114,0426_12_24,73.913634,F,app_ps1,ACad,RSU,0.64,66,"[[0.5917600000000001, 0.20384000000000002, 0.2...","[[0.9549600000000282, 0.4084400000001551, 1.40...","[[10.215079999999944], [0.46524000000044907, 7...","[876, 268, 840, 448, 540, 488, 476, 284, 1544,...","[264, 260, 184, 252, 96, 136, 240, 180, 208, 1...","[88, 40, 76, 96, 24, 80, 80, 120, 56, 60, 84, ...","[[0.4598, 34.51816, 70.235, 99.24692, 132.1226...","[[4357.26812, 4430.07124, 4504.97196, 4582.645...","[[4682.71028, 4692.92536], [5428.26984, 5467.6..."
67,zbr114,0426_12_24,73.913634,F,app_ps1,ACad,RSU,0.72,67,"[[0.1582, 0.07636000000000001, 0.01432, 0.1035...","[[0.011679999999614665, 0.23976000000038766, 0...","[[], [0.059879999999793654, 0.0453999999999723...","[876, 268, 840, 448, 540, 488, 476, 284, 1544,...","[264, 260, 184, 252, 96, 136, 240, 180, 208, 1...","[88, 40, 76, 96, 24, 80, 80, 120, 56, 60, 84, ...","[[0.02268, 9.38236, 15.65908, 28.41156, 42.359...","[[4356.00852, 4365.78056, 4378.37312, 4389.569...","[[], [5428.05148, 5441.23484, 5453.46072, 5467..."
68,zbr114,0426_12_24,73.913634,F,app_ps1,ACad,RSU,0.68,68,"[[0.03264, 0.0274, 0.018039999999999994, 0.008...","[[0.02172000000064145, 0.20583999999962543, 0....","[[], [0.13968000000022585, 0.0846400000000358,...","[876, 268, 840, 448, 540, 488, 476, 284, 1544,...","[264, 260, 184, 252, 96, 136, 240, 180, 208, 1...","[88, 40, 76, 96, 24, 80, 80, 120, 56, 60, 84, ...","[[4e-05, 2.57912, 5.77696, 8.7086, 10.82836, 1...","[[4356.00192, 4361.178, 4366.29744, 4372.21236...","[[], [5428.0018, 5437.537, 5444.59264, 5454.48..."

Working on zbr117
Has 3 files to go through
got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,zbr117,0502_0_9,79.394028,M,app_ps1,RSPv,RSU,0.52,0,"[[3.759520000000002, 13.008680000000002, 0.851...","[[20.957519999999988, 4.623639999999995, 0.516...","[[9.202400000000011, 33.142559999999946, 4.813...","[164, 204, 160, 996, 472, 2096, 696, 956, 1036...","[128, 408, 740, 712, 384, 448, 448, 512, 348, ...","[88, 148, 192, 164, 116, 132, 144, 88, 68, 40,...","[[16.2034, 140.25128], [389.77624, 583.3938], ...","[[208.0208, 279.54408], [592.82312, 983.21], [...","[[298.38508, 374.78752], [993.95632, 1136.7280..."
1,zbr117,0502_0_9,79.394028,M,app_ps1,RSPv,FS,0.32,1,"[[13.69536, 0.5660799999999995, 1.555519999999...","[[2.512599999999992, 6.044319999999999, 8.2121...","[[1.3405599999999822, 4.9133600000000115, 0.56...","[164, 204, 160, 996, 472, 2096, 696, 956, 1036...","[128, 408, 740, 712, 384, 448, 448, 512, 348, ...","[88, 148, 192, 164, 116, 132, 144, 88, 68, 40,...","[[1.623, 155.86952], [380.87692, 582.33248], [...","[[169.65436, 282.58924], [584.072, 825.83596, ...","[[292.46296, 378.41132], [992.26192, 1092.4883..."
2,zbr117,0502_0_9,79.394028,M,app_ps1,RSPv,RSU,0.52,2,"[[], [48.77496000000002, 12.640479999999968, 2...","[[44.56316000000001], [5.733240000000023, 21.0...","[[14.895199999999988, 12.76660000000004], [6.7...","[164, 204, 160, 996, 472, 2096, 696, 956, 1036...","[128, 408, 740, 712, 384, 448, 448, 512, 348, ...","[88, 148, 192, 164, 116, 132, 144, 88, 68, 40,...","[[57.45872], [391.5906, 578.7956], [1160.15984...","[[223.04016, 267.60332], [601.20864, 985.9706]...","[[327.54816, 355.20996], [997.54432, 1134.6686..."
3,zbr117,0502_0_9,79.394028,M,app_ps1,RSPv,RSU,0.52,3,"[[7.7936, 0.24127999999999972, 0.1423199999999...","[[2.4340799999999945, 0.940480000000008, 1.270...","[[5.99824000000001, 1.7390800000000013, 0.4789...","[164, 204, 160, 996, 472, 2096, 696, 956, 1036...","[128, 408, 740, 712, 384, 448, 448, 512, 348, ...","[88, 148, 192, 164, 116, 132, 144, 88, 68, 40,...","[[4e-05, 161.17056], [380.26652, 582.58736], [...","[[170.9888, 287.79444], [617.9184, 974.17568],...","[[292.23528, 379.16108], [995.39908, 1137.4811..."
4,zbr117,0502_0_9,79.394028,M,app_ps1,RSPv,RSU,0.56,4,"[[0.06956000000000001, 0.394, 0.03784000000000...","[[0.049080000000003565, 0.04344000000000392, 0...","[[0.03311999999999671, 0.2879599999999982, 0.0...","[164, 204, 160, 996, 472, 2096, 696, 956, 1036...","[128, 408, 740, 712, 384, 448, 448, 512, 348, ...","[88, 148, 192, 164, 116, 132, 144, 88, 68, 40,...","[[0.02328, 13.53948, 26.19512, 40.74364, 52.25...","[[164.0224, 178.80228, 198.13016, 217.01288, 2...","[[292.17104, 313.70936, 327.51844, 337.49548, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,zbr117,0502_0_9,79.394028,M,app_ps1,ACad,RSU,0.80,58,"[[0.13359999999999994, 2.3064800000000005, 0.5...","[[0.0866800000000012, 0.03996000000000777, 2.0...","[[0.14320000000003574, 0.08843999999999141, 0....","[164, 204, 160, 996, 472, 2096, 696, 956, 1036...","[128, 408, 740, 712, 384, 448, 448, 512, 348, ...","[88, 148, 192, 164, 116, 132, 144, 88, 68, 40,...","[[1.1194, 147.01576, 163.57912], [380.03596, 4...","[[164.00968, 224.60352, 291.91576], [586.74444...","[[292.08984, 338.95912, 377.49348, 378.05772],..."
59,zbr117,0502_0_9,79.394028,M,app_ps1,ACad,RSU,0.64,59,"[[0.019559999999999998, 0.11959999999999998, 0...","[[0.17011999999999716, 0.02124000000000592, 0....","[[0.16999999999995907, 0.07504000000000133, 0....","[164, 204, 160, 996, 472, 2096, 696, 956, 1036...","[128, 408, 740, 712, 384, 448, 448, 512, 348, ...","[88, 148, 192, 164, 116, 132, 144, 88, 68, 40,...","[[0.01744, 10.94556, 18.83804, 27.91708, 44.18...","[[164.62144, 174.20852, 184.86068, 196.50448, ...","[[292.00456, 302.45684, 314.16624, 324.32024, ..."
60,zbr117,0502_0_9,79.394028,M,app_ps1,ACad,RSU,0.64,60,"[[0.01948, 0.11964, 0.047880000000000006, 0.06...","[[0.7818400000000167, 0.021279999999990196, 0....","[[0.16999999999995907, 0.07499999999998863, 0....","[164, 204, 160, 996, 472, 2096, 696, 956, 1036...","[128, 408, 740, 712, 384, 448, 448, 512, 348, ...","[88, 148, 192, 164, 116, 132, 144, 88, 68, 40,...","[[0.01748, 12.94732, 21.70272, 34.88256, 55.97...","[[164.00972, 175.42708, 187.31712, 201.59896, ...","[[292.00456, 304.35952, 317.6922, 331.94216, 3..."
61,zbr117,0502_0_9,79.394028,M,app_ps1,ACad,RSU,0.56,61,"[[0.49576000000000003, 0.19640000000000002, 0....","[[0.20824000000001774, 0.11635999999998603, 0....","[[0.5597999999999956, 0.06296000000003232, 0.0...","[164, 204, 160, 996, 472, 2096, 696, 956, 1036...","[128, 408, 740, 712, 384, 448, 448, 512, 348, ...","[88, 148, 192, 164, 116, 132, 144, 88, 68, 40,...","[[4e-05, 21.76024, 41.99932, 59.69112, 73.0461...","[[164.00276, 181.97344, 200.65172, 217.14216, ...","[[292.23172, 310.35404, 329.55292, 355.79168, ..."
62,zbr117,0502_0_9,79.394028,M,app_ps1,ACad,RSU,0.52,62,"[[0.38944, 0.5378, 0.60912, 1.6469200000000002...","[[2.6166800000000023, 6.222199999999987, 4.103...","[[1.0842000000000098, 1.5319999999999823, 1.04...","[164, 204, 160, 996, 472, 2096, 696, 956, 1036...","[128, 408, 740, 712, 384, 448, 448, 512, 348, ...","[88, 148, 192, 164, 116, 132, 144, 88, 68, 40,...","[[0.0382, 31.72712, 88.55296, 1.87508, 13.7233...","[[175.00976, 289.15704, 184.90324, 208.25712, ...","[[292.22836, 347.3184, 372.65348, 304.1938, 32..."

got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,zbr117,0529_0_12,106.502338,M,app_ps1,RSPv,RSU,0.68,0,"[[0.11844000000000005, 0.007279999999999953, 0...","[[0.32384000000092783, 0.055319999999483116, 0...","[[0.04215999999905762, 0.002080000000205473, 0...","[452, 244, 520, 1148, 144, 296, 816, 2744, 324...","[448, 312, 132, 160, 176, 796, 168, 144, 320, ...","[24, 44, 24, 28, 112, 20, 44, 20, 36, 12, 40, ...","[[0.31964, 6.94992, 13.9488, 21.04988, 29.5379...","[[9616.3072, 9627.18672, 9636.06336, 9644.3443...","[[10064.01948, 10067.92416, 10071.71652, 10074..."
1,zbr117,0529_0_12,106.502338,M,app_ps1,RSPv,RSU,0.68,1,"[[0.041999999999999996, 0.002680000000000002, ...","[[0.06843999999910011, 0.024400000000241562, 0...","[[0.039319999999861466, 0.013559999999415595, ...","[452, 244, 520, 1148, 144, 296, 816, 2744, 324...","[448, 312, 132, 160, 176, 796, 168, 144, 320, ...","[24, 44, 24, 28, 112, 20, 44, 20, 36, 12, 40, ...","[[0.00368, 3.46964, 7.43884, 11.36072, 15.7852...","[[9616.05212, 9627.6194, 9638.32296, 9648.6187...","[[10064.02704, 10066.1778, 10069.2966, 10072.0..."
2,zbr117,0529_0_12,106.502338,M,app_ps1,RSPv,FS,0.24,2,"[[0.06556000000000001, 0.009599999999999997, 0...","[[0.13515999999981432, 0.06799999999930151, 0....","[[0.9280799999996816, 7.573440000000119, 2.632...","[452, 244, 520, 1148, 144, 296, 816, 2744, 324...","[448, 312, 132, 160, 176, 796, 168, 144, 320, ...","[24, 44, 24, 28, 112, 20, 44, 20, 36, 12, 40, ...","[[0.01852, 12.22992, 24.8228, 38.43448, 48.381...","[[9616.53764, 9633.39968, 9661.47976, 9742.901...","[[10064.93352, 10085.165], [10416.2646, 10442...."
3,zbr117,0529_0_12,106.502338,M,app_ps1,RSPv,RSU,0.60,3,"[[0.05444, 0.007599999999999996, 0.05971999999...","[[0.09931999999935215, 0.035040000000662985, 0...","[[0.003839999999399879, 0.015680000000429573, ...","[452, 244, 520, 1148, 144, 296, 816, 2744, 324...","[448, 312, 132, 160, 176, 796, 168, 144, 320, ...","[24, 44, 24, 28, 112, 20, 44, 20, 36, 12, 40, ...","[[0.11044, 6.6128, 12.28788, 16.59848, 20.4284...","[[9616.004, 9623.10488, 9630.487, 9639.89672, ...","[[10064.00148, 10066.61944, 10068.76064, 10070..."
4,zbr117,0529_0_12,106.502338,M,app_ps1,RSPv,RSU,0.56,4,"[[2.5917200000000005, 1.8066399999999998, 5.91...","[[0.004160000000410946, 0.018199999998614658, ...","[[2.3589200000005803, 2.3813200000004144, 0.78...","[452, 244, 520, 1148, 144, 296, 816, 2744, 324...","[448, 312, 132, 160, 176, 796, 168, 144, 320, ...","[24, 44, 24, 28, 112, 20, 44, 20, 36, 12, 40, ...","[[4.88692, 248.31964, 421.96756, 450.8174], [6...","[[9616.0154, 9624.4292, 9635.56392, 9648.1516,...","[[10069.59176, 10087.68128], [10416.40524, 104..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,zbr117,0529_0_12,106.502338,M,app_ps1,ACad,RSU,0.68,77,"[[0.00432, 0.07275999999999999, 0.014960000000...","[[0.01419999999961874, 0.02292000000124972, 0....","[[0.012560000001030858, 0.03883999999925436, 0...","[452, 244, 520, 1148, 144, 296, 816, 2744, 324...","[448, 312, 132, 160, 176, 796, 168, 144, 320, ...","[24, 44, 24, 28, 112, 20, 44, 20, 36, 12, 40, ...","[[4e-05, 5.52568, 12.47188, 20.18788, 28.43352...","[[9616.01772, 9622.17608, 9629.80976, 9638.013...","[[10064.06008, 10070.02392, 10076.065, 10081.7..."
78,zbr117,0529_0_12,106.502338,M,app_ps1,ACad,RSU,0.64,78,"[[0.7220000000000001, 0.08827999999999991, 1.6...","[[0.07687999999870954, 0.17428000000109023, 0....","[[0.015599999998812564, 0.1995999999999185, 0....","[452, 244, 520, 1148, 144, 296, 816, 2744, 324...","[448, 312, 132, 160, 176, 796, 168, 144, 320, ...","[24, 44, 24, 28, 112, 20, 44, 20, 36, 12, 40, ...","[[0.94812, 18.04368, 41.17948, 51.52876, 69.62...","[[9616.01128, 9641.40804, 9674.6018, 9716.8204...","[[10064.10936, 10080.9284, 10087.97864], [1041..."
79,zbr117,0529_0_12,106.502338,M,app_ps1,ACad,RSU,0.64,79,"[[126.86968, 118.84060000000002, 16.3003999999...","[[1.5774799999999232, 4.465840000000753, 2.446...","[[0.27656000000024505, 0.19023999999990338, 0....","[452, 244, 520, 1148, 144, 296, 816, 2744, 324...","[448, 312, 132, 160, 176, 796, 168, 144, 320, ...","[24, 44, 24, 28, 112, 20, 44, 20, 36, 12, 40, ...","[[94.24448, 447.77936], [691.79752, 755.83912]...","[[9617.846, 9782.06368, 9864.4122, 9973.72756,...","[[10065.62444, 10087.82792], [10419.10128, 104..."
80,zbr117,0529_0_12,106.502338,M,app_ps1,ACad,RSU,0.68,80,"[[0.07511999999999999, 0.04552000000000002, 0....","[[0.9388400000007096, 0.24319999999897846, 0.2...","[[0.061480000000301516, 0.032199999999647844, ...","[452, 244, 520, 1148, 144, 296, 816, 2744, 324...","[448, 312, 132, 160, 176, 796, 168, 144, 320, ...","[24, 44, 24, 28, 112, 20, 44, 20, 36, 12, 40, ...","[[0.01492, 8.93544, 19.8654, 43.08788, 55.0499...","[[9616.1472, 9630.97724, 9643.5024, 9664.19748...","[[10064.14292, 10076.40356, 10087.73268, 10087..."
81,zbr117,0529_0_12,106.502338,M,app_ps1,ACad,RSU,0.92,81,"[[0.26256, 0.66652, 0.3944399999999999, 0.0232...","[[1.539439999998649, 1.1169200000003912, 0.254...","[[0.02635999999984051, 0.16996000000108324, 0....","[452, 244, 520, 1148, 144, 296, 816, 2744, 324...","[448, 312, 132, 160, 176, 796, 168, 144, 320, ...","[24, 44, 24, 28, 112, 20, 44, 20, 36, 12, 40, ...","[[0.86268, 62.60708, 178.064, 261.11976, 355.3...","[[9616.02712, 9650.57976, 9688.03652, 9733.831...","[[10064.90216, 10087.731], [10416.19916, 10453..."

got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,zbr117,0529_12_15,107.002361,M,app_ps1,RSPv,RSU,0.60,0,"[[0.08492, 0.00716, 0.023320000000000007, 0.04...","[[0.04464000000007218, 0.10979999999995016, 0....","[[0.12424000000009983, 0.07827999999994972, 0....","[1136, 1360, 316]","[484, 380, 728, 996, 16, 564, 532, 252, 176, 3...","[84, 84, 64, 56, 152, 136, 40, 136, 32, 100]","[[4e-05, 4.16032, 8.54424, 11.73972, 15.31324,...","[[1136.32244, 1142.41812, 1150.25004, 1158.937...","[[1620.14672, 1627.0552, 1635.6562, 1641.72548..."
1,zbr117,0529_12_15,107.002361,M,app_ps1,RSPv,FS,0.24,1,"[[0.017240000000000005, 0.0034000000000000002,...","[[0.03664000000003398, 0.0028800000000046566, ...","[[0.04088000000001557, 0.013879999999971915, 0...","[1136, 1360, 316]","[484, 380, 728, 996, 16, 564, 532, 252, 176, 3...","[84, 84, 64, 56, 152, 136, 40, 136, 32, 100]","[[0.05312, 2.51352, 5.0606, 8.0686, 10.04376, ...","[[1136.1822, 1139.53552, 1144.77012, 1150.1944...","[[1620.02768, 1623.20332, 1627.52712, 1631.027..."
2,zbr117,0529_12_15,107.002361,M,app_ps1,RSPv,RSU,0.52,2,"[[0.06132, 0.1702, 0.009360000000000007, 0.287...","[[0.028279999999995198, 0.18864000000007763, 0...","[[0.443559999999934, 0.5307200000002013, 0.877...","[1136, 1360, 316]","[484, 380, 728, 996, 16, 564, 532, 252, 176, 3...","[84, 84, 64, 56, 152, 136, 40, 136, 32, 100]","[[4e-05, 25.45088, 49.66632, 74.82348, 101.613...","[[1136.21028, 1169.50796, 1205.85044, 1243.735...","[[1622.36664, 1674.05604, 1701.8782], [2104.20..."
3,zbr117,0529_12_15,107.002361,M,app_ps1,RSPv,FS,0.36,3,"[[0.31971999999999995, 0.31504, 0.49488, 0.763...","[[1.302199999999857, 0.21136000000001332, 0.01...","[[0.16247999999995955, 0.11372000000005755, 0....","[1136, 1360, 316]","[484, 380, 728, 996, 16, 564, 532, 252, 176, 3...","[84, 84, 64, 56, 152, 136, 40, 136, 32, 100]","[[0.26528, 37.368, 75.9978, 121.95004, 173.303...","[[1136.19448, 1211.44724, 1289.38372, 1356.676...","[[1620.10896, 1691.50976, 1702.57896], [2104.4..."
4,zbr117,0529_12_15,107.002361,M,app_ps1,RSPv,FS,0.12,4,"[[1.0964799999999997, 5.74268, 4.1926400000000...","[[3.879040000000032, 8.974199999999882, 14.112...","[[9.702600000000075, 7.064879999999903, 20.817...","[1136, 1360, 316]","[484, 380, 728, 996, 16, 564, 532, 252, 176, 3...","[84, 84, 64, 56, 152, 136, 40, 136, 32, 100]","[[4.20228, 290.17184, 395.37472, 421.10948, 44...","[[1153.43236, 1582.1492], [1734.07952, 1808.01...","[[1630.12104, 1673.703], [2104.0702, 2114.5558..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,zbr117,0529_12_15,107.002361,M,app_ps1,ACad,RSU,0.72,92,"[[0.9837600000000002, 0.57016, 0.1835599999999...","[[1.7028000000000247, 0.05691999999999098, 0.9...","[[1.9623599999999897, 7.474519999999984, 0.049...","[1136, 1360, 316]","[484, 380, 728, 996, 16, 564, 532, 252, 176, 3...","[84, 84, 64, 56, 152, 136, 40, 136, 32, 100]","[[2.13232, 24.14292, 87.71192, 128.65964, 158....","[[1137.19768, 1269.92032, 1412.37408, 1543.465...","[[1620.70452, 1699.396], [2121.48304, 2185.891..."
93,zbr117,0529_12_15,107.002361,M,app_ps1,ACad,RSU,0.72,93,"[[0.07796, 0.03608, 0.008680000000000007, 0.02...","[[0.13575999999989108, 0.4031999999999698, 0.0...","[[0.02592000000004191, 0.16664000000014312, 0....","[1136, 1360, 316]","[484, 380, 728, 996, 16, 564, 532, 252, 176, 3...","[84, 84, 64, 56, 152, 136, 40, 136, 32, 100]","[[0.00348, 2.61216, 5.31856, 9.37448, 16.99816...","[[1136.02788, 1145.47224, 1153.171, 1160.59532...","[[1620.00264, 1628.15608, 1634.83356, 1642.006..."
94,zbr117,0529_12_15,107.002361,M,app_ps1,ACad,RSU,0.64,94,"[[0.002119999999999997, 0.08848, 0.04891999999...","[[0.005879999999933716, 0.13732000000004518, 0...","[[0.9290000000000873, 0.6071199999998953, 0.17...","[1136, 1360, 316]","[484, 380, 728, 996, 16, 564, 532, 252, 176, 3...","[84, 84, 64, 56, 152, 136, 40, 136, 32, 100]","[[0.0376, 4.63996, 20.00124, 28.91804, 47.4401...","[[1136.42148, 1188.34648, 1238.53084, 1291.955...","[[1620.80208, 1641.53216, 1653.34276, 1678.358..."
95,zbr117,0529_12_15,107.002361,M,app_ps1,ACad,RSU,0.64,95,"[[0.09304, 0.12119999999999999, 0.060200000000...","[[0.28119999999989886, 0.23516000000017812, 0....","[[0.1613199999999324, 0.10028000000011161, 0.0...","[1136, 1360, 316]","[484, 380, 728, 996, 16, 564, 532, 252, 176, 3...","[84, 84, 64, 56, 152, 136, 40, 136, 32, 100]","[[0.01932, 5.19012, 19.09044, 26.65432, 39.411...","[[1136.15804, 1164.78456, 1192.26396, 1221.863...","[[1620.01548, 1636.2046, 1650.52852, 1658.1730..."
96,zbr117,0529_12_15,107.002361,M,app_ps1,ACad,RSU,0.64,96,"[[0.08256000000000001, 0.14376, 0.083080000000...","[[0.463799999999992, 0.4774800000000141, 0.080...","[[0.3303599999999278, 0.03152000000000044, 0.0...","[1136, 1360, 316]","[484, 380, 728, 996, 16, 564, 532, 252, 176, 3...","[84, 84, 64, 56, 152, 136, 40, 136, 32, 100]","[[0.01988, 13.2776, 24.4698, 49.92556, 67.4586...","[[1136.65944, 1166.96224, 1201.64916, 1240.916...","[[1620.04356, 1638.16604, 1646.09456, 1652.491..."

Working on zbr118
Has 2 files to go through
got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,zbr118,0522_0_12,99.320162,F,app_ps1,RSPv,RSU,0.64,0,"[[0.08432, 0.41892, 0.07347999999999999, 0.071...","[[0.011120000000005348, 0.0018000000000029104,...","[[0.0037999999999556167, 0.008280000000013388,...","[916, 1528, 1380, 8360, 2048, 52, 148]","[720, 588, 572, 632, 480, 12, 28, 60, 32, 36, ...","[132, 124, 168, 44, 52, 456, 380, 516, 136, 41...","[[0.18296, 11.41436, 18.14864, 23.22504, 27.20...","[[916.02796, 925.137, 941.23444, 952.20608, 96...","[[1636.08204, 1647.15192, 1659.24732, 1671.540..."
1,zbr118,0522_0_12,99.320162,F,app_ps1,RSPv,RSU,0.60,1,"[[0.413, 0.023560000000000025, 0.2879999999999...","[[0.20820000000003347, 1.6651999999999134, 0.3...","[[0.05343999999990956, 0.7204000000001543, 0.5...","[916, 1528, 1380, 8360, 2048, 52, 148]","[720, 588, 572, 632, 480, 12, 28, 60, 32, 36, ...","[132, 124, 168, 44, 52, 456, 380, 516, 136, 41...","[[0.10376, 16.82, 49.34928, 61.56364, 74.9722,...","[[916.3442, 957.0082, 995.85856, 1030.51748, 1...","[[1636.0888, 1693.88064, 1767.59248], [2386.14..."
2,zbr118,0522_0_12,99.320162,F,app_ps1,RSPv,RSU,0.68,2,"[[1.18384, 3.2226800000000004, 0.1009199999999...","[[5.4051600000000235, 0.9064799999999877, 7.07...","[[6.5668799999998555, 0.27084000000013475, 26....","[916, 1528, 1380, 8360, 2048, 52, 148]","[720, 588, 572, 632, 480, 12, 28, 60, 32, 36, ...","[132, 124, 168, 44, 52, 456, 380, 516, 136, 41...","[[5.30968, 122.8908, 127.05192, 130.83504, 218...","[[930.03412, 1292.3246, 1623.63316], [1829.379...","[[1639.67956, 1755.40256], [2413.08708, 2500.1..."
3,zbr118,0522_0_12,99.320162,F,app_ps1,RSPv,RSU,0.52,3,"[[2.67304, 1.5431600000000003, 3.8971999999999...","[[2.535480000000007, 2.662879999999973, 0.0256...","[[0.01731999999992695, 0.04448000000002139, 0....","[916, 1528, 1380, 8360, 2048, 52, 148]","[720, 588, 572, 632, 480, 12, 28, 60, 32, 36, ...","[132, 124, 168, 44, 52, 456, 380, 516, 136, 41...","[[0.55524, 126.26488, 130.29296, 351.61072, 52...","[[916.85276, 1317.79836, 1632.69552], [1797.86...","[[1642.69016, 1688.26012, 1746.63724, 1766.106..."
4,zbr118,0522_0_12,99.320162,F,app_ps1,RSPv,RSU,0.88,4,"[[0.39476, 0.16655999999999993, 0.226200000000...","[[0.04272000000003118, 0.017519999999990432, 0...","[[2.971320000000105, 0.11179999999990287, 0.81...","[916, 1528, 1380, 8360, 2048, 52, 148]","[720, 588, 572, 632, 480, 12, 28, 60, 32, 36, ...","[132, 124, 168, 44, 52, 456, 380, 516, 136, 41...","[[0.52784, 26.69704, 58.34396, 73.4134, 123.66...","[[916.33488, 941.97168, 996.32944, 1045.71104,...","[[1636.598, 1704.37624, 1766.69692], [2384.135..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,zbr118,0522_0_12,99.320162,F,app_ps1,ACad,RSU,0.48,113,"[[1.5680399999999999, 0.9739200000000006, 0.91...","[[0.14264000000002852, 0.66895999999997, 3.221...","[[0.08992000000012013, 3.589079999999967, 0.03...","[916, 1528, 1380, 8360, 2048, 52, 148]","[720, 588, 572, 632, 480, 12, 28, 60, 32, 36, ...","[132, 124, 168, 44, 52, 456, 380, 516, 136, 41...","[[1.51952, 125.55892, 170.87808, 265.83416, 39...","[[920.90652, 1075.18936, 1322.15028, 1589.9048...","[[1636.58596, 1766.795], [2385.4028, 2506.653]..."
114,zbr118,0522_0_12,99.320162,F,app_ps1,ACad,RSU,0.68,114,"[[0.1411199999999999, 0.06471999999999989, 0.0...","[[0.04988000000003012, 0.0055599999999458305, ...","[[0.03460000000018226, 0.029679999999871143, 0...","[916, 1528, 1380, 8360, 2048, 52, 148]","[720, 588, 572, 632, 480, 12, 28, 60, 32, 36, ...","[132, 124, 168, 44, 52, 456, 380, 516, 136, 41...","[[3.33128, 20.27004, 43.97152, 59.85504, 134.1...","[[917.27972, 966.98932, 1001.74416, 1038.07748...","[[1636.78768, 1699.97676, 1741.61528, 1766.810..."
115,zbr118,0522_0_12,99.320162,F,app_ps1,ACad,RSU,0.64,115,"[[0.0016399999999999997, 0.11212, 0.00852, 0.0...","[[0.11691999999993641, 0.22256000000004406, 0....","[[0.38883999999984553, 0.1369200000001456, 0.0...","[916, 1528, 1380, 8360, 2048, 52, 148]","[720, 588, 572, 632, 480, 12, 28, 60, 32, 36, ...","[132, 124, 168, 44, 52, 456, 380, 516, 136, 41...","[[0.00144, 6.07736, 12.05304, 15.06136, 18.666...","[[916.24084, 922.91112, 930.33824, 940.14988, ...","[[1636.15496, 1644.49112, 1652.902, 1663.43976..."
116,zbr118,0522_0_12,99.320162,F,app_ps1,ACad,RSU,0.60,116,"[[0.126, 1.15416, 0.1890400000000001, 0.113519...","[[0.2336800000000494, 1.4023999999999432, 0.43...","[[0.22260000000005675, 0.870679999999993, 0.63...","[916, 1528, 1380, 8360, 2048, 52, 148]","[720, 588, 572, 632, 480, 12, 28, 60, 32, 36, ...","[132, 124, 168, 44, 52, 456, 380, 516, 136, 41...","[[0.07792, 48.42892, 71.63188, 155.87148, 217....","[[916.46336, 984.4658, 1053.10396, 1150.80572,...","[[1636.37732, 1698.71024, 1752.7772, 1767.6104..."
117,zbr118,0522_0_12,99.320162,F,app_ps1,ACad,RSU,0.68,117,"[[0.33152000000000004, 0.16928000000000004, 0....","[[0.20208000000002357, 0.1349599999999782, 0.1...","[[0.07292000000006738, 0.016560000000026776, 1...","[916, 1528, 1380, 8360, 2048, 52, 148]","[720, 588, 572, 632, 480, 12, 28, 60, 32, 36, ...","[132, 124, 168, 44, 52, 456, 380, 516, 136, 41...","[[0.07796, 18.758, 44.29352, 48.76832, 56.3508...","[[916.12636, 939.47504, 960.88768, 986.6584, 1...","[[1636.07412, 1669.10356, 1693.94188, 1716.449..."

got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,zbr118,0522_12_24,99.820174,F,app_ps1,RSPv,RSU,0.56,0,"[[0.0982, 0.23284000000000002, 0.30824, 0.0221...","[[0.004680000000007567, 0.2276799999999639, 0....","[[0.006440000000111468, 0.022400000000288856, ...","[1760, 468, 4732, 3860, 1152, 1452, 592, 2416]","[368, 544, 688, 224, 300, 372, 460, 240, 336, ...","[28, 24, 100, 196, 48, 28, 128, 168, 144, 80, ...","[[0.05136, 17.45952, 32.5078, 40.123, 47.41208...","[[1760.34788, 1766.63196, 1774.9492, 1783.1351...","[[2128.4556, 2139.60896, 2151.22404, 2155.7842..."
1,zbr118,0522_12_24,99.820174,F,app_ps1,RSPv,RSU,0.56,1,"[[0.029079999999999995, 0.03420000000000001, 0...","[[0.2925199999999677, 0.05988000000002103, 0.1...","[[0.007480000000214204, 0.032079999999950815, ...","[1760, 468, 4732, 3860, 1152, 1452, 592, 2416]","[368, 544, 688, 224, 300, 372, 460, 240, 336, ...","[28, 24, 100, 196, 48, 28, 128, 168, 144, 80, ...","[[0.00608, 8.41496, 14.96536, 23.75836, 29.681...","[[1760.05692, 1771.49288, 1788.27728, 1804.423...","[[2128.4982, 2154.18732, 2155.85188], [2720.22..."
2,zbr118,0522_12_24,99.820174,F,app_ps1,RSPv,RSU,0.60,2,"[[0.10364000000000001, 0.22619999999999996, 0....","[[0.32387999999991735, 0.21188000000006468, 0....","[[0.036639999999806605, 0.7612400000002708, 0....","[1760, 468, 4732, 3860, 1152, 1452, 592, 2416]","[368, 544, 688, 224, 300, 372, 460, 240, 336, ...","[28, 24, 100, 196, 48, 28, 128, 168, 144, 80, ...","[[0.21732, 18.434, 42.15224, 59.69088, 80.1248...","[[1760.075, 1775.97936, 1795.42516, 1821.63896...","[[2128.46416, 2155.45052], [2720.25076, 2742.2..."
3,zbr118,0522_12_24,99.820174,F,app_ps1,RSPv,RSU,0.68,3,"[[0.36832, 0.10531999999999997, 0.384040000000...","[[0.35732000000007247, 0.19704000000001543, 3....","[[0.7846799999997529, 0.8704400000001442, 0.01...","[1760, 468, 4732, 3860, 1152, 1452, 592, 2416]","[368, 544, 688, 224, 300, 372, 460, 240, 336, ...","[28, 24, 100, 196, 48, 28, 128, 168, 144, 80, ...","[[0.0796, 47.53672, 101.36564, 149.89104, 221....","[[1760.5924, 1902.40932, 2014.29272, 2125.3586...","[[2129.27208, 2155.50676], [2720.45356, 2743.7..."
4,zbr118,0522_12_24,99.820174,F,app_ps1,RSPv,RSU,0.40,4,"[[0.011560000000000015, 0.20800000000000002, 0...","[[0.004439999999931388, 0.008080000000063592, ...","[[0.006440000000111468, 0.001720000000204891, ...","[1760, 468, 4732, 3860, 1152, 1452, 592, 2416]","[368, 544, 688, 224, 300, 372, 460, 240, 336, ...","[28, 24, 100, 196, 48, 28, 128, 168, 144, 80, ...","[[0.43632, 8.47276, 16.25968, 25.53688, 33.212...","[[1760.03864, 1765.6224, 1770.20344, 1776.8010...","[[2128.49032, 2136.46312, 2149.0788, 2155.9779..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,zbr118,0522_12_24,99.820174,F,app_ps1,ACad,RSU,0.68,136,"[[0.07064000000000001, 0.017559999999999992, 0...","[[0.011640000000170403, 0.03251999999997679, 0...","[[0.018520000000080472, 0.12463999999999942, 0...","[1760, 468, 4732, 3860, 1152, 1452, 592, 2416]","[368, 544, 688, 224, 300, 372, 460, 240, 336, ...","[28, 24, 100, 196, 48, 28, 128, 168, 144, 80, ...","[[0.08404, 4.33008, 8.89116, 15.96688, 22.2552...","[[1760.03336, 1766.49684, 1770.86116, 1776.146...","[[2128.45424, 2135.529, 2141.8692, 2148.88108,..."
137,zbr118,0522_12_24,99.820174,F,app_ps1,ACad,RSU,0.68,137,"[[0.047479999999999994, 0.033680000000000015, ...","[[0.02539999999999054, 0.20875999999998385, 0....","[[0.01448000000027605, 0.0445199999999204, 0.0...","[1760, 468, 4732, 3860, 1152, 1452, 592, 2416]","[368, 544, 688, 224, 300, 372, 460, 240, 336, ...","[28, 24, 100, 196, 48, 28, 128, 168, 144, 80, ...","[[0.1124, 8.5692, 16.18752, 22.16252, 30.20656...","[[1760.40012, 1771.5436, 1781.58704, 1794.1637...","[[2128.0226, 2139.62116, 2155.14856, 2155.9493..."
138,zbr118,0522_12_24,99.820174,F,app_ps1,ACad,RSU,0.60,138,"[[0.08696000000000004, 0.11591999999999997, 0....","[[0.01251999999999498, 0.020440000000007785, 0...","[[0.09547999999995227, 0.0725600000000668, 0.0...","[1760, 468, 4732, 3860, 1152, 1452, 592, 2416]","[368, 544, 688, 224, 300, 372, 460, 240, 336, ...","[28, 24, 100, 196, 48, 28, 128, 168, 144, 80, ...","[[0.301, 12.31968, 19.30576, 28.48172, 37.1444...","[[1760.02648, 1799.93384, 1849.15408, 1887.725...","[[2128.03544, 2154.67828], [2720.54728, 2743.9..."
139,zbr118,0522_12_24,99.820174,F,app_ps1,ACad,RSU,0.92,139,"[[0.0398, 1.39412, 0.018160000000000176, 0.068...","[[0.12192000000004555, 0.5996399999999085, 0.1...","[[0.008479999999963184, 0.1649600000000646, 0....","[1760, 468, 4732, 3860, 1152, 1452, 592, 2416]","[368, 544, 688, 224, 300, 372, 460, 240, 336, ...","[28, 24, 100, 196, 48, 28, 128, 168, 144, 80, ...","[[0.28956, 32.77276, 40.91604, 67.36596, 79.12...","[[1761.0188, 1800.30376, 1841.33884, 1880.3098...","[[2128.22264, 2154.65772], [2721.8226, 2743.73..."
140,zbr118,0522_12_24,99.820174,F,app_ps1,ACad,RSU,0.64,140,"[[0.04624, 0.07144, 0.05779999999999999, 0.057...","[[0.0065600000000358705, 0.06175999999982196, ...","[[0.027919999999994616, 0.17459999999982756, 0...","[1760, 468, 4732, 3860, 1152, 1452, 592, 2416]","[368, 544, 688, 224, 300, 372, 460, 240, 336, ...","[28, 24, 100, 196, 48, 28, 128, 168, 144, 80, ...","[[0.028, 7.35728, 13.71124, 20.80468, 31.01736...","[[1760.01016, 1765.37532, 1772.37824, 1780.384...","[[2128.12048, 2136.97232, 2145.18764, 2155.989..."

Working on zbr119
Has 4 files to go through
got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,zbr119,0604_0_12,112.231898,M,app_ps1,RSPv,RSU,0.64,0,"[[0.07615999999999999, 1.3803999999999998, 0.0...","[[18.77059999999983, 3.698920000000271], [0.28...","[[0.1835999999998421, 0.23624000000017986, 0.3...","[3600, 3052, 464, 332, 1796, 3604, 948, 2016, ...","[36, 192, 560, 448, 336, 540, 64, 588, 800, 36...","[132, 1280, 92, 44, 68, 44, 60, 124, 76, 192, ...","[[0.108, 27.37084, 61.6494, 107.2106, 145.741,...","[[3748.74584, 3771.21536], [4308.64628, 4363.2...","[[3600.02592, 3631.93632, 3659.59068, 3689.837..."
1,zbr119,0604_0_12,112.231898,M,app_ps1,RSPv,RSU,0.52,1,"[[0.1117199999999996, 2.2105200000000003, 6.08...","[[0.07156000000031781, 0.10811999999987165, 0....","[[0.021279999999933352, 0.12924000000020897, 0...","[3600, 3052, 464, 332, 1796, 3604, 948, 2016, ...","[36, 192, 560, 448, 336, 540, 64, 588, 800, 36...","[132, 1280, 92, 44, 68, 44, 60, 124, 76, 192, ...","[[2.59724, 107.01148, 211.56044, 302.33812, 37...","[[3748.15912, 3761.07092, 3778.45532, 3783.934...","[[3600.07148, 3608.1076, 3617.26148, 3625.1307..."
2,zbr119,0604_0_12,112.231898,M,app_ps1,RSPv,RSU,0.56,2,"[[0.01656, 0.03108, 0.09976000000000002, 0.030...","[[0.09979999999995925, 0.024959999999737192, 0...","[[0.032479999999850406, 0.0014000000001033186,...","[3600, 3052, 464, 332, 1796, 3604, 948, 2016, ...","[36, 192, 560, 448, 336, 540, 64, 588, 800, 36...","[132, 1280, 92, 44, 68, 44, 60, 124, 76, 192, ...","[[0.0128, 2.70752, 5.91704, 8.62104, 11.8068, ...","[[3748.02356, 3753.16568, 3758.77024, 3766.540...","[[3600.0202, 3603.42264, 3605.68716, 3608.583,..."
3,zbr119,0604_0_12,112.231898,M,app_ps1,RSPv,RSU,0.64,3,"[[11.81988, 4.678799999999999, 8.80744, 3.8600...","[[0.04304000000001906, 0.04839999999967404, 1....","[[0.3145199999999022, 1.1826399999999921, 0.24...","[3600, 3052, 464, 332, 1796, 3604, 948, 2016, ...","[36, 192, 560, 448, 336, 540, 64, 588, 800, 36...","[132, 1280, 92, 44, 68, 44, 60, 124, 76, 192, ...","[[1.44448, 389.40184, 607.03556, 796.89164, 10...","[[3748.47092, 3783.52124], [4308.36888, 4342.8...","[[3600.13524, 3629.4464, 3653.91904, 3676.1835..."
4,zbr119,0604_0_12,112.231898,M,app_ps1,RSPv,RSU,0.60,4,"[[2.5843999999999987, 9.25872, 7.3455599999999...","[[2.681999999999789, 0.3790800000001582, 1.257...","[[0.3952399999998306, 0.2238800000000083, 0.72...","[3600, 3052, 464, 332, 1796, 3604, 948, 2016, ...","[36, 192, 560, 448, 336, 540, 64, 588, 800, 36...","[132, 1280, 92, 44, 68, 44, 60, 124, 76, 192, ...","[[6.10012, 442.93108, 670.9996, 928.27612, 122...","[[3748.37008, 3783.49724], [4308.0076, 4342.63...","[[3600.04588, 3625.57856, 3642.763, 3661.84572..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,zbr119,0604_0_12,112.231898,M,app_ps1,ACad,RSU,0.60,79,"[[0.15112, 0.0902, 0.34068000000000004, 0.0259...","[[0.5562399999998888, 0.5749599999999191, 0.02...","[[0.10835999999972046, 0.07644000000027518, 0....","[3600, 3052, 464, 332, 1796, 3604, 948, 2016, ...","[36, 192, 560, 448, 336, 540, 64, 588, 800, 36...","[132, 1280, 92, 44, 68, 44, 60, 124, 76, 192, ...","[[0.19924, 15.29228, 31.60516, 46.6358, 60.470...","[[3748.13632, 3775.4898, 3777.78352], [4308.15...","[[3600.09288, 3627.78808, 3649.97308, 3686.590..."
80,zbr119,0604_0_12,112.231898,M,app_ps1,ACad,RSU,0.56,80,"[[0.013039999999999996, 0.25992000000000004, 0...","[[0.03944000000001324, 0.07047999999986132, 0....","[[0.14288000000033207, 1.3873999999996158, 0.3...","[3600, 3052, 464, 332, 1796, 3604, 948, 2016, ...","[36, 192, 560, 448, 336, 540, 64, 588, 800, 36...","[132, 1280, 92, 44, 68, 44, 60, 124, 76, 192, ...","[[0.16184, 19.28956, 52.44908, 83.86236, 105.9...","[[3748.3544, 3776.90992], [4308.6812, 4392.940...","[[3600.02924, 3627.78428, 3671.82224, 3731.586..."
81,zbr119,0604_0_12,112.231898,M,app_ps1,ACad,RSU,0.52,81,"[[0.029719999999999996, 0.07887999999999999, 0...","[[0.08948000000009415, 0.05004000000008091, 0....","[[0.12864000000035958, 0.12655999999969936, 0....","[3600, 3052, 464, 332, 1796, 3604, 948, 2016, ...","[36, 192, 560, 448, 336, 540, 64, 588, 800, 36...","[132, 1280, 92, 44, 68, 44, 60, 124, 76, 192, ...","[[0.09024, 7.0476, 14.6184, 22.26108, 29.52908...","[[3748.03332, 3753.59144, 3760.2862, 3776.3809...","[[3600.0876, 3608.17504, 3616.7816, 3623.50808..."
82,zbr119,0604_0_12,112.231898,M,app_ps1,ACad,RSU,0.52,82,"[[0.029719999999999996, 0.07887999999999999, 0...","[[0.08948000000009415, 0.05004000000008091, 0....","[[0.12864000000035958, 0.12655999999969936, 0....","[3600, 3052, 464, 332, 1796, 3604, 948, 2016, ...","[36, 192, 560, 448, 336, 540, 64, 588, 800, 36...","[132, 1280, 92, 44, 68, 44, 60, 124, 76, 192, ...","[[0.09024, 7.0476, 14.6184, 22.26108, 29.52908...","[[3748.03332, 3753.59144, 3760.2862, 3776.3809...","[[3600.0876, 3608.17504, 3616.7816, 3623.50808..."
83,zbr119,0604_0_12,112.231898,M,app_ps1,ACad,RSU,0.56,83,"[[0.21691999999999997, 0.53688, 0.084559999999...","[[1.231239999999616, 0.3581600000002254, 0.075...","[[0.09936000000016065, 0.129359999999906, 0.08...","[3600, 3052, 464, 332, 1796, 3604, 948, 2016, ...","[36, 192, 560, 448, 336, 540, 64, 588, 800, 36...","[132, 1280, 92, 44, 68, 44, 60, 124, 76, 192, ...","[[0.21512, 13.83772, 29.537, 44.81448, 58.6077...","[[3752.65572, 3773.71788, 3773.8426], [4308.14...","[[3600.09544, 3613.59048, 3623.27788, 3630.399..."

got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,zbr119,0604_12_19,112.731921,M,app_ps1,RSPv,FS,0.28,0,"[[0.22184, 0.8497199999999999, 0.3140400000000...","[[0.026759999999967476, 0.014040000000022701, ...","[[0.09555999999975029, 0.09548000000040702, 0....","[1932, 4032, 768, 3808]","[312, 556, 1216, 64, 340, 280, 288, 532, 320, ...","[52, 128, 24, 40, 56, 56, 64, 28, 72, 152, 12,...","[[0.00028, 21.21772, 34.0094, 45.72924, 59.611...","[[1932.06412, 1956.76348, 2001.79788, 2039.244...","[[2244.03456, 2254.69552, 2264.42352, 2271.239..."
1,zbr119,0604_12_19,112.731921,M,app_ps1,RSPv,FS,0.16,1,"[[0.16596, 0.04872000000000004, 0.063599999999...","[[0.011040000000093642, 0.028319999999894208, ...","[[0.1107200000001285, 0.07888000000002648, 0.0...","[1932, 4032, 768, 3808]","[312, 556, 1216, 64, 340, 280, 288, 532, 320, ...","[52, 128, 24, 40, 56, 56, 64, 28, 72, 152, 12,...","[[0.10356, 6.28064, 18.66264, 27.31376, 33.814...","[[1932.00892, 1934.80204, 1940.7782, 1950.5172...","[[2244.13688, 2248.36872, 2250.43684, 2251.657..."
2,zbr119,0604_12_19,112.731921,M,app_ps1,RSPv,RSU,0.60,2,"[[0.07776, 0.008480000000000001, 0.08764, 0.00...","[[0.027879999999868232, 0.01251999999999498, 0...","[[0.01672000000007756, 0.01999999999998181, 0....","[1932, 4032, 768, 3808]","[312, 556, 1216, 64, 340, 280, 288, 532, 320, ...","[52, 128, 24, 40, 56, 56, 64, 28, 72, 152, 12,...","[[0.02416, 3.77592, 7.94804, 11.6632, 16.13876...","[[1932.02716, 1935.75148, 1939.92924, 1944.938...","[[2244.00412, 2248.46076, 2251.58772, 2255.757..."
3,zbr119,0604_12_19,112.731921,M,app_ps1,RSPv,RSU,0.72,3,"[[0.16907999999999998, 0.04672000000000001, 0....","[[0.2763599999998405, 0.09951999999998407, 0.1...","[[0.021519999999782158, 0.07264000000031956, 0...","[1932, 4032, 768, 3808]","[312, 556, 1216, 64, 340, 280, 288, 532, 320, ...","[52, 128, 24, 40, 56, 56, 64, 28, 72, 152, 12,...","[[4e-05, 18.70372, 36.50412, 50.82724, 67.7298...","[[1932.13452, 1943.80172, 1956.53468, 1969.765...","[[2244.02684, 2252.18456, 2260.50848, 2266.107..."
4,zbr119,0604_12_19,112.731921,M,app_ps1,RSPv,RSU,0.60,4,"[[0.08380000000000001, 0.07671999999999998, 0....","[[0.21023999999988519, 0.006720000000086657, 0...","[[0.08431999999993423, 0.044800000000122964, 0...","[1932, 4032, 768, 3808]","[312, 556, 1216, 64, 340, 280, 288, 532, 320, ...","[52, 128, 24, 40, 56, 56, 64, 28, 72, 152, 12,...","[[0.08248, 5.4564, 11.79948, 17.99952, 23.7104...","[[1932.1112, 1936.15068, 1942.31528, 1949.1901...","[[2244.02304, 2250.5952, 2259.27396, 2265.2855..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,zbr119,0604_12_19,112.731921,M,app_ps1,ACad,RSU,0.64,140,"[[0.02512, 0.0678, 0.016319999999999987, 0.041...","[[0.02060000000005857, 0.3269199999999728, 0.0...","[[0.24675999999999476, 0.007360000000062428, 0...","[1932, 4032, 768, 3808]","[312, 556, 1216, 64, 340, 280, 288, 532, 320, ...","[52, 128, 24, 40, 56, 56, 64, 28, 72, 152, 12,...","[[0.00364, 4.36296, 8.8312, 14.79744, 20.16312...","[[1932.30116, 1941.29252, 1948.8344, 1960.5947...","[[2244.09284, 2253.62528, 2263.2926, 2271.3505..."
141,zbr119,0604_12_19,112.731921,M,app_ps1,ACad,RSU,0.56,141,"[[0.06051999999999999, 0.12727999999999998, 0....","[[0.8766399999999521, 0.12100000000009459, 0.6...","[[0.004879999999957363, 0.7638400000000729, 1....","[1932, 4032, 768, 3808]","[312, 556, 1216, 64, 340, 280, 288, 532, 320, ...","[52, 128, 24, 40, 56, 56, 64, 28, 72, 152, 12,...","[[0.07272, 12.34876, 24.59176, 42.07696, 58.10...","[[1932.20432, 1949.65452, 1973.50132, 1999.441...","[[2244.06108, 2270.819, 2289.5896, 2295.99748]..."
142,zbr119,0604_12_19,112.731921,M,app_ps1,ACad,RSU,0.56,142,"[[0.47759999999999997, 1.08968, 0.766039999999...","[[0.7627600000000712, 0.16452000000003864, 3.9...","[[1.1467999999999847, 3.6312000000002627, 2.69...","[1932, 4032, 768, 3808]","[312, 556, 1216, 64, 340, 280, 288, 532, 320, ...","[52, 128, 24, 40, 56, 56, 64, 28, 72, 152, 12,...","[[0.11264, 81.2856, 156.05232, 229.53504, 308....","[[1933.1632, 2140.772, 2243.40224], [2324.3608...","[[2244.75348, 2295.13992], [2881.17952, 3007.3..."
143,zbr119,0604_12_19,112.731921,M,app_ps1,ACad,RSU,0.56,143,"[[6.930840000000001, 0.5605999999999991, 1.194...","[[9.142640000000029, 1.2529199999999037, 1.820...","[[4.741120000000137, 8.670639999999821, 16.283...","[1932, 4032, 768, 3808]","[312, 556, 1216, 64, 340, 280, 288, 532, 320, ...","[52, 128, 24, 40, 56, 56, 64, 28, 72, 152, 12,...","[[7.64568, 486.61852, 968.35868, 1456.36472, 1...","[[1938.51816, 2238.14756], [2326.57272, 2853.4...","[[2244.89104, 2279.65724], [2900.21076, 2986.0..."
144,zbr119,0604_12_19,112.731921,M,app_ps1,ACad,RSU,0.68,144,"[[0.02164, 0.038599999999999995, 0.12524000000...","[[0.10800000000017462, 0.10695999999984451, 0....","[[0.0403599999999642, 0.02687999999989188, 0.0...","[1932, 4032, 768, 3808]","[312, 556, 1216, 64, 340, 280, 288, 532, 320, ...","[52, 128, 24, 40, 56, 56, 64, 28, 72, 152, 12,...","[[0.0496, 6.3604, 13.2984, 19.52976, 26.89588,...","[[1932.00896, 1940.41984, 1947.29808, 1955.498...","[[2244.04504, 2253.5362, 2262.86184, 2270.1927..."

got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,zbr119,0625_0_12,133.166146,M,app_ps1,RSPv,RSU,0.56,0,"[[0.05380000000000001, 0.03132, 0.05144, 0.055...","[[0.09092000000055123, 0.02475999999933265, 0....","[[0.37136000000100466, 0.10203999999976077, 1....","[6252, 800, 404, 164, 800, 224, 2492, 568, 404...","[880, 452, 436, 760, 452, 660, 880, 168, 356, ...","[100, 176, 12, 72, 100, 76, 156, 196, 36, 36, ...","[[0.01248, 8.19332, 15.66092, 23.91148, 29.263...","[[7888.12332, 7899.19512, 7916.43104, 7929.368...","[[8768.19752, 8788.05568, 8800.13424, 8810.324..."
1,zbr119,0625_0_12,133.166146,M,app_ps1,RSPv,RSU,0.60,1,"[[0.15904000000000001, 0.08903999999999998, 0....","[[0.054919999999583524, 0.11247999999977765, 0...","[[0.39879999999902793, 0.01728000000002794, 0....","[6252, 800, 404, 164, 800, 224, 2492, 568, 404...","[880, 452, 436, 760, 452, 660, 880, 168, 356, ...","[100, 176, 12, 72, 100, 76, 156, 196, 36, 36, ...","[[0.0552, 9.92268, 16.4808, 26.9638, 34.7422, ...","[[7888.27576, 7897.64528, 7911.03848, 7921.805...","[[8768.17524, 8781.51988, 8788.30488, 8798.628..."
2,zbr119,0625_0_12,133.166146,M,app_ps1,RSPv,RSU,0.60,2,"[[0.08375999999999999, 0.11504, 0.043999999999...","[[0.09940000000005966, 0.05367999999998574, 0....","[[0.0030800000004092, 0.3999199999998382, 0.00...","[6252, 800, 404, 164, 800, 224, 2492, 568, 404...","[880, 452, 436, 760, 452, 660, 880, 168, 356, ...","[100, 176, 12, 72, 100, 76, 156, 196, 36, 36, ...","[[0.06568, 2.914, 6.72452, 11.31248, 17.17096,...","[[7888.03748, 7894.82352, 7899.76104, 7906.038...","[[8768.16164, 8776.53304, 8784.22964, 8790.675..."
3,zbr119,0625_0_12,133.166146,M,app_ps1,RSPv,RSU,0.52,3,"[[0.032920000000000005, 0.04891999999999999, 0...","[[0.5117600000003222, 0.06715999999960331, 0.1...","[[0.0965200000009645, 0.08527999999932945, 0.1...","[6252, 800, 404, 164, 800, 224, 2492, 568, 404...","[880, 452, 436, 760, 452, 660, 880, 168, 356, ...","[100, 176, 12, 72, 100, 76, 156, 196, 36, 36, ...","[[0.15888, 7.33676, 13.26024, 17.804, 24.92724...","[[7888.06344, 7897.52612, 7907.44608, 7918.663...","[[8768.00212, 8780.2724, 8789.52544, 8797.7130..."
4,zbr119,0625_0_12,133.166146,M,app_ps1,RSPv,FS,0.16,4,"[[0.09323999999999999, 0.044280000000000014, 0...","[[0.011319999999614083, 0.02408000000013999, 0...","[[0.04363999999986845, 0.02139999999963038, 0....","[6252, 800, 404, 164, 800, 224, 2492, 568, 404...","[880, 452, 436, 760, 452, 660, 880, 168, 356, ...","[100, 176, 12, 72, 100, 76, 156, 196, 36, 36, ...","[[0.00664, 9.85524, 14.17668, 19.6262, 24.8345...","[[7888.05748, 7895.06872, 7899.47408, 7903.746...","[[8768.14896, 8773.95908, 8780.01188, 8785.671..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,zbr119,0625_0_12,133.166146,M,app_ps1,ACad,RSU,0.68,102,"[[0.010880000000000223, 0.5617199999999998, 5....","[[3.3936400000002322, 0.9065200000004552, 0.09...","[[1.2009600000001228, 0.030479999999442953, 0....","[6252, 800, 404, 164, 800, 224, 2492, 568, 404...","[880, 452, 436, 760, 452, 660, 880, 168, 356, ...","[100, 176, 12, 72, 100, 76, 156, 196, 36, 36, ...","[[3.42032, 182.18088, 293.54096, 421.74392, 51...","[[7888.68784, 7996.04892, 8122.69164, 8207.121...","[[8769.16652, 8828.0494, 8854.74424, 8867.9052..."
103,zbr119,0625_0_12,133.166146,M,app_ps1,ACad,RSU,0.60,103,"[[0.19779999999999998, 0.8178000000000001, 0.1...","[[0.07772000000022672, 0.029359999999542197, 2...","[[4.294399999998859, 0.17403999999987718, 1.90...","[6252, 800, 404, 164, 800, 224, 2492, 568, 404...","[880, 452, 436, 760, 452, 660, 880, 168, 356, ...","[100, 176, 12, 72, 100, 76, 156, 196, 36, 36, ...","[[2.92164, 72.99052, 139.00816, 207.9406, 292....","[[7888.7562, 7945.41464, 8009.14864, 8060.1848...","[[8769.93264, 8851.2924, 8852.06108], [9838.59..."
104,zbr119,0625_0_12,133.166146,M,app_ps1,ACad,RSU,0.60,104,"[[0.3539199999999999, 0.8408000000000002, 0.18...","[[0.6129199999995762, 0.3091199999998935, 3.79...","[[0.23099999999976717, 1.136399999999412, 0.48...","[6252, 800, 404, 164, 800, 224, 2492, 568, 404...","[880, 452, 436, 760, 452, 660, 880, 168, 356, ...","[100, 176, 12, 72, 100, 76, 156, 196, 36, 36, ...","[[0.82204, 29.00096, 63.14116, 105.8688, 122.8...","[[7888.16524, 7913.58636, 7955.43916, 7999.353...","[[8768.96116, 8817.50364, 8863.82744, 8867.171..."
105,zbr119,0625_0_12,133.166146,M,app_ps1,ACad,RSU,0.68,105,"[[0.4318799999999996, 0.38339999999999996, 0.3...","[[1.0840399999997317, 0.19848000000001775, 0.1...","[[0.06068000000050233, 0.0381600000000617, 1.4...","[6252, 800, 404, 164, 800, 224, 2492, 568, 404...","[880, 452, 436, 760, 452, 660, 880, 168, 356, ...","[100, 176, 12, 72, 100, 76, 156, 196, 36, 36, ...","[[4.26876, 228.55528, 328.9104, 459.9064, 509....","[[7889.25028, 8121.01212, 8392.40868, 8564.130...","[[8768.02356, 8867.60316], [9837.11108, 9969.0..."
106,zbr119,0625_0_12,133.166146,M,app_ps1,ACad,RSU,0.76,106,"[[0.023279999999999745, 0.1943199999999905, 31...","[[519.2471600000008, 6.579039999998713, 0.0287...","[[47.31680000000051, 9.77332000000024, -57.090...","[6252, 800, 404, 164, 800, 224, 2492, 568, 404...","[880, 452, 436, 760, 452, 660, 880, 168, 356, ...","[100, 176, 12, 72, 100, 76, 156, 196, 36, 36, ...","[[125.6466, 2173.6656, 6198.48444], [7428.0122...","[[8100.42268, 8742.38988], [8929.97504, 9307.3...","[[8804.2714, 8861.36152], [9871.70884, 9971.72..."

got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,zbr119,0625_12_24,133.666169,M,app_ps1,RSPv,RSU,0.56,0,"[[0.044719999999983884, 0.04579999999998563, 0...","[[0.016119999999773427, 0.02451999999993859, 0...","[[0.023720000000139407, 0.07567999999992026, 0...","[268, 4, 224, 132, 2284, 144, 4276, 500, 692, ...","[516, 212, 264, 276, 376, 440, 12, 8, 228, 304...","[32, 32, 56, 100, 840, 724, 24, 32, 60, 28, 11...","[[888.08816, 896.29428, 905.44128, 913.44012, ...","[[2364.24256, 2374.168, 2387.65796, 2399.92896...","[[3316.14036, 3328.53708, 3335.94748, 3340.762..."
1,zbr119,0625_12_24,133.666169,M,app_ps1,RSPv,RSU,0.64,1,"[[0.05728000000010525, 0.012560000000007676, 0...","[[0.07823999999982334, 0.018079999999827123, 0...","[[0.008400000000165164, 0.015319999999974243, ...","[268, 4, 224, 132, 2284, 144, 4276, 500, 692, ...","[516, 212, 264, 276, 376, 440, 12, 8, 228, 304...","[32, 32, 56, 100, 840, 724, 24, 32, 60, 28, 11...","[[888.07468, 894.8454, 900.79092, 906.08708, 9...","[[2364.00784, 2371.21536, 2379.00512, 2388.126...","[[3316.14076, 3327.60784, 3336.88472, 3343.170..."
2,zbr119,0625_12_24,133.666169,M,app_ps1,RSPv,RSU,0.52,2,"[[7.368200000000002, 21.315079999999966, 17.79...","[[18.184439999999995, 13.520160000000033, 29.6...","[[4.230079999999816, 11.2830399999998], [4.669...","[268, 4, 224, 132, 2284, 144, 4276, 500, 692, ...","[516, 212, 264, 276, 376, 440, 12, 8, 228, 304...","[32, 32, 56, 100, 840, 724, 24, 32, 60, 28, 11...","[[923.86192, 1151.61676], [], [2883.34452, 309...","[[2374.76492, 2870.4394], [3113.171, 3304.5082...","[[3325.23732, 3340.75044], [3645.62652, 3651.0..."
3,zbr119,0625_12_24,133.666169,M,app_ps1,RSPv,RSU,0.52,3,"[[0.00836000000003878, 0.10256000000003951, 0....","[[0.03519999999980428, 0.0012400000000525324, ...","[[0.08944000000019514, 0.09468000000015309, 0....","[268, 4, 224, 132, 2284, 144, 4276, 500, 692, ...","[516, 212, 264, 276, 376, 440, 12, 8, 228, 304...","[32, 32, 56, 100, 840, 724, 24, 32, 60, 28, 11...","[[888.0078, 892.89312, 898.49648, 906.033, 911...","[[2364.01216, 2367.81864, 2373.5534, 2380.4072...","[[3316.0966, 3325.12108, 3333.9208, 3340.53308..."
4,zbr119,0625_12_24,133.666169,M,app_ps1,RSPv,RSU,0.60,4,"[[0.0141999999999598, 2.7158399999999574, 1.18...","[[0.30335999999988417, 0.10644000000002052, 0....","[[0.49492000000009284, 1.4618799999998373, 0.0...","[268, 4, 224, 132, 2284, 144, 4276, 500, 692, ...","[516, 212, 264, 276, 376, 440, 12, 8, 228, 304...","[32, 32, 56, 100, 840, 724, 24, 32, 60, 28, 11...","[[892.11868, 1152.8802], [2360.54628, 2360.981...","[[2367.56824, 2454.54372, 2555.94808, 2657.026...","[[3316.80764, 3346.574], [3636.14608, 3650.797..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,zbr119,0625_12_24,133.666169,M,app_ps1,ACad,RSU,0.60,118,"[[2.0438400000000456, 0.07155999999997675, 0.6...","[[0.14420000000018263, 0.10543999999981679, 0....","[[0.009199999999964348, 0.14544000000023516, 0...","[268, 4, 224, 132, 2284, 144, 4276, 500, 692, ...","[516, 212, 264, 276, 376, 440, 12, 8, 228, 304...","[32, 32, 56, 100, 840, 724, 24, 32, 60, 28, 11...","[[891.2482, 924.16048, 939.54436, 955.54536, 9...","[[2364.6944, 2412.2998, 2478.76648, 2534.82844...","[[3317.03908, 3344.77836], [3637.84856, 3664.7..."
119,zbr119,0625_12_24,133.666169,M,app_ps1,ACad,RSU,0.64,119,"[[0.3108799999999974, 0.3594799999999623, 0.35...","[[0.319079999999758, 0.06576000000040949, 0.49...","[[0.17376000000012937, 0.40275999999994383, 0....","[268, 4, 224, 132, 2284, 144, 4276, 500, 692, ...","[516, 212, 264, 276, 376, 440, 12, 8, 228, 304...","[32, 32, 56, 100, 840, 724, 24, 32, 60, 28, 11...","[[888.00548, 898.93264, 910.8098, 922.56248, 9...","[[2364.22296, 2381.80028, 2405.82188, 2432.930...","[[3316.38312, 3347.60316], [3637.744, 3667.399..."
120,zbr119,0625_12_24,133.666169,M,app_ps1,ACad,RSU,0.64,120,"[[0.22111999999992804, 1.7676000000000158, 0.6...","[[1.0778000000000247, 0.28684000000021115, 0.2...","[[0.05536000000029162, 0.41031999999995605, 2....","[268, 4, 224, 132, 2284, 144, 4276, 500, 692, ...","[516, 212, 264, 276, 376, 440, 12, 8, 228, 304...","[32, 32, 56, 100, 840, 724, 24, 32, 60, 28, 11...","[[889.95784, 940.291, 981.74952, 1044.15508, 1...","[[2365.13408, 2497.41516, 2616.56084, 2731.533...","[[3317.11332, 3345.91852], [3637.84852, 3663.8..."
121,zbr119,0625_12_24,133.666169,M,app_ps1,ACad,RSU,0.68,121,"[[0.15168000000005577, 0.3165199999999686, 0.1...","[[0.22895999999991545, 0.274199999999837, 0.28...","[[0.02080000000023574, 0.011919999999918218, 0...","[268, 4, 224, 132, 2284, 144, 4276, 500, 692, ...","[516, 212, 264, 276, 376, 440, 12, 8, 228, 304...","[32, 32, 56, 100, 840, 724, 24, 32, 60, 28, 11...","[[889.34152, 922.52924, 933.50484, 945.52968, ...","[[2367.34796, 2598.98332, 2859.39908, 2879.469...","[[3341.17508, 3343.69316], [3660.6044, 3667.10..."
122,zbr119,0625_12_24,133.666169,M,app_ps1,ACad,RSU,0.52,122,"[[0.16408000000001266, 0.05383999999992284, 0....","[[0.02323999999998705, 0.15291999999999462, 0....","[[0.2863200000001598, 0.5265599999997903, 0.28...","[268, 4, 224, 132, 2284, 144, 4276, 500, 692, ...","[516, 212, 264, 276, 376, 440, 12, 8, 228, 304...","[32, 32, 56, 100, 840, 724, 24, 32, 60, 28, 11...","[[888.34464, 900.16624, 908.7436, 915.49884, 9...","[[2364.12224, 2378.53692, 2393.2678, 2413.2048...","[[3316.11076, 3334.04932, 3347.97136], [3636.4..."

Working on bth90
Has 2 files to go through
got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,bth90,0323_0_12,101.185266,F,wt,ACad,RSU,0.60,0,"[[0.08188000000000001, 0.07487999999999995, 0....","[[0.9253999999999678, 0.1448400000000447, 0.22...","[[0.7637999999999465, 0.37780000000009295, 0.6...","[504, 1744, 2620, 136, 60, 2012, 112, 952, 80,...","[396, 488, 468, 92, 356, 404, 292, 544, 132, 5...","[84, 64, 136, 44, 100, 120, 12, 188, 108, 40, ...","[[0.4038, 51.999, 75.81, 105.19016, 148.9134, ...","[[504.5926, 575.1684, 619.96576, 687.14812, 74...","[[900.03404, 946.23904, 973.5802, 983.4922], [..."
1,bth90,0323_0_12,101.185266,F,wt,ACad,RSU,0.76,1,"[[0.12180000000000035, 0.29655999999999993, 0....","[[0.213799999999992, 0.02336000000002514, 0.18...","[[0.11755999999991218, 0.03560000000004493, 0....","[504, 1744, 2620, 136, 60, 2012, 112, 952, 80,...","[396, 488, 468, 92, 356, 404, 292, 544, 132, 5...","[84, 64, 136, 44, 100, 120, 12, 188, 108, 40, ...","[[3.42792, 34.16688, 53.22416, 93.43296, 131.4...","[[504.59296, 567.53688, 629.27328, 692.41892, ...","[[901.04348, 947.72396, 979.72264, 983.8076], ..."
2,bth90,0323_0_12,101.185266,F,wt,ACad,RSU,0.76,2,"[[0.21056, 0.23156, 0.20496000000000003, 0.030...","[[0.12715999999994665, 0.462600000000009, 0.10...","[[0.4352400000000216, 0.2635999999999967, 0.31...","[504, 1744, 2620, 136, 60, 2012, 112, 952, 80,...","[396, 488, 468, 92, 356, 404, 292, 544, 132, 5...","[84, 64, 136, 44, 100, 120, 12, 188, 108, 40, ...","[[0.01236, 5.97188, 10.85096, 17.04108, 24.278...","[[504.29844, 521.93688, 541.68916, 563.01704, ...","[[900.15412, 923.93792, 948.87004, 969.85068, ..."
3,bth90,0323_0_12,101.185266,F,wt,ACad,RSU,0.60,3,"[[1.50172, 1.18392, 1.0238399999999999, 1.4476...","[[0.07532000000003336, 2.7916000000000167, 0.7...","[[2.0390800000000127, 0.013720000000034815, 0....","[504, 1744, 2620, 136, 60, 2012, 112, 952, 80,...","[396, 488, 468, 92, 356, 404, 292, 544, 132, 5...","[84, 64, 136, 44, 100, 120, 12, 188, 108, 40, ...","[[1.792, 92.66156, 252.77444, 371.34968, 499.8...","[[508.775, 789.65212, 897.36308], [1012.8752, ...","[[901.8564, 976.75784], [1493.75392, 1555.9099..."
4,bth90,0323_0_12,101.185266,F,wt,ACad,RSU,0.64,4,"[[0.12712, 0.16964000000000012, 0.215199999999...","[[1.9007599999999911, 0.08348000000000866, 1.0...","[[2.181919999999991, 0.05547999999998865, 0.31...","[504, 1744, 2620, 136, 60, 2012, 112, 952, 80,...","[396, 488, 468, 92, 356, 404, 292, 544, 132, 5...","[84, 64, 136, 44, 100, 120, 12, 188, 108, 40, ...","[[0.72288, 32.99956, 71.28112, 119.30376, 164....","[[504.04284, 605.93928, 702.506, 855.3652, 899...","[[901.7136, 983.65364], [1493.95964, 1555.7854..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,bth90,0323_0_12,101.185266,F,wt,V1,RSU,0.52,140,"[[0.08336, 0.12548, 0.12988, 0.144919999999999...","[[0.030480000000011387, 0.017040000000008604, ...","[[0.5414400000000796, 0.003399999999942338, 0....","[504, 1744, 2620, 136, 60, 2012, 112, 952, 80,...","[396, 488, 468, 92, 356, 404, 292, 544, 132, 5...","[84, 64, 136, 44, 100, 120, 12, 188, 108, 40, ...","[[0.07204, 8.664, 17.51264, 24.88292, 30.34076...","[[504.0904, 516.016, 526.79268, 539.16472, 550...","[[900.19112, 913.4968, 927.0328, 940.30364, 95..."
141,bth90,0323_0_12,101.185266,F,wt,V1,RSU,0.60,141,"[[0.03604, 0.026240000000000006, 0.00359999999...","[[0.021839999999997417, 0.0897600000000125, 0....","[[0.020039999999994507, 0.20235999999999876, 0...","[504, 1744, 2620, 136, 60, 2012, 112, 952, 80,...","[396, 488, 468, 92, 356, 404, 292, 544, 132, 5...","[84, 64, 136, 44, 100, 120, 12, 188, 108, 40, ...","[[0.01488, 2.9524, 6.01172, 9.37152, 12.74128,...","[[504.00568, 508.03048, 512.2476, 516.84968, 5...","[[900.00044, 903.99648, 908.33624, 912.23116, ..."
142,bth90,0323_0_12,101.185266,F,wt,V1,FS,0.24,142,"[[0.01076, 0.03956, 0.031160000000000007, 0.02...","[[0.09755999999998721, 0.03684000000004062, 0....","[[0.006679999999960273, 0.013080000000059044, ...","[504, 1744, 2620, 136, 60, 2012, 112, 952, 80,...","[396, 488, 468, 92, 356, 404, 292, 544, 132, 5...","[84, 64, 136, 44, 100, 120, 12, 188, 108, 40, ...","[[0.0066, 6.49868, 11.10964, 15.45288, 20.3914...","[[504.0766, 512.67336, 522.9576, 532.05436, 53...","[[900.28476, 908.7308, 917.40048, 926.42632, 9..."
143,bth90,0323_0_12,101.185266,F,wt,V1,RSU,0.56,143,"[[0.0020799999999999985, 0.05932000000000001, ...","[[0.012000000000000455, 0.08755999999999631, 0...","[[0.03916000000003805, 0.24163999999996122, 0....","[504, 1744, 2620, 136, 60, 2012, 112, 952, 80,...","[396, 488, 468, 92, 356, 404, 292, 544, 132, 5...","[84, 64, 136, 44, 100, 120, 12, 188, 108, 40, ...","[[0.09408, 6.56724, 13.74764, 19.2042, 23.9924...","[[504.01936, 510.62184, 518.98936, 527.861, 53...","[[900.00396, 910.90188, 920.73216, 929.99716, ..."
144,bth90,0323_0_12,101.185266,F,wt,V1,RSU,0.60,144,"[[0.29508, 0.08527999999999997, 0.020440000000...","[[0.2248000000000161, 0.09339999999997417, 0.0...","[[0.10592000000008284, 0.20871999999997115, 0....","[504, 1744, 2620, 136, 60, 2012, 112, 952, 80,...","[396, 488, 468, 92, 356, 404, 292, 544, 132, 5...","[84, 64, 136, 44, 100, 120, 12, 188, 108, 40, ...","[[0.04368, 13.28164, 23.10884, 34.11704, 46.56...","[[504.45376, 524.72336, 538.95924, 551.72548, ...","[[900.07504, 918.66244, 940.49804, 964.17988, ..."

got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,bth90,0323_12_24,101.685289,F,wt,ACad,RSU,0.80,0,"[[0.004800000000017235, 0.0781199999999842, 0....","[[0.003119999999398715, 0.028760000000147556, ...","[[0.0873200000005454, 0.06563999999980297, 0.7...","[1688, 2204, 5712, 1080, 1464, 2304, 484, 996,...","[348, 416, 340, 460, 696, 544, 212, 588, 116, ...","[72, 100, 164, 92, 176, 104, 24, 100, 20, 44, ...","[[196.00508, 218.07776, 241.59704, 270.29676, ...","[[4548.7596, 4595.20356, 4651.29984, 4720.0579...","[[4897.22816, 4928.2676, 4964.40244, 4967.9003..."
1,bth90,0323_12_24,101.685289,F,wt,ACad,FS,0.12,1,"[[0.8292800000000113, 0.9932799999999986, 0.88...","[[0.5824800000000323, 0.24703999999928783, 0.7...","[[1.8685199999999895, 0.6715199999998731, 1.12...","[1688, 2204, 5712, 1080, 1464, 2304, 484, 996,...","[348, 416, 340, 460, 696, 544, 212, 588, 116, ...","[72, 100, 164, 92, 176, 104, 24, 100, 20, 44, ...","[[197.3526, 854.652, 1097.74612, 1510.081, 187...","[[4550.08492, 4727.22628, 4895.18776], [4985.4...","[[4898.2238, 4967.55088], [5400.47288, 5495.34..."
2,bth90,0323_12_24,101.685289,F,wt,ACad,RSU,0.60,2,"[[0.03875999999999635, 0.0906800000000203, 0.3...","[[4.275880000000143, 1.0583200000000943, 3.671...","[[0.020599999999831198, 2.8541199999999662, 1....","[1688, 2204, 5712, 1080, 1464, 2304, 484, 996,...","[348, 416, 340, 460, 696, 544, 212, 588, 116, ...","[72, 100, 164, 92, 176, 104, 24, 100, 20, 44, ...","[[196.12524, 228.91812, 382.02372, 539.71396, ...","[[4555.93136, 4893.72412], [5000.9412, 5392.94...","[[4896.80108, 4967.53228], [5401.5076, 5499.40..."
3,bth90,0323_12_24,101.685289,F,wt,ACad,FS,0.12,3,"[[0.05588000000000193, 0.25079999999999814, 0....","[[0.1938399999999092, 0.07695999999941705, 0.0...","[[0.1324400000003152, 0.6151200000003882, 0.52...","[1688, 2204, 5712, 1080, 1464, 2304, 484, 996,...","[348, 416, 340, 460, 696, 544, 212, 588, 116, ...","[72, 100, 164, 92, 176, 104, 24, 100, 20, 44, ...","[[196.25612, 207.89576, 218.81148, 229.06128, ...","[[4548.15624, 4573.22616, 4603.76892, 4631.831...","[[4896.04628, 4912.04148, 4919.9028, 4925.8499..."
4,bth90,0323_12_24,101.685289,F,wt,ACad,RSU,0.64,4,"[[0.02552000000000021, 0.09532000000001517, 0....","[[0.13879999999971915, 0.02599999999983993, 0....","[[0.018839999999727297, 0.20668000000023312, 0...","[1688, 2204, 5712, 1080, 1464, 2304, 484, 996,...","[348, 416, 340, 460, 696, 544, 212, 588, 116, ...","[72, 100, 164, 92, 176, 104, 24, 100, 20, 44, ...","[[196.05452, 199.43, 202.16316, 204.73396, 208...","[[4548.01824, 4553.33152, 4558.18572, 4563.303...","[[4896.07208, 4902.48504, 4908.78892, 4915.676..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,bth90,0323_12_24,101.685289,F,wt,V1,RSU,0.72,136,"[[0.06847999999999388, 0.04304000000001906, 0....","[[0.04312000000027183, 0.06652000000030966, 0....","[[0.06507999999939784, 0.0886000000000422, 0.1...","[1688, 2204, 5712, 1080, 1464, 2304, 484, 996,...","[348, 416, 340, 460, 696, 544, 212, 588, 116, ...","[72, 100, 164, 92, 176, 104, 24, 100, 20, 44, ...","[[196.04592, 201.42032, 207.39836, 214.24048, ...","[[4548.00088, 4553.81124, 4561.57996, 4570.483...","[[4896.04632, 4903.68464, 4912.257, 4918.9268,..."
137,bth90,0323_12_24,101.685289,F,wt,V1,RSU,0.52,137,"[[0.011959999999987758, 0.006000000000000227, ...","[[0.020679999999629217, 0.0030800000004092, 0....","[[0.12327999999979511, 0.05915999999979249, 0....","[1688, 2204, 5712, 1080, 1464, 2304, 484, 996,...","[348, 416, 340, 460, 696, 544, 212, 588, 116, ...","[72, 100, 164, 92, 176, 104, 24, 100, 20, 44, ...","[[196.0072, 203.29412, 210.80688, 217.34888, 2...","[[4548.14868, 4558.46156, 4570.9252, 4583.5613...","[[4896.16424, 4911.0198, 4924.52344, 4939.5124..."
138,bth90,0323_12_24,101.685289,F,wt,V1,RSU,0.60,138,"[[0.044879999999977827, 0.017040000000008604, ...","[[0.13896000000022468, 0.0227999999997337, 0.0...","[[0.0863999999992302, 0.0025200000000040745, 0...","[1688, 2204, 5712, 1080, 1464, 2304, 484, 996,...","[348, 416, 340, 460, 696, 544, 212, 588, 116, ...","[72, 100, 164, 92, 176, 104, 24, 100, 20, 44, ...","[[196.00004, 199.82132, 204.61268, 209.94876, ...","[[4548.17108, 4553.60104, 4560.56392, 4566.756...","[[4896.01532, 4905.84544, 4913.95188, 4922.470..."
139,bth90,0323_12_24,101.685289,F,wt,V1,FS,0.24,139,"[[0.042360000000002174, 0.011560000000002901, ...","[[0.15232000000014523, 0.02819999999974243, 0....","[[0.4395200000008117, 0.29235999999946216, 0.0...","[1688, 2204, 5712, 1080, 1464, 2304, 484, 996,...","[348, 416, 340, 460, 696, 544, 212, 588, 116, ...","[72, 100, 164, 92, 176, 104, 24, 100, 20, 44, ...","[[196.00728, 205.2996, 212.31844, 219.96644, 2...","[[4548.01152, 4561.92108, 4577.82464, 4596.039...","[[4896.33984, 4912.43936, 4924.35528, 4942.211..."
140,bth90,0323_12_24,101.685289,F,wt,V1,RSU,0.64,140,"[[0.15379999999998972, 0.08340000000001169, 0....","[[0.38040000000000873, 0.14452000000073895, 0....","[[0.18708000000060565, 0.29500000000007276, 0....","[1688, 2204, 5712, 1080, 1464, 2304, 484, 996,...","[348, 416, 340, 460, 696, 544, 212, 588, 116, ...","[72, 100, 164, 92, 176, 104, 24, 100, 20, 44, ...","[[196.14416, 211.86548, 224.5836, 241.47768, 2...","[[4548.0232, 4565.92656, 4580.9286, 4596.18488...","[[4896.16256, 4917.95556, 4941.74612, 4967.892..."

Working on bth95
Has 4 files to go through
got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,bth95,0611_0_12,105.093356,F,wt,CA1,RSU,0.40,0,"[[0.37611999999990076, 0.021639999999933934, 0...","[[0.08107999999999999, 0.00496000000000002, 0....","[[0.17092000000002372, 2.7452399999999955, 0.3...","[1312, 1848, 1428, 1016, 480, 1848, 648, 164, ...","[216, 292, 252, 172, 584, 500, 560, 248, 668, ...","[124, 24, 16, 56, 180, 80, 32, 24, 116, 52, 24...","[[5888.46496, 5910.763, 5928.37444, 5950.50908...","[[0.2006, 39.15536, 83.20164, 134.54152, 180.8...","[[216.367, 263.81092, 312.63572, 339.91984], [..."
1,bth95,0611_0_12,105.093356,F,wt,CA1,FS,0.24,1,"[[0.1671599999999671, 0.013960000000224682, 0....","[[0.9472, 0.01075999999999988, 0.5094800000000...","[[0.1052800000000218, 0.40607999999997446, 0.3...","[1312, 1848, 1428, 1016, 480, 1848, 648, 164, ...","[216, 292, 252, 172, 584, 500, 560, 248, 668, ...","[124, 24, 16, 56, 180, 80, 32, 24, 116, 52, 24...","[[5888.10948, 5904.4136, 5914.00704, 5926.5694...","[[0.11456, 17.22648, 33.20644, 44.47756, 59.23...","[[216.0682, 232.74204, 250.19896, 257.77568, 2..."
2,bth95,0611_0_12,105.093356,F,wt,CA1,FS,0.12,2,"[[0.2398800000000847, 0.40287999999964086, 0.0...","[[0.836, 0.603, 0.23772000000000015, 0.9722799...","[[0.24976000000000909, 0.0029199999999889314, ...","[1312, 1848, 1428, 1016, 480, 1848, 648, 164, ...","[216, 292, 252, 172, 584, 500, 560, 248, 668, ...","[124, 24, 16, 56, 180, 80, 32, 24, 116, 52, 24...","[[5888.12452, 5902.90984, 5919.28504, 5932.605...","[[0.18524, 48.49892, 97.94676, 138.06596, 181....","[[216.07512, 245.97076, 266.1856, 293.12192, 3..."
3,bth95,0611_0_12,105.093356,F,wt,CA1,FS,0.36,3,"[[0.5751600000003236, 0.1934000000001106, 1.11...","[[0.92744, 0.16235999999999984, 0.164560000000...","[[0.017480000000006157, 0.009559999999993352, ...","[1312, 1848, 1428, 1016, 480, 1848, 648, 164, ...","[216, 292, 252, 172, 584, 500, 560, 248, 668, ...","[124, 24, 16, 56, 180, 80, 32, 24, 116, 52, 24...","[[5888.1052, 5936.7328, 5999.82324, 6060.59604...","[[0.4998, 51.07804, 120.78432, 191.34336, 215....","[[216.5112, 271.72148, 322.26148, 339.9356], [..."
4,bth95,0611_0_12,105.093356,F,wt,CA1,FS,0.20,4,"[[0.09436000000005151, 1.155279999999948, 2.40...","[[0.010440000000000005, 1.8139199999999998, 0....","[[0.9578400000000045, 0.4470799999999997, 3.74...","[1312, 1848, 1428, 1016, 480, 1848, 648, 164, ...","[216, 292, 252, 172, 584, 500, 560, 248, 668, ...","[124, 24, 16, 56, 180, 80, 32, 24, 116, 52, 24...","[[5891.36108, 5912.60788, 5919.20048, 5926.864...","[[0.41944, 112.04552, 215.36072], [359.35088, ...","[[216.51644, 263.85084, 289.14636, 310.8472, 3..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,bth95,0611_0_12,105.093356,F,wt,V1,FS,0.12,148,"[[0.35239999999976135, 0.6015200000001641, 0.0...","[[0.012759999999999994, 0.23832000000000003, 0...","[[0.19820000000001414, 0.002240000000000464, 0...","[1312, 1848, 1428, 1016, 480, 1848, 648, 164, ...","[216, 292, 252, 172, 584, 500, 560, 248, 668, ...","[124, 24, 16, 56, 180, 80, 32, 24, 116, 52, 24...","[[5888.45628, 5902.16984, 5911.34828, 5921.565...","[[0.16552, 15.98588, 29.996, 40.62788, 48.5230...","[[216.21576, 226.35672, 235.717, 244.30216, 25..."
149,bth95,0611_0_12,105.093356,F,wt,V1,FS,0.28,149,"[[2.074959999999919, 0.06924000000071828, 0.08...","[[1.1530399999999998, 0.013679999999999914, 2....","[[0.04184000000000765, 0.23071999999999093, 0....","[1312, 1848, 1428, 1016, 480, 1848, 648, 164, ...","[216, 292, 252, 172, 584, 500, 560, 248, 668, ...","[124, 24, 16, 56, 180, 80, 32, 24, 116, 52, 24...","[[5889.81348, 5917.43756, 5941.21412, 5973.141...","[[1.51696, 46.05664, 74.81816, 125.31316, 168....","[[216.7004, 247.2588, 258.64116, 269.54656, 28..."
150,bth95,0611_0_12,105.093356,F,wt,V1,FS,0.16,150,"[[0.054200000000491855, 0.014760000000023865, ...","[[0.038639999999999994, 0.39252, 0.05303999999...","[[0.004559999999997899, 0.2943599999999833, 0....","[1312, 1848, 1428, 1016, 480, 1848, 648, 164, ...","[216, 292, 252, 172, 584, 500, 560, 248, 668, ...","[124, 24, 16, 56, 180, 80, 32, 24, 116, 52, 24...","[[5888.039, 5891.96368, 5895.7616, 5900.2046, ...","[[0.06772, 14.94168, 26.95596, 39.89472, 47.04...","[[216.10192, 228.642, 237.74464, 243.99972, 24..."
151,bth95,0611_0_12,105.093356,F,wt,V1,FS,0.12,151,"[[0.21152000000074622, 0.7362399999992704, 0.3...","[[0.68372, 1.59176, 0.2573599999999998, 0.2902...","[[0.3682399999999859, 0.9126400000000103, 0.00...","[1312, 1848, 1428, 1016, 480, 1848, 648, 164, ...","[216, 292, 252, 172, 584, 500, 560, 248, 668, ...","[124, 24, 16, 56, 180, 80, 32, 24, 116, 52, 24...","[[5888.09596, 5905.13684, 5921.07124, 5932.307...","[[0.14868, 30.4238, 56.02208, 83.73192, 118.43...","[[216.96464, 245.17452, 262.2132, 278.35644, 2..."
152,bth95,0611_0_12,105.093356,F,wt,V1,RSU,0.60,152,"[[0.592279999999846, 1.5473999999994703, 1.175...","[[1.6296400000000002, 2.55804, 0.4156000000000...","[[0.6126799999999832, 1.7979200000000048, 0.40...","[1312, 1848, 1428, 1016, 480, 1848, 648, 164, ...","[216, 292, 252, 172, 584, 500, 560, 248, 668, ...","[124, 24, 16, 56, 180, 80, 32, 24, 116, 52, 24...","[[5889.64936, 5934.56816, 5965.72908, 6020.729...","[[8.78376, 203.46084, 211.14496], [359.604, 55...","[[217.91396, 300.57256, 339.99604], [651.78332..."

got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,bth95,0611_12_24,105.59338,F,wt,CA1,RSU,0.68,0,"[[0.3227199999999999, 0.5360800000000001, 0.08...","[[0.228080000000773, 1.1033199999992576, 2.953...","[[1.2845200000001569, 0.4228400000001784, 0.73...","[5600, 288, 1228, 1816, 2700, 3016, 372, 1136,...","[428, 536, 344, 548, 120, 632, 436, 204, 48, 3...","[36, 40, 88, 24, 28, 48, 72, 164, 44, 60, 88, ...","[[1.77896, 70.1146, 144.5448, 226.67876, 307.5...","[[5816.86796, 5877.44176, 5947.87244, 6019.207...","[[6245.6772, 6279.8004], [6836.39072, 6875.387..."
1,bth95,0611_12_24,105.59338,F,wt,CA1,FS,0.24,1,"[[0.1594, 0.08736, 0.22864000000000007, 0.2464...","[[0.20103999999992084, 0.3091199999998935, 0.1...","[[0.11983999999938533, 0.4354400000001988, 0.1...","[5600, 288, 1228, 1816, 2700, 3016, 372, 1136,...","[428, 536, 344, 548, 120, 632, 436, 204, 48, 3...","[36, 40, 88, 24, 28, 48, 72, 164, 44, 60, 88, ...","[[0.03508, 15.5912, 27.9168, 41.60604, 56.1788...","[[5816.04384, 5834.59508, 5853.80048, 5871.622...","[[6244.04964, 6259.43492, 6276.14232, 6279.844..."
2,bth95,0611_12_24,105.59338,F,wt,CA1,RSU,0.84,2,"[[12.48112, 2.281319999999999, 0.1228799999999...","[[12.90516000000025, 0.006440000000111468, 63....","[[], [], [], [], [], [3.9397600000011153, 0.72...","[5600, 288, 1228, 1816, 2700, 3016, 372, 1136,...","[428, 536, 344, 548, 120, 632, 436, 204, 48, 3...","[36, 40, 88, 24, 28, 48, 72, 164, 44, 60, 88, ...","[[3.01056, 373.35984, 496.84224, 575.28672, 67...","[[5950.40284, 6236.34804], [6331.114, 6805.177...","[[], [], [7301.58844], [10668.7414], [], [1103..."
3,bth95,0611_12_24,105.59338,F,wt,CA1,RSU,0.72,3,"[[0.12863999999999987, 0.13016000000000005, 0....","[[0.01231999999981781, 2.309479999999894, 0.67...","[[24.27868000000035, 0.012679999999818392], [1...","[5600, 288, 1228, 1816, 2700, 3016, 372, 1136,...","[428, 536, 344, 548, 120, 632, 436, 204, 48, 3...","[36, 40, 88, 24, 28, 48, 72, 164, 44, 60, 88, ...","[[2.53852, 100.28512, 107.96584, 118.82408, 12...","[[5816.53892, 5925.69728, 6045.40156, 6165.184...","[[6252.33476, 6276.62612], [6842.31632, 6853.1..."
4,bth95,0611_12_24,105.59338,F,wt,CA1,FS,0.12,4,"[[0.24028, 0.37788000000000005, 0.107399999999...","[[0.17536000000018248, 0.04156000000057247, 0....","[[0.13479999999981374, 0.15812000000005355, 0....","[5600, 288, 1228, 1816, 2700, 3016, 372, 1136,...","[428, 536, 344, 548, 120, 632, 436, 204, 48, 3...","[36, 40, 88, 24, 28, 48, 72, 164, 44, 60, 88, ...","[[0.21848, 25.76572, 63.01576, 88.14148, 124.2...","[[5816.05092, 5850.56612, 5890.44156, 5929.942...","[[6244.47428, 6266.7794, 6279.7598], [6836.591..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,bth95,0611_12_24,105.59338,F,wt,V1,RSU,0.52,144,"[[0.011319999999999997, 0.060200000000000004, ...","[[0.06132000000070548, 0.04103999999915686, 0....","[[0.004680000000007567, 0.05703999999968801, 0...","[5600, 288, 1228, 1816, 2700, 3016, 372, 1136,...","[428, 536, 344, 548, 120, 632, 436, 204, 48, 3...","[36, 40, 88, 24, 28, 48, 72, 164, 44, 60, 88, ...","[[0.20308, 5.72528, 14.2684, 21.14576, 30.9682...","[[5816.0646, 5833.16668, 5840.18412, 5845.5651...","[[6244.11024, 6261.84348, 6278.19004, 6279.833..."
145,bth95,0611_12_24,105.59338,F,wt,V1,FS,0.12,145,"[[0.20144, 0.03700000000000003, 0.013799999999...","[[0.06308000000080938, 0.06695999999919877, 0....","[[0.022840000000542204, 0.1745599999994738, 0....","[5600, 288, 1228, 1816, 2700, 3016, 372, 1136,...","[428, 536, 344, 548, 120, 632, 436, 204, 48, 3...","[36, 40, 88, 24, 28, 48, 72, 164, 44, 60, 88, ...","[[0.46564, 7.84836, 13.62076, 18.5488, 27.0172...","[[5816.09056, 5823.5362, 5835.58512, 5851.3273...","[[6244.01776, 6250.4678, 6258.80572, 6268.9762..."
146,bth95,0611_12_24,105.59338,F,wt,V1,RSU,0.52,146,"[[0.77456, 0.17700000000000005, 0.096119999999...","[[0.08363999999983207, 0.024120000000039, 0.01...","[[0.02271999999993568, 0.36999999999989086, 0....","[5600, 288, 1228, 1816, 2700, 3016, 372, 1136,...","[428, 536, 344, 548, 120, 632, 436, 204, 48, 3...","[36, 40, 88, 24, 28, 48, 72, 164, 44, 60, 88, ...","[[0.30384, 12.272, 28.27828, 39.18372, 51.3556...","[[5816.08104, 5834.75792, 5846.25292, 5858.097...","[[6244.32556, 6270.57428, 6279.75848], [6836.3..."
147,bth95,0611_12_24,105.59338,F,wt,V1,FS,0.36,147,"[[0.17576000000000014, 0.17511999999999994, 0....","[[0.07344000000011874, 0.20427999999992608, 0....","[[0.24135999999998603, 0.28312000000005355, 0....","[5600, 288, 1228, 1816, 2700, 3016, 372, 1136,...","[428, 536, 344, 548, 120, 632, 436, 204, 48, 3...","[36, 40, 88, 24, 28, 48, 72, 164, 44, 60, 88, ...","[[1.38024, 26.95048, 46.06488, 69.10388, 89.57...","[[5816.22672, 5900.83964, 6005.58668, 6111.541...","[[6244.08312, 6275.23436, 6279.91216], [6840.4..."
148,bth95,0611_12_24,105.59338,F,wt,V1,RSU,0.60,148,"[[0.17415999999999998, 0.37, 0.232760000000000...","[[0.2179999999998472, 0.20467999999982567, 0.3...","[[0.2736399999994319, 0.14880000000084692, 0.7...","[5600, 288, 1228, 1816, 2700, 3016, 372, 1136,...","[428, 536, 344, 548, 120, 632, 436, 204, 48, 3...","[36, 40, 88, 24, 28, 48, 72, 164, 44, 60, 88, ...","[[0.27132, 44.43464, 89.58356, 145.18408, 188....","[[5816.99248, 6071.30044, 6243.91072], [6300.5...","[[6245.38828, 6279.6076], [6843.5502, 6875.656..."

got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,bth95,0612_0_12,106.32316,F,wt,CA1,RSU,0.72,0,"[[0.35168, 0.83836, 0.8591200000000001, 0.5455...","[[0.4351599999999962, 0.004840000000058353, 1....","[[2.036999999999807, 0.18031999999993786, 4.01...","[2208, 56, 96, 168, 528, 1180, 748, 16384, 232...","[308, 324, 112, 328, 824, 488, 716, 860, 224, ...","[84, 20, 132, 120, 96, 136, 160, 24, 184, 32, ...","[[0.43696, 146.12708, 425.21732, 558.54888, 77...","[[2209.53352, 2454.1104, 2515.27188], [2624.98...","[[2528.48736, 2599.1058], [2940.33648, 2957.29..."
1,bth95,0612_0_12,106.32316,F,wt,CA1,FS,0.12,1,"[[0.47884000000000004, 0.21463999999999994, 0....","[[1.137079999999969, 0.2783599999997932, 0.184...","[[0.1603600000003098, 0.35079999999970823, 0.3...","[2208, 56, 96, 168, 528, 1180, 748, 16384, 232...","[308, 324, 112, 328, 824, 488, 716, 860, 224, ...","[84, 20, 132, 120, 96, 136, 160, 24, 184, 32, ...","[[0.90416, 37.81628, 66.58068, 113.9768, 147.3...","[[2208.28756, 2236.21248, 2259.75616, 2289.528...","[[2516.40444, 2539.38256, 2568.88872, 2593.698..."
2,bth95,0612_0_12,106.32316,F,wt,CA1,RSU,0.72,2,"[[1.2209200000000004, 1.1780799999999996, 1.10...","[[0.07600000000002183, 0.21171999999978652, 0....","[[3.1624799999999595, 4.277679999999691, 0.863...","[2208, 56, 96, 168, 528, 1180, 748, 16384, 232...","[308, 324, 112, 328, 824, 488, 716, 860, 224, ...","[84, 20, 132, 120, 96, 136, 160, 24, 184, 32, ...","[[7.9812, 425.28364, 837.5798, 1158.896, 1497....","[[2209.84144, 2426.495, 2513.10444], [2617.343...","[[2522.2676, 2591.269], [2946.17892, 2958.8730..."
3,bth95,0612_0_12,106.32316,F,wt,CA1,FS,0.32,3,"[[0.6988399999999999, 0.42296, 1.4556799999999...","[[4.497040000000197, 3.408799999999701, 0.5869...","[[0.02260000000023865, 0.008519999999862193, 0...","[2208, 56, 96, 168, 528, 1180, 748, 16384, 232...","[308, 324, 112, 328, 824, 488, 716, 860, 224, ...","[84, 20, 132, 120, 96, 136, 160, 24, 184, 32, ...","[[0.2718, 37.61332, 100.13828, 110.6822, 176.6...","[[2212.05692, 2253.1664, 2283.44136, 2317.6835...","[[2517.01032, 2538.38512, 2566.2188, 2576.4613..."
4,bth95,0612_0_12,106.32316,F,wt,CA1,FS,0.24,4,"[[0.448, 0.006360000000000032, 0.0024399999999...","[[0.1980399999997644, 0.9494400000003225, 0.57...","[[0.08455999999978303, 0.4568800000001829, 0.1...","[2208, 56, 96, 168, 528, 1180, 748, 16384, 232...","[308, 324, 112, 328, 824, 488, 716, 860, 224, ...","[84, 20, 132, 120, 96, 136, 160, 24, 184, 32, ...","[[0.49884, 48.4382, 87.5724, 138.19116, 168.86...","[[2210.3332, 2258.66444, 2304.96668, 2320.7926...","[[2517.39588, 2560.50612, 2594.68364, 2599.001..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,bth95,0612_0_12,106.32316,F,wt,V1,RSU,0.52,108,"[[0.03432, 0.03204, 0.01627999999999999, 0.031...","[[0.024600000000191358, 0.07051999999976033, 0...","[[0.046000000000276486, 0.26711999999997715, 0...","[2208, 56, 96, 168, 528, 1180, 748, 16384, 232...","[308, 324, 112, 328, 824, 488, 716, 860, 224, ...","[84, 20, 132, 120, 96, 136, 160, 24, 184, 32, ...","[[0.02956, 3.34088, 6.8008, 10.35268, 13.43844...","[[2208.01628, 2213.32056, 2219.12564, 2225.284...","[[2516.2198, 2525.78664, 2534.3224, 2540.01072..."
109,bth95,0612_0_12,106.32316,F,wt,V1,RSU,0.52,109,"[[0.017520000000000008, 0.48544, 0.34940000000...","[[0.11992000000009284, 0.03736000000026252, 0....","[[0.31899999999996, 0.3122400000002017, 0.2459...","[2208, 56, 96, 168, 528, 1180, 748, 16384, 232...","[308, 324, 112, 328, 824, 488, 716, 860, 224, ...","[84, 20, 132, 120, 96, 136, 160, 24, 184, 32, ...","[[0.21916, 11.63192, 23.16, 37.92924, 49.44416...","[[2209.60508, 2221.56836, 2232.60572, 2244.609...","[[2516.09604, 2527.99544, 2542.43888, 2560.124..."
110,bth95,0612_0_12,106.32316,F,wt,V1,FS,0.28,110,"[[0.4696, 0.5075999999999999, 0.27956000000000...","[[0.16784000000006927, 0.4180799999999181, 0.1...","[[0.35572000000001935, 0.28508000000010725, 0....","[2208, 56, 96, 168, 528, 1180, 748, 16384, 232...","[308, 324, 112, 328, 824, 488, 716, 860, 224, ...","[84, 20, 132, 120, 96, 136, 160, 24, 184, 32, ...","[[0.34536, 61.21684, 116.7948, 172.56644, 238....","[[2208.4936, 2257.90508, 2309.13592, 2379.9713...","[[2516.46944, 2568.47572, 2599.47368, 2599.954..."
111,bth95,0612_0_12,106.32316,F,wt,V1,FS,0.28,111,"[[0.40900000000000003, 0.11136000000000001, 0....","[[3.1186000000002423, 0.13691999999991822, 0.1...","[[2.8713599999996404, 0.3503600000003644, 0.44...","[2208, 56, 96, 168, 528, 1180, 748, 16384, 232...","[308, 324, 112, 328, 824, 488, 716, 860, 224, ...","[84, 20, 132, 120, 96, 136, 160, 24, 184, 32, ...","[[0.3862, 47.54132, 105.93992, 167.0958, 243.8...","[[2208.24824, 2332.94648, 2504.87344, 2513.758...","[[2517.37564, 2599.50136], [2942.19608, 2959.9..."
112,bth95,0612_0_12,106.32316,F,wt,V1,RSU,0.64,112,"[[0.14664, 0.04507999999999998, 0.1256, 0.1929...","[[0.5387200000000121, 0.25600000000031287, 0.4...","[[0.22571999999991021, 0.06719999999995707, 0....","[2208, 56, 96, 168, 528, 1180, 748, 16384, 232...","[308, 324, 112, 328, 824, 488, 716, 860, 224, ...","[84, 20, 132, 120, 96, 136, 160, 24, 184, 32, ...","[[0.09968, 6.44416, 13.11452, 21.64116, 29.318...","[[2208.42964, 2247.9078, 2287.4836, 2314.9072,...","[[2516.34292, 2543.04372, 2562.1656, 2576.8454..."

got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,bth95,0612_12_24,106.823183,F,wt,CA1,RSU,0.72,0,"[[0.0097600000001421, 0.6766399999999066, 0.00...","[[0.2554000000000003, 0.4567999999999999, 0.00...","[[0.0038400000000251566, 2.154679999999985, 0....","[304, 404, 2272, 1728, 1340, 792, 2032, 356, 3...","[244, 412, 224, 208, 556, 360, 792, 212, 76, 6...","[52, 40, 64, 56, 128, 32, 32, 28, 120, 140, 11...","[[1373.57496, 1395.8892, 1415.38732, 1432.4425...","[[2.25648, 43.77064, 87.44696, 93.47872, 104.7...","[[244.08252, 288.189, 294.34228], [737.84156, ..."
1,bth95,0612_12_24,106.823183,F,wt,CA1,RSU,0.40,1,"[[0.054759999999987485, 0.013480000000072323, ...","[[0.030920000000000003, 0.013919999999999988, ...","[[0.7106399999999837, 1.3312400000000082, 0.04...","[304, 404, 2272, 1728, 1340, 792, 2032, 356, 3...","[244, 412, 224, 208, 556, 360, 792, 212, 76, 6...","[52, 40, 64, 56, 128, 32, 32, 28, 120, 140, 11...","[[1372.00668, 1376.5338, 1382.11196, 1388.5092...","[[0.16052, 10.18692, 25.7504, 43.01036, 53.002...","[[244.33804, 254.70008, 262.84788, 268.5794, 2..."
2,bth95,0612_12_24,106.823183,F,wt,CA1,RSU,0.80,2,"[[0.7246399999999085, 0.06400000000007822, 0.9...","[[0.009000000000000008, 0.09079999999999999, 0...","[[0.004040000000003374, 0.00435999999999126, 0...","[304, 404, 2272, 1728, 1340, 792, 2032, 356, 3...","[244, 412, 224, 208, 556, 360, 792, 212, 76, 6...","[52, 40, 64, 56, 128, 32, 32, 28, 120, 140, 11...","[[1372.08088, 1393.99256, 1404.38856, 1425.304...","[[0.10404, 12.97504, 25.74112, 41.95828, 54.63...","[[244.0164, 256.03008, 269.85796, 290.53736, 2..."
3,bth95,0612_12_24,106.823183,F,wt,CA1,FS,0.12,3,"[[0.008759999999938373, 0.006519999999909487, ...","[[0.3873199999999999, 0.58548, 0.72264, 0.1760...","[[0.32499999999998863, 0.07731999999998607, 0....","[304, 404, 2272, 1728, 1340, 792, 2032, 356, 3...","[244, 412, 224, 208, 556, 360, 792, 212, 76, 6...","[52, 40, 64, 56, 128, 32, 32, 28, 120, 140, 11...","[[1372.00772, 1396.03656, 1424.06872, 1448.574...","[[0.96852, 30.11964, 62.06772, 84.41344, 96.34...","[[244.1476, 256.17288, 270.25112, 284.92588, 2..."
4,bth95,0612_12_24,106.823183,F,wt,CA1,RSU,0.76,4,"[[1.687800000000152, 0.576720000000023, 0.0317...","[[0.77684, 0.7275999999999999, 0.0434400000000...","[[3.9684799999999996, 1.5845600000000104, 0.31...","[304, 404, 2272, 1728, 1340, 792, 2032, 356, 3...","[244, 412, 224, 208, 556, 360, 792, 212, 76, 6...","[52, 40, 64, 56, 128, 32, 32, 28, 120, 140, 11...","[[1372.72896, 1454.01116, 1473.9594, 1530.6408...","[[0.198, 37.16904, 92.40508, 128.295, 176.4734...","[[244.08476, 279.868, 292.19804], [736.49592, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112,bth95,0612_12_24,106.823183,F,wt,V1,FS,0.28,112,"[[0.014120000000048094, 0.028599999999869397, ...","[[0.6571200000000001, 1.61432, 1.5840800000000...","[[0.07743999999999573, 0.03916000000000963, 0....","[304, 404, 2272, 1728, 1340, 792, 2032, 356, 3...","[244, 412, 224, 208, 556, 360, 792, 212, 76, 6...","[52, 40, 64, 56, 128, 32, 32, 28, 120, 140, 11...","[[1372.46396, 1394.25604, 1418.70748, 1436.100...","[[0.7786, 48.82288, 85.7856, 124.24228, 183.46...","[[244.29344, 271.12252, 287.56076, 295.4254], ..."
113,bth95,0612_12_24,106.823183,F,wt,V1,FS,0.28,113,"[[0.11063999999987573, 0.4731200000001081, 0.7...","[[0.059360000000000024, 0.34092, 0.70556, 0.01...","[[0.5239600000000166, 0.46751999999997906, 0.5...","[304, 404, 2272, 1728, 1340, 792, 2032, 356, 3...","[244, 412, 224, 208, 556, 360, 792, 212, 76, 6...","[52, 40, 64, 56, 128, 32, 32, 28, 120, 140, 11...","[[1373.22684, 1448.32124, 1501.19604, 1563.247...","[[0.49316, 98.78924, 221.73684, 242.64896], [3...","[[244.73244, 295.14928], [736.85132, 775.64452..."
114,bth95,0612_12_24,106.823183,F,wt,V1,RSU,0.40,114,"[[0.2824399999999514, 0.9505200000000968, 0.65...","[[0.011079999999999757, 0.039839999999999876, ...","[[0.3281999999999812, 0.1679200000000094, 0.02...","[304, 404, 2272, 1728, 1340, 792, 2032, 356, 3...","[244, 412, 224, 208, 556, 360, 792, 212, 76, 6...","[52, 40, 64, 56, 128, 32, 32, 28, 120, 140, 11...","[[1374.11428, 1448.57728, 1480.48448, 1527.077...","[[2.43088, 109.75996, 184.67064, 242.59836], [...","[[244.49232, 295.31932], [738.15088, 775.8926]..."
115,bth95,0612_12_24,106.823183,F,wt,V1,FS,0.28,115,"[[0.23944000000005872, 0.007679999999936626, 1...","[[2.1525600000000003, 0.9844399999999998, 1.79...","[[0.1548400000000072, 0.18363999999999692, 0.3...","[304, 404, 2272, 1728, 1340, 792, 2032, 356, 3...","[244, 412, 224, 208, 556, 360, 792, 212, 76, 6...","[52, 40, 64, 56, 128, 32, 32, 28, 120, 140, 11...","[[1372.03808, 1409.37376, 1435.23412, 1457.380...","[[0.28508, 76.8326, 143.7212, 222.7894, 243.81...","[[244.70548, 285.2352, 295.66044], [736.66096,..."
116,bth95,0612_12_24,106.823183,F,wt,V1,RSU,0.68,116,"[[0.02327999999988606, 0.26652000000012777, 0....","[[0.0388, 0.18504, 0.31467999999999996, 0.5213...","[[1.9081999999999937, 0.46696000000000026, 0.9...","[304, 404, 2272, 1728, 1340, 792, 2032, 356, 3...","[244, 412, 224, 208, 556, 360, 792, 212, 76, 6...","[52, 40, 64, 56, 128, 32, 32, 28, 120, 140, 11...","[[1372.00116, 1391.2454, 1410.88904, 1430.3419...","[[0.06436, 30.29716, 61.82792, 94.40704, 113.9...","[[244.10604, 282.20248, 293.77408, 295.86248],..."

Working on bth100
Has 4 files to go through
got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,bth100,0623_0_12,97.126505,M,wt,CA1,FS,0.24,0,"[[0.013479999999999999, 0.01508, 0.02876, 0.02...","[[0.018159999999625143, 0.014519999999720312, ...","[[0.004520000000411528, 0.01415999999971973, 0...","[4448, 552, 296, 84, 636, 1456, 536, 340, 412,...","[196, 372, 104, 128, 408, 264, 744, 272, 204, ...","[92, 56, 92, 100, 48, 128, 56, 132, 120, 56, 6...","[[0.01216, 1.47244, 2.93124, 4.15024, 5.3548, ...","[[4480.01432, 4481.29344, 4483.19892, 4484.605...","[[4676.007, 4677.17388, 4678.46972, 4680.18336..."
1,bth100,0623_0_12,97.126505,M,wt,CA1,RSU,0.68,1,"[[6.36088, 9.69648, 3.031320000000001, 1.75600...","[[5.48279999999977, 0.3258800000003248, 4.9607...","[[4.0243200000004435, 6.700959999999213, 1.798...","[4448, 552, 296, 84, 636, 1456, 536, 340, 412,...","[196, 372, 104, 128, 408, 264, 744, 272, 204, ...","[92, 56, 92, 100, 48, 128, 56, 132, 120, 56, 6...","[[0.541, 283.2244, 391.9028, 460.5886, 595.916...","[[4481.19388, 4607.34628, 4673.51612], [4796.2...","[[4679.52236, 4753.93848], [6249.19464, 6301.4..."
2,bth100,0623_0_12,97.126505,M,wt,CA1,RSU,0.72,2,"[[135.5786, 118.28484, 39.00043999999997, 148....","[[24.617159999999785, 4.51068000000032, 0.0066...","[[0.05083999999988009, 49.960000000000036, 12....","[4448, 552, 296, 84, 636, 1456, 536, 340, 412,...","[196, 372, 104, 128, 408, 264, 744, 272, 204, ...","[92, 56, 92, 100, 48, 128, 56, 132, 120, 56, 6...","[[96.48312, 2523.72468, 3626.60548, 4432.96336...","[[4480.9842, 4664.72056], [4796.91736, 4891.33...","[[4679.6986, 4743.5798], [6248.06116], [7027.3..."
3,bth100,0623_0_12,97.126505,M,wt,CA1,FS,0.12,3,"[[0.003480000000000011, 0.15704, 0.10831999999...","[[0.044240000000172586, 0.06703999999990629, 0...","[[0.0885599999992337, 0.020160000000032596, 0....","[4448, 552, 296, 84, 636, 1456, 536, 340, 412,...","[196, 372, 104, 128, 408, 264, 744, 272, 204, ...","[92, 56, 92, 100, 48, 128, 56, 132, 120, 56, 6...","[[0.1646, 14.05884, 31.25408, 49.70924, 72.819...","[[4480.71244, 4519.50968, 4582.477, 4599.07176...","[[4676.12628, 4685.64196, 4696.02604, 4721.755..."
4,bth100,0623_0_12,97.126505,M,wt,CA1,RSU,0.64,4,"[[0.032280000000000086, 0.05599999999999994, 0...","[[0.003960000000006403, 0.049160000000483706, ...","[[0.05828000000019529, 0.008200000000215368, 0...","[4448, 552, 296, 84, 636, 1456, 536, 340, 412,...","[196, 372, 104, 128, 408, 264, 744, 272, 204, ...","[92, 56, 92, 100, 48, 128, 56, 132, 120, 56, 6...","[[0.64828, 22.199, 41.61716, 50.1686, 61.9816,...","[[4480.00044, 4486.94384, 4504.29372, 4527.383...","[[4676.00408, 4681.998, 4693.52416, 4708.05216..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,bth100,0623_0_12,97.126505,M,wt,V1,FS,0.20,83,"[[0.04507999999999998, 0.13668, 0.5686, 0.1271...","[[0.21679999999923893, 0.0038800000002083834, ...","[[0.3775600000008126, 0.14503999999942607, 0.0...","[4448, 552, 296, 84, 636, 1456, 536, 340, 412,...","[196, 372, 104, 128, 408, 264, 744, 272, 204, ...","[92, 56, 92, 100, 48, 128, 56, 132, 120, 56, 6...","[[0.15104, 28.0506, 53.31708, 75.5738, 95.5284...","[[4480.39176, 4486.2438, 4496.45636, 4594.7316...","[[4676.75484, 4757.61284, 4767.68912], [6249.3..."
84,bth100,0623_0_12,97.126505,M,wt,V1,FS,0.16,84,"[[0.20032, 0.04899999999999993, 0.016440000000...","[[0.028400000000146974, 0.06556000000000495, 0...","[[0.07732000000032713, 0.004759999999805586, 0...","[4448, 552, 296, 84, 636, 1456, 536, 340, 412,...","[196, 372, 104, 128, 408, 264, 744, 272, 204, ...","[92, 56, 92, 100, 48, 128, 56, 132, 120, 56, 6...","[[0.25984, 20.68344, 36.3144, 44.23084, 48.485...","[[4480.61496, 4484.12812, 4495.2914, 4540.5968...","[[4676.00088, 4678.4732, 4681.73588, 4683.5912..."
85,bth100,0623_0_12,97.126505,M,wt,V1,FS,0.16,85,"[[0.05744, 0.07379999999999999, 0.112320000000...","[[0.003560000000106811, 0.005280000000311702, ...","[[0.011120000000119035, 0.002599999999802094, ...","[4448, 552, 296, 84, 636, 1456, 536, 340, 412,...","[196, 372, 104, 128, 408, 264, 744, 272, 204, ...","[92, 56, 92, 100, 48, 128, 56, 132, 120, 56, 6...","[[0.04548, 7.59224, 19.85028, 27.32388, 39.375...","[[4480.61208, 4483.41816, 4488.95564, 4493.714...","[[4676.12724, 4680.10908, 4683.82908, 4686.516..."
86,bth100,0623_0_12,97.126505,M,wt,V1,FS,0.36,86,"[[0.10703999999999997, 0.24512, 0.205119999999...","[[0.2873200000003635, 0.8523999999997613, 0.57...","[[0.03120000000035361, 0.058399999999892316, 0...","[4448, 552, 296, 84, 636, 1456, 536, 340, 412,...","[196, 372, 104, 128, 408, 264, 744, 272, 204, ...","[92, 56, 92, 100, 48, 128, 56, 132, 120, 56, 6...","[[0.2716, 13.51752, 27.14708, 43.37312, 51.430...","[[4480.16072, 4625.71364, 4674.94616, 4675.875...","[[4676.08984, 4707.79912, 4754.26372, 4767.689..."
87,bth100,0623_0_12,97.126505,M,wt,V1,RSU,0.48,87,"[[0.06344, 0.027559999999999973, 0.01012000000...","[[2.3280800000002273, 0.8913599999996222, 1.21...","[[0.22027999999954773, 0.10404000000016822, 0....","[4448, 552, 296, 84, 636, 1456, 536, 340, 412,...","[196, 372, 104, 128, 408, 264, 744, 272, 204, ...","[92, 56, 92, 100, 48, 128, 56, 132, 120, 56, 6...","[[0.26728, 2.19824, 4.16752, 4.83844, 5.7538, ...","[[4480.11212, 4622.65928, 4670.08472, 4675.837...","[[4676.03736, 4716.17996, 4755.43116, 4767.725..."

got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,bth100,0623_12_24,97.626528,M,wt,CA1,FS,0.16,0,"[[0.00196, 0.011040000000000001, 0.01311999999...","[[0.08812000000000353, 0.030799999999999272, 0...","[[0.09748000000013235, 0.07315999999991618, 0....","[760, 284, 900, 1012, 700, 1348, 1120, 1096, 1...","[88, 96, 220, 156, 172, 92, 320, 436, 140, 344...","[116, 124, 64, 132, 92, 52, 24, 44, 160, 28, 1...","[[0.01532, 3.45916, 7.09908, 10.86868, 14.4729...","[[760.09576, 771.83748, 780.1656, 789.61712, 7...","[[1888.00884, 1891.76208, 1895.21736, 1898.950..."
1,bth100,0623_12_24,97.626528,M,wt,CA1,RSU,0.52,1,"[[0.12108, 0.19648, 0.16288000000000002, 0.004...","[[0.05171999999993204, 0.12376000000006115, 0....","[[0.5928800000001502, 0.17624000000000706, 0.1...","[760, 284, 900, 1012, 700, 1348, 1120, 1096, 1...","[88, 96, 220, 156, 172, 92, 320, 436, 140, 344...","[116, 124, 64, 132, 92, 52, 24, 44, 160, 28, 1...","[[0.01152, 14.39776, 28.09664, 39.42632, 49.59...","[[760.33392, 775.60532, 790.21716, 805.89048, ...","[[1888.55244, 1915.41228, 1930.762, 1942.08336..."
2,bth100,0623_12_24,97.626528,M,wt,CA1,RSU,0.40,2,"[[3.9955199999999995, 5.55096, 11.533719999999...","[[3.4342000000000326, 0.4741199999999708, 3.23...","[[0.8917999999998756, 0.09968000000003485, 0.0...","[760, 284, 900, 1012, 700, 1348, 1120, 1096, 1...","[88, 96, 220, 156, 172, 92, 320, 436, 140, 344...","[116, 124, 64, 132, 92, 52, 24, 44, 160, 28, 1...","[[3.59064, 469.13716, 754.72488], [1230.43332,...","[[760.11096, 847.87372], [881.01456, 973.37532...","[[1889.16308, 1955.00248, 1998.93536], [3334.2..."
3,bth100,0623_12_24,97.626528,M,wt,CA1,RSU,0.64,3,"[[0.31123999999999996, 0.30167999999999995, 0....","[[0.13780000000008386, 0.04351999999994405, 0....","[[0.32787999999982276, 0.031240000000025248, 0...","[760, 284, 900, 1012, 700, 1348, 1120, 1096, 1...","[88, 96, 220, 156, 172, 92, 320, 436, 140, 344...","[116, 124, 64, 132, 92, 52, 24, 44, 160, 28, 1...","[[1.05068, 36.1058, 49.92932, 71.57276, 95.020...","[[760.06, 770.69956, 785.06604, 803.178, 820.9...","[[1888.15216, 1908.75248, 1923.03864, 1936.951..."
4,bth100,0623_12_24,97.626528,M,wt,CA1,RSU,0.56,4,"[[34.154599999999995, 1.1264800000000008, 4.40...","[[23.36959999999999, 7.373119999999972, 17.725...","[[27.09104000000002, 1.062599999999975, 4.8654...","[760, 284, 900, 1012, 700, 1348, 1120, 1096, 1...","[88, 96, 220, 156, 172, 92, 320, 436, 140, 344...","[116, 124, 64, 132, 92, 52, 24, 44, 160, 28, 1...","[[52.7506, 722.74916], [1242.57808, 1494.54276...","[[791.53652, 840.88456], [906.47344, 975.7516]...","[[1891.06288, 1997.844], [3336.13264, 3455.124..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,bth100,0623_12_24,97.626528,M,wt,V1,FS,0.20,81,"[[0.00452, 0.00936, 0.007559999999999997, 0.01...","[[0.032359999999926004, 0.02296000000001186, 0...","[[0.027839999999969223, 0.06544000000008054, 0...","[760, 284, 900, 1012, 700, 1348, 1120, 1096, 1...","[88, 96, 220, 156, 172, 92, 320, 436, 140, 344...","[116, 124, 64, 132, 92, 52, 24, 44, 160, 28, 1...","[[0.01216, 2.01352, 4.0306, 5.8596, 7.86184, 1...","[[760.00516, 763.24504, 766.53872, 770.35892, ...","[[1888.0128, 1889.95216, 1891.94496, 1893.9566..."
82,bth100,0623_12_24,97.626528,M,wt,V1,RSU,0.48,82,"[[0.6609999999999999, 0.010160000000000169, 1....","[[0.9662799999999834, 0.5746000000000322, 3.92...","[[0.7208800000000792, 2.8949199999999564, 0.66...","[760, 284, 900, 1012, 700, 1348, 1120, 1096, 1...","[88, 96, 220, 156, 172, 92, 320, 436, 140, 344...","[116, 124, 64, 132, 92, 52, 24, 44, 160, 28, 1...","[[0.36312, 49.74828, 89.509, 123.78748, 151.91...","[[764.59628, 847.32748, 847.9766], [880.22772,...","[[1888.78892, 1934.77036, 1968.75996, 2003.561..."
83,bth100,0623_12_24,97.626528,M,wt,V1,FS,0.20,83,"[[0.3482, 0.07028000000000001, 0.2117599999999...","[[0.6077199999999721, 0.543480000000045, 0.716...","[[0.4977599999999711, 0.0746799999999439, 0.56...","[760, 284, 900, 1012, 700, 1348, 1120, 1096, 1...","[88, 96, 220, 156, 172, 92, 320, 436, 140, 344...","[116, 124, 64, 132, 92, 52, 24, 44, 160, 28, 1...","[[0.00616, 19.21308, 36.64704, 53.63628, 69.33...","[[760.12328, 803.67136, 847.86816], [880.032, ...","[[1888.2106, 1910.01672, 1930.65268, 1954.6286..."
84,bth100,0623_12_24,97.626528,M,wt,V1,FS,0.32,84,"[[0.9232, 0.6315199999999999, 0.07848000000000...","[[0.5127599999999575, 0.09492000000000189, 1.1...","[[0.20019999999999527, 0.4277600000000348, 0.0...","[760, 284, 900, 1012, 700, 1348, 1120, 1096, 1...","[88, 96, 220, 156, 172, 92, 320, 436, 140, 344...","[116, 124, 64, 132, 92, 52, 24, 44, 160, 28, 1...","[[0.54708, 40.33384, 74.28896, 109.01624, 137....","[[761.05088, 802.38788, 822.08108, 843.02644, ...","[[1888.09356, 1899.275, 1913.0668, 1924.20236,..."
85,bth100,0623_12_24,97.626528,M,wt,V1,RSU,0.52,85,"[[0.3325199999999999, 0.03268000000000004, 0.0...","[[0.23367999999993572, 0.002119999999990796, 1...","[[0.025279999999838765, 0.09248000000002321, 0...","[760, 284, 900, 1012, 700, 1348, 1120, 1096, 1...","[88, 96, 220, 156, 172, 92, 320, 436, 140, 344...","[116, 124, 64, 132, 92, 52, 24, 44, 160, 28, 1...","[[0.22972, 10.75492, 22.40952, 32.13928, 43.23...","[[760.43992, 776.91012, 793.41444, 811.57196, ...","[[1888.18712, 1900.8774, 1913.4416, 1921.95172..."

got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,bth100,0624_0_12,98.187037,M,wt,CA1,RSU,0.52,0,"[[0.49512, 1.2418400000000003, 0.1206399999999...","[[0.21515999999996893, 0.026039999999966312, 0...","[[1.3489199999999073, 1.434479999999894, 0.657...","[400, 1344, 56, 256, 2328, 396, 1088, 256, 632...","[748, 496, 208, 704, 608, 132, 1072, 1072, 444...","[48, 60, 52, 220, 24, 20, 84, 52, 20, 28, 20, ...","[[0.31228, 62.92228, 145.27932, 190.00316, 236...","[[1996.833, 2078.86012, 2167.73916, 2328.71804...","[[2744.05456, 2791.91], [3351.82384, 3403.7572..."
1,bth100,0624_0_12,98.187037,M,wt,CA1,RSU,0.64,1,"[[0.4216800000000003, 0.3255600000000003, 0.56...","[[1.979280000000017, 1.270240000000058, 0.9627...","[[21.82448000000022, 0.17671999999993204, 4.17...","[400, 1344, 56, 256, 2328, 396, 1088, 256, 632...","[748, 496, 208, 704, 608, 132, 1072, 1072, 444...","[48, 60, 52, 220, 24, 20, 84, 52, 20, 28, 20, ...","[[6.32168, 236.44084, 291.98144, 372.262, 399....","[[1999.97976, 2164.5922, 2321.87324, 2524.2451...","[[2749.07176, 2791.97052], [3346.48112, 3373.3..."
2,bth100,0624_0_12,98.187037,M,wt,CA1,FS,0.24,2,"[[0.2242, 0.40735999999999994, 0.94112, 0.5941...","[[0.10572000000001935, 0.04927999999995336, 0....","[[0.2140799999997398, 0.026920000000245636, 0....","[400, 1344, 56, 256, 2328, 396, 1088, 256, 632...","[748, 496, 208, 704, 608, 132, 1072, 1072, 444...","[48, 60, 52, 220, 24, 20, 84, 52, 20, 28, 20, ...","[[0.31512, 22.27644, 42.65252, 64.48636, 81.29...","[[1996.0532, 2001.56284, 2004.58892, 2008.2158...","[[2744.11052, 2752.7358, 2760.5368, 2772.47724..."
3,bth100,0624_0_12,98.187037,M,wt,CA1,RSU,0.64,3,"[[0.08784, 0.34644, 0.04496, 0.252999999999999...","[[0.0065600000000358705, 0.25499999999988177, ...","[[0.4331600000000435, 0.6678399999996145, 0.35...","[400, 1344, 56, 256, 2328, 396, 1088, 256, 632...","[748, 496, 208, 704, 608, 132, 1072, 1072, 444...","[48, 60, 52, 220, 24, 20, 84, 52, 20, 28, 20, ...","[[0.01684, 20.32564, 39.8282, 56.45168, 75.578...","[[1996.0806, 2030.57468, 2064.78504, 2099.9717...","[[2744.10388, 2774.47096, 2789.85208], [3344.1..."
4,bth100,0624_0_12,98.187037,M,wt,CA1,RSU,0.48,4,"[[0.10651999999999999, 0.10172000000000003, 0....","[[0.321920000000091, 0.6134799999999814, 0.625...","[[4.153760000000148, 10.17452000000003, 0.2336...","[400, 1344, 56, 256, 2328, 396, 1088, 256, 632...","[748, 496, 208, 704, 608, 132, 1072, 1072, 444...","[48, 60, 52, 220, 24, 20, 84, 52, 20, 28, 20, ...","[[0.07692, 63.1494, 157.99788, 255.81748, 372....","[[1996.69844, 2098.37524, 2196.75204, 2352.937...","[[2744.48404, 2790.86588], [3345.24848, 3402.7..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,bth100,0624_0_12,98.187037,M,wt,V1,FS,0.28,93,"[[0.024599999999999997, 0.021599999999999994, ...","[[0.2716400000001613, 0.0051199999998061685, 0...","[[0.007920000000012806, 0.08611999999993714, 0...","[400, 1344, 56, 256, 2328, 396, 1088, 256, 632...","[748, 496, 208, 704, 608, 132, 1072, 1072, 444...","[48, 60, 52, 220, 24, 20, 84, 52, 20, 28, 20, ...","[[0.0704, 7.91516, 14.69508, 18.90348, 22.9378...","[[1996.23112, 2002.61064, 2025.44752, 2036.865...","[[2744.3654, 2755.83204, 2763.99208, 2776.0762..."
94,bth100,0624_0_12,98.187037,M,wt,V1,FS,0.28,94,"[[0.08967999999999998, 0.14088000000000003, 0....","[[0.6038800000001174, 0.9746399999999085, 0.63...","[[0.23471999999992477, 0.1178000000004431, 0.0...","[400, 1344, 56, 256, 2328, 396, 1088, 256, 632...","[748, 496, 208, 704, 608, 132, 1072, 1072, 444...","[48, 60, 52, 220, 24, 20, 84, 52, 20, 28, 20, ...","[[0.038, 16.24452, 28.43676, 58.4462, 71.3236,...","[[1996.94916, 2093.61924, 2168.96412, 2247.810...","[[2744.16288, 2762.37084, 2778.47244, 2791.997..."
95,bth100,0624_0_12,98.187037,M,wt,V1,FS,0.24,95,"[[0.007200000000000001, 0.02096, 0.02308000000...","[[0.0027199999999538704, 0.007440000000087821,...","[[0.005639999999857537, 0.014000000000123691, ...","[400, 1344, 56, 256, 2328, 396, 1088, 256, 632...","[748, 496, 208, 704, 608, 132, 1072, 1072, 444...","[48, 60, 52, 220, 24, 20, 84, 52, 20, 28, 20, ...","[[0.00164, 1.3352, 4.27884, 8.42808, 12.21628,...","[[1996.13852, 1997.90272, 1999.8346, 2002.4074...","[[2744.01832, 2747.00752, 2751.13356, 2753.922..."
96,bth100,0624_0_12,98.187037,M,wt,V1,FS,0.28,96,"[[0.010999999999999996, 0.006840000000000006, ...","[[0.028520000000071377, 0.0686399999999594, 0....","[[0.02907999999979438, 0.0263199999999415, 0.2...","[400, 1344, 56, 256, 2328, 396, 1088, 256, 632...","[748, 496, 208, 704, 608, 132, 1072, 1072, 444...","[48, 60, 52, 220, 24, 20, 84, 52, 20, 28, 20, ...","[[0.04884, 4.42228, 12.07252, 14.8792, 18.0014...","[[1996.51424, 2050.22324, 2084.09612, 2098.005...","[[2744.12892, 2751.60444, 2756.3904, 2759.6332..."
97,bth100,0624_0_12,98.187037,M,wt,V1,FS,0.36,97,"[[0.11880000000000002, 0.11175999999999997, 0....","[[2.257240000000138, 0.3051599999998871, 0.067...","[[0.009120000000166328, 0.43727999999964595, 0...","[400, 1344, 56, 256, 2328, 396, 1088, 256, 632...","[748, 496, 208, 704, 608, 132, 1072, 1072, 444...","[48, 60, 52, 220, 24, 20, 84, 52, 20, 28, 20, ...","[[0.03796, 21.83208, 66.19208, 105.15328, 166....","[[1996.45688, 2149.58904, 2272.46188, 2410.502...","[[2744.43568, 2778.29772, 2791.99744], [3344.2..."

got initial info

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,bth100,0624_12_24,98.68706,M,wt,CA1,FS,0.12,0,"[[0.025560000000041327, 0.013760000000047512, ...","[[0.0024400000000000047, 0.0023199999999999957...","[[0.012600000000020373, 0.0058399999999210195,...","[5852, 336, 168, 2548, 676, 3524, 3780, 448, 3...","[592, 692, 68, 484, 324, 196, 380, 472, 256, 5...","[76, 28, 40, 88, 40, 72, 120, 104, 100, 88, 44...","[[668.02812, 670.26996, 671.89888, 673.5458, 6...","[[0.04176, 2.55352, 6.58892, 9.05928, 12.22428...","[[592.00368, 595.76548, 600.50304, 603.74572, ..."
1,bth100,0624_12_24,98.68706,M,wt,CA1,FS,0.12,1,"[[0.11644000000001142, 0.03663999999992029, 0....","[[0.16071999999999997, 0.00804000000000002, 0....","[[0.007000000000061846, 0.035520000000019536, ...","[5852, 336, 168, 2548, 676, 3524, 3780, 448, 3...","[592, 692, 68, 484, 324, 196, 380, 472, 256, 5...","[76, 28, 40, 88, 40, 72, 120, 104, 100, 88, 44...","[[668.0832, 679.6716, 684.66272, 687.21084, 69...","[[0.0364, 15.34164, 22.97888, 33.68256, 44.257...","[[592.13852, 598.03596, 605.5396, 611.5196, 61..."
2,bth100,0624_12_24,98.68706,M,wt,CA1,FS,0.12,2,"[[0.12408000000004904, 0.5085599999999886, 0.5...","[[6.20472, 4.413679999999999, 1.21828, 2.12264...","[[0.18988000000001648, 1.0691600000000108, 1.3...","[5852, 336, 168, 2548, 676, 3524, 3780, 448, 3...","[592, 692, 68, 484, 324, 196, 380, 472, 256, 5...","[76, 28, 40, 88, 40, 72, 120, 104, 100, 88, 44...","[[668.18252, 765.64232, 874.85624, 982.93896, ...","[[0.64512, 107.75448, 195.08272, 345.67664, 46...","[[592.3836, 667.98692], [7225.85152, 7239.5913..."
3,bth100,0624_12_24,98.68706,M,wt,CA1,RSU,0.68,3,"[[1.084920000000011, 6.257839999999987, 7.3813...","[[2.22504, 2.5909199999999997, 0.0122800000000...","[[0.6865199999999732, 5.437440000000038, 0.467...","[5852, 336, 168, 2548, 676, 3524, 3780, 448, 3...","[592, 692, 68, 484, 324, 196, 380, 472, 256, 5...","[76, 28, 40, 88, 40, 72, 120, 104, 100, 88, 44...","[[674.59012, 923.73884, 984.71692, 1006.88036,...","[[1.84264, 227.45684, 416.10672, 571.7464, 591...","[[594.61712, 654.12812], [7217.08904, 7220.399..."
4,bth100,0624_12_24,98.68706,M,wt,CA1,FS,0.24,4,"[[0.01984000000004471, 0.008800000000064756, 0...","[[0.02068, 0.013920000000000002, 0.01911999999...","[[0.010480000000029577, 0.02255999999999858, 0...","[5852, 336, 168, 2548, 676, 3524, 3780, 448, 3...","[592, 692, 68, 484, 324, 196, 380, 472, 256, 5...","[76, 28, 40, 88, 40, 72, 120, 104, 100, 88, 44...","[[668.03672, 669.97724, 671.94212, 674.09624, ...","[[0.0028, 1.87252, 3.63784, 5.68228, 7.51496, ...","[[592.0144, 593.792, 595.84156, 598.016, 599.4..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,bth100,0624_12_24,98.68706,M,wt,V1,RSU,0.68,90,"[[0.020479999999906795, 0.4212400000000116, 0....","[[1.57676, 0.04683999999999999, 0.407960000000...","[[1.6818399999999656, 0.047159999999962565, 0....","[5852, 336, 168, 2548, 676, 3524, 3780, 448, 3...","[592, 692, 68, 484, 324, 196, 380, 472, 256, 5...","[76, 28, 40, 88, 40, 72, 120, 104, 100, 88, 44...","[[668.57176, 707.01432, 740.97008, 767.3638, 7...","[[1.30304, 45.60452, 92.60128, 153.071, 202.79...","[[592.2716, 636.20772, 667.88588], [7214.34452..."
91,bth100,0624_12_24,98.68706,M,wt,V1,RSU,0.56,91,"[[0.1151199999999335, 0.12744000000009237, 0.0...","[[0.46224, 1.79184, 0.24311999999999978, 0.452...","[[1.3544399999999541, 1.002520000000004, 0.383...","[5852, 336, 168, 2548, 676, 3524, 3780, 448, 3...","[592, 692, 68, 484, 324, 196, 380, 472, 256, 5...","[76, 28, 40, 88, 40, 72, 120, 104, 100, 88, 44...","[[668.24004, 694.74624, 733.93376, 754.5682, 7...","[[0.79468, 44.809, 98.434, 153.49844, 192.7348...","[[592.14768, 617.384, 640.14308, 656.65148, 66..."
92,bth100,0624_12_24,98.68706,M,wt,V1,RSU,0.52,92,"[[0.2658400000000256, 0.22303999999996904, 0.1...","[[0.04723999999999995, 0.015519999999999978, 1...","[[0.11188000000004195, 0.050520000000005894, 1...","[5852, 336, 168, 2548, 676, 3524, 3780, 448, 3...","[592, 692, 68, 484, 324, 196, 380, 472, 256, 5...","[76, 28, 40, 88, 40, 72, 120, 104, 100, 88, 44...","[[668.0002, 691.67572, 726.4122, 752.80192, 77...","[[0.83096, 18.63536, 35.94724, 58.99576, 72.86...","[[592.35984, 608.945, 626.10488, 651.55616, 66..."
93,bth100,0624_12_24,98.68706,M,wt,V1,FS,0.24,93,"[[0.0017599999999902138, 0.0036400000000185173...","[[0.05371999999999999, 0.006599999999999939, 0...","[[0.015319999999974243, 0.00952000000006592, 0...","[5852, 336, 168, 2548, 676, 3524, 3780, 448, 3...","[592, 692, 68, 484, 324, 196, 380, 472, 256, 5...","[76, 28, 40, 88, 40, 72, 120, 104, 100, 88, 44...","[[668.059, 671.24976, 674.65804, 677.55264, 68...","[[0.57132, 8.88216, 10.725, 12.5402, 14.50152,...","[[592.0422, 596.30928, 598.21452, 600.23812, 6..."
94,bth100,0624_12_24,98.68706,M,wt,V1,RSU,0.64,94,"[[0.37239999999997053, 0.11788000000001375, 0....","[[0.07823999999999998, 0.37315999999999994, 0....","[[0.012119999999981701, 1.1850399999999581, 0....","[5852, 336, 168, 2548, 676, 3524, 3780, 448, 3...","[592, 692, 68, 484, 324, 196, 380, 472, 256, 5...","[76, 28, 40, 88, 40, 72, 120, 104, 100, 88, 44...","[[668.07948, 684.70712, 698.44004, 709.13184, ...","[[0.60892, 24.43068, 56.51936, 75.62352, 103.3...","[[592.27164, 610.02992, 623.00304, 639.55592, ..."

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,caf69,1228_0_12,358.152546,F,wt,ACC,RSU,0.68,0,"[[0.00592, 0.00132, 0.004360000000000001, 0.02...","[[0.15272000000004482, 0.07171999999991385, 0....","[[0.15104000000019369, 0.11567999999988388, 0....","[3320, 320, 20, 1708, 588, 92, 740, 252, 68, 3...","[520, 440, 40, 240, 180, 200, 180, 220, 180, 6...","[160, 40, 100, 20, 40, 60, 100, 40, 108, 80, 3...","[[0.00532, 8.30984, 16.46344, 25.3846, 37.0028...","[[3320.05296, 3328.55344, 3339.40532, 3345.584...","[[3841.05772, 3868.16824, 3891.42572, 3909.411..."
1,caf69,1228_0_12,358.152546,F,wt,ACC,RSU,0.68,1,"[[0.12224, 6.87172, 1.7081599999999995, 2.1617...","[[14.897280000000137, 1.6376399999999194, 6.17...","[[3.8209999999999127, 4.546280000000024, 3.097...","[3320, 320, 20, 1708, 588, 92, 740, 252, 68, 3...","[520, 440, 40, 240, 180, 200, 180, 220, 180, 6...","[160, 40, 100, 20, 40, 60, 100, 40, 108, 80, 3...","[[4e-05, 219.53304, 509.02504, 573.5778, 737.8...","[[3329.31148, 3785.66544], [4008.16452, 4438.9...","[[3859.45592, 3980.94744], [4470.14316, 4478.7..."
2,caf69,1228_0_12,358.152546,F,wt,ACC,RSU,0.52,2,"[[0.06476000000000001, 0.017119999999999996, 0...","[[0.05519999999978609, 0.8142000000002554, 0.0...","[[0.05375999999978376, 0.286200000000008, 0.08...","[3320, 320, 20, 1708, 588, 92, 740, 252, 68, 3...","[520, 440, 40, 240, 180, 200, 180, 220, 180, 6...","[160, 40, 100, 20, 40, 60, 100, 40, 108, 80, 3...","[[0.01684, 22.50024, 46.03396, 66.695, 89.9888...","[[3320.1932, 3372.29616, 3432.87716, 3497.7676...","[[3840.76872, 3894.55876, 3944.32072, 3989.872..."
3,caf69,1228_0_12,358.152546,F,wt,ACC,RSU,0.52,3,"[[0.24439999999999998, 0.27224000000000004, 0....","[[2.0253600000000915, 0.87920000000031, 0.7080...","[[0.6291599999999562, 0.11724000000003798, 0.7...","[3320, 320, 20, 1708, 588, 92, 740, 252, 68, 3...","[520, 440, 40, 240, 180, 200, 180, 220, 180, 6...","[160, 40, 100, 20, 40, 60, 100, 40, 108, 80, 3...","[[0.00892, 22.6154, 48.60976, 73.74956, 91.015...","[[3320.42208, 3368.56088, 3431.02976, 3503.225...","[[3840.58268, 3899.72988, 3942.88864, 3976.861..."
4,caf69,1228_0_12,358.152546,F,wt,ACC,RSU,0.48,4,"[[0.15028000000000002, 0.34468000000000004, 0....","[[0.59996000000001, 0.4675600000000486, 0.8568...","[[2.2804799999998977, 0.46628000000009706, 1.0...","[3320, 320, 20, 1708, 588, 92, 740, 252, 68, 3...","[520, 440, 40, 240, 180, 200, 180, 220, 180, 6...","[160, 40, 100, 20, 40, 60, 100, 40, 108, 80, 3...","[[0.25464, 28.47056, 53.57136, 85.74888, 91.68...","[[3320.71772, 3373.96056, 3425.57584, 3523.176...","[[3841.0414, 3907.79736, 3946.2996, 3986.7532,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5470,bth100,0624_12_24,98.687060,M,wt,V1,RSU,0.68,90,"[[0.020479999999906795, 0.4212400000000116, 0....","[[1.57676, 0.04683999999999999, 0.407960000000...","[[1.6818399999999656, 0.047159999999962565, 0....","[5852, 336, 168, 2548, 676, 3524, 3780, 448, 3...","[592, 692, 68, 484, 324, 196, 380, 472, 256, 5...","[76, 28, 40, 88, 40, 72, 120, 104, 100, 88, 44...","[[668.57176, 707.01432, 740.97008, 767.3638, 7...","[[1.30304, 45.60452, 92.60128, 153.071, 202.79...","[[592.2716, 636.20772, 667.88588], [7214.34452..."
5471,bth100,0624_12_24,98.687060,M,wt,V1,RSU,0.56,91,"[[0.1151199999999335, 0.12744000000009237, 0.0...","[[0.46224, 1.79184, 0.24311999999999978, 0.452...","[[1.3544399999999541, 1.002520000000004, 0.383...","[5852, 336, 168, 2548, 676, 3524, 3780, 448, 3...","[592, 692, 68, 484, 324, 196, 380, 472, 256, 5...","[76, 28, 40, 88, 40, 72, 120, 104, 100, 88, 44...","[[668.24004, 694.74624, 733.93376, 754.5682, 7...","[[0.79468, 44.809, 98.434, 153.49844, 192.7348...","[[592.14768, 617.384, 640.14308, 656.65148, 66..."
5472,bth100,0624_12_24,98.687060,M,wt,V1,RSU,0.52,92,"[[0.2658400000000256, 0.22303999999996904, 0.1...","[[0.04723999999999995, 0.015519999999999978, 1...","[[0.11188000000004195, 0.050520000000005894, 1...","[5852, 336, 168, 2548, 676, 3524, 3780, 448, 3...","[592, 692, 68, 484, 324, 196, 380, 472, 256, 5...","[76, 28, 40, 88, 40, 72, 120, 104, 100, 88, 44...","[[668.0002, 691.67572, 726.4122, 752.80192, 77...","[[0.83096, 18.63536, 35.94724, 58.99576, 72.86...","[[592.35984, 608.945, 626.10488, 651.55616, 66..."
5473,bth100,0624_12_24,98.687060,M,wt,V1,FS,0.24,93,"[[0.0017599999999902138, 0.0036400000000185173...","[[0.05371999999999999, 0.006599999999999939, 0...","[[0.015319999999974243, 0.00952000000006592, 0...","[5852, 336, 168, 2548, 676, 3524, 3780, 448, 3...","[592, 692, 68, 484, 324, 196, 380, 472, 256, 5...","[76, 28, 40, 88, 40, 72, 120, 104, 100, 88, 44...","[[668.059, 671.24976, 674.65804, 677.55264, 68...","[[0.57132, 8.88216, 10.725, 12.5402, 14.50152,...","[[592.0422, 596.30928, 598.21452, 600.23812, 6..."
5474,bth100,0624_12_24,98.687060,M,wt,V1,RSU,0.64,94,"[[0.37239999999997053, 0.11788000000001375, 0....","[[0.07823999999999998, 0.37315999999999994, 0....","[[0.012119999999981701, 1.1850399999999581, 0....","[5852, 336, 168, 2548, 676, 3524, 3780, 448, 3...","[592, 692, 68, 484, 324, 196, 380, 472, 256, 5...","[76, 28, 40, 88, 40, 72, 120, 104, 100, 88, 44...","[[668.07948, 684.70712, 698.44004, 709.13184, ...","[[0.60892, 24.43068, 56.51936, 75.62352, 103.3...","[[592.27164, 610.02992, 623.00304, 639.55592, ..."

In [23]:
all_animal_isi_df

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,caf69,1228_0_12,358.152546,F,wt,ACC,RSU,0.68,0,"[[0.00592, 0.00132, 0.004360000000000001, 0.02...","[[0.15272000000004482, 0.07171999999991385, 0....","[[0.15104000000019369, 0.11567999999988388, 0....","[3320, 320, 20, 1708, 588, 92, 740, 252, 68, 3...","[520, 440, 40, 240, 180, 200, 180, 220, 180, 6...","[160, 40, 100, 20, 40, 60, 100, 40, 108, 80, 3...","[[0.00532, 8.30984, 16.46344, 25.3846, 37.0028...","[[3320.05296, 3328.55344, 3339.40532, 3345.584...","[[3841.05772, 3868.16824, 3891.42572, 3909.411..."
1,caf69,1228_0_12,358.152546,F,wt,ACC,RSU,0.68,1,"[[0.12224, 6.87172, 1.7081599999999995, 2.1617...","[[14.897280000000137, 1.6376399999999194, 6.17...","[[3.8209999999999127, 4.546280000000024, 3.097...","[3320, 320, 20, 1708, 588, 92, 740, 252, 68, 3...","[520, 440, 40, 240, 180, 200, 180, 220, 180, 6...","[160, 40, 100, 20, 40, 60, 100, 40, 108, 80, 3...","[[4e-05, 219.53304, 509.02504, 573.5778, 737.8...","[[3329.31148, 3785.66544], [4008.16452, 4438.9...","[[3859.45592, 3980.94744], [4470.14316, 4478.7..."
2,caf69,1228_0_12,358.152546,F,wt,ACC,RSU,0.52,2,"[[0.06476000000000001, 0.017119999999999996, 0...","[[0.05519999999978609, 0.8142000000002554, 0.0...","[[0.05375999999978376, 0.286200000000008, 0.08...","[3320, 320, 20, 1708, 588, 92, 740, 252, 68, 3...","[520, 440, 40, 240, 180, 200, 180, 220, 180, 6...","[160, 40, 100, 20, 40, 60, 100, 40, 108, 80, 3...","[[0.01684, 22.50024, 46.03396, 66.695, 89.9888...","[[3320.1932, 3372.29616, 3432.87716, 3497.7676...","[[3840.76872, 3894.55876, 3944.32072, 3989.872..."
3,caf69,1228_0_12,358.152546,F,wt,ACC,RSU,0.52,3,"[[0.24439999999999998, 0.27224000000000004, 0....","[[2.0253600000000915, 0.87920000000031, 0.7080...","[[0.6291599999999562, 0.11724000000003798, 0.7...","[3320, 320, 20, 1708, 588, 92, 740, 252, 68, 3...","[520, 440, 40, 240, 180, 200, 180, 220, 180, 6...","[160, 40, 100, 20, 40, 60, 100, 40, 108, 80, 3...","[[0.00892, 22.6154, 48.60976, 73.74956, 91.015...","[[3320.42208, 3368.56088, 3431.02976, 3503.225...","[[3840.58268, 3899.72988, 3942.88864, 3976.861..."
4,caf69,1228_0_12,358.152546,F,wt,ACC,RSU,0.48,4,"[[0.15028000000000002, 0.34468000000000004, 0....","[[0.59996000000001, 0.4675600000000486, 0.8568...","[[2.2804799999998977, 0.46628000000009706, 1.0...","[3320, 320, 20, 1708, 588, 92, 740, 252, 68, 3...","[520, 440, 40, 240, 180, 200, 180, 220, 180, 6...","[160, 40, 100, 20, 40, 60, 100, 40, 108, 80, 3...","[[0.25464, 28.47056, 53.57136, 85.74888, 91.68...","[[3320.71772, 3373.96056, 3425.57584, 3523.176...","[[3841.0414, 3907.79736, 3946.2996, 3986.7532,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5470,bth100,0624_12_24,98.687060,M,wt,V1,RSU,0.68,90,"[[0.020479999999906795, 0.4212400000000116, 0....","[[1.57676, 0.04683999999999999, 0.407960000000...","[[1.6818399999999656, 0.047159999999962565, 0....","[5852, 336, 168, 2548, 676, 3524, 3780, 448, 3...","[592, 692, 68, 484, 324, 196, 380, 472, 256, 5...","[76, 28, 40, 88, 40, 72, 120, 104, 100, 88, 44...","[[668.57176, 707.01432, 740.97008, 767.3638, 7...","[[1.30304, 45.60452, 92.60128, 153.071, 202.79...","[[592.2716, 636.20772, 667.88588], [7214.34452..."
5471,bth100,0624_12_24,98.687060,M,wt,V1,RSU,0.56,91,"[[0.1151199999999335, 0.12744000000009237, 0.0...","[[0.46224, 1.79184, 0.24311999999999978, 0.452...","[[1.3544399999999541, 1.002520000000004, 0.383...","[5852, 336, 168, 2548, 676, 3524, 3780, 448, 3...","[592, 692, 68, 484, 324, 196, 380, 472, 256, 5...","[76, 28, 40, 88, 40, 72, 120, 104, 100, 88, 44...","[[668.24004, 694.74624, 733.93376, 754.5682, 7...","[[0.79468, 44.809, 98.434, 153.49844, 192.7348...","[[592.14768, 617.384, 640.14308, 656.65148, 66..."
5472,bth100,0624_12_24,98.687060,M,wt,V1,RSU,0.52,92,"[[0.2658400000000256, 0.22303999999996904, 0.1...","[[0.04723999999999995, 0.015519999999999978, 1...","[[0.11188000000004195, 0.050520000000005894, 1...","[5852, 336, 168, 2548, 676, 3524, 3780, 448, 3...","[592, 692, 68, 484, 324, 196, 380, 472, 256, 5...","[76, 28, 40, 88, 40, 72, 120, 104, 100, 88, 44...","[[668.0002, 691.67572, 726.4122, 752.80192, 77...","[[0.83096, 18.63536, 35.94724, 58.99576, 72.86...","[[592.35984, 608.945, 626.10488, 651.55616, 66..."
5473,bth100,0624_12_24,98.687060,M,wt,V1,FS,0.24,93,"[[0.0017599999999902138, 0.0036400000000185173...","[[0.05371999999999999, 0.006599999999999939, 0...","[[0.015319999999974243, 0.00952000000006592, 0...","[5852, 336, 168, 2548, 676, 3524, 3780, 448, 3...","[592, 692, 68, 484, 324, 196, 380, 472, 256, 5...","[76, 28, 40, 88, 40, 72, 120, 104, 100, 88, 44...","[[668.059, 671.24976, 674.65804, 677.55264, 68...","[[0.57132, 8.88216, 10.725, 12.5402, 14.50152,...","[[592.0422, 596.30928, 598.21452, 600.23812, 6..."
5474,bth100,0624_12_24,98.687060,M,wt,V1,RSU,0.64,94,"[[0.37239999999997053, 0.11788000000001375, 0....","[[0.07823999999999998, 0.37315999999999994, 0....","[[0.012119999999981701, 1.1850399999999581, 0....","[5852, 336, 168, 2548, 676, 3524, 3780, 448, 3...","[592, 692, 68, 484, 324, 196, 380, 472, 256, 5...","[76, 28, 40, 88, 40, 72, 120, 104, 100, 88, 44...","[[668.07948, 684.70712, 698.44004, 709.13184, ...","[[0.60892, 24.43068, 56.51936, 75.62352, 103.3...","[[592.27164, 610.02992, 623.00304, 639.55592, ..."

In [24]:
import pickle
begin = "/media/HlabShare/Toby_work/sleep_indiv_neuron/"
with open(f'{begin}full_animal_isi.pkl', 'wb') as file:
    pickle.dump(all_animal_isi_df, file)

In [27]:
filtered_dataset = all_animal_isi_df
valid_days = {'caf69':'', 'caf71':'0103','caf73':'0120','caf74':'0125', 'caf75':'0125',
             'caf77':'0202','caf81':'0304','caf82':'0304',
             'zbr106':'0223','zbr113':'0513','zbr114':'0426','zbr117':'','zbr118':'0522',
             'zbr119':'0604','bth90':'0323','bth95':'0611','bth100':'0624'}
for animal in valid_days:
    for file in filtered_dataset[filtered_dataset['animal']==animal]['epoch'].unique():
        if valid_days[animal] not in file:
            filtered_dataset = filtered_dataset[filtered_dataset['epoch']!=file]
filtered_dataset = filtered_dataset[filtered_dataset['animal'].isin(valid_days.keys())]
display(filtered_dataset)

,animal,epoch,age,sex,geno,brain_region,cell_type,peak_latency,cell_no,wake_isi,nrem_isi,rem_isi,wake_lens,nrem_lens,rem_lens,wake_timings,nrem_timings,rem_timings
0,caf69,1228_0_12,358.152546,F,wt,ACC,RSU,0.68,0,"[[0.00592, 0.00132, 0.004360000000000001, 0.02...","[[0.15272000000004482, 0.07171999999991385, 0....","[[0.15104000000019369, 0.11567999999988388, 0....","[3320, 320, 20, 1708, 588, 92, 740, 252, 68, 3...","[520, 440, 40, 240, 180, 200, 180, 220, 180, 6...","[160, 40, 100, 20, 40, 60, 100, 40, 108, 80, 3...","[[0.00532, 8.30984, 16.46344, 25.3846, 37.0028...","[[3320.05296, 3328.55344, 3339.40532, 3345.584...","[[3841.05772, 3868.16824, 3891.42572, 3909.411..."
1,caf69,1228_0_12,358.152546,F,wt,ACC,RSU,0.68,1,"[[0.12224, 6.87172, 1.7081599999999995, 2.1617...","[[14.897280000000137, 1.6376399999999194, 6.17...","[[3.8209999999999127, 4.546280000000024, 3.097...","[3320, 320, 20, 1708, 588, 92, 740, 252, 68, 3...","[520, 440, 40, 240, 180, 200, 180, 220, 180, 6...","[160, 40, 100, 20, 40, 60, 100, 40, 108, 80, 3...","[[4e-05, 219.53304, 509.02504, 573.5778, 737.8...","[[3329.31148, 3785.66544], [4008.16452, 4438.9...","[[3859.45592, 3980.94744], [4470.14316, 4478.7..."
2,caf69,1228_0_12,358.152546,F,wt,ACC,RSU,0.52,2,"[[0.06476000000000001, 0.017119999999999996, 0...","[[0.05519999999978609, 0.8142000000002554, 0.0...","[[0.05375999999978376, 0.286200000000008, 0.08...","[3320, 320, 20, 1708, 588, 92, 740, 252, 68, 3...","[520, 440, 40, 240, 180, 200, 180, 220, 180, 6...","[160, 40, 100, 20, 40, 60, 100, 40, 108, 80, 3...","[[0.01684, 22.50024, 46.03396, 66.695, 89.9888...","[[3320.1932, 3372.29616, 3432.87716, 3497.7676...","[[3840.76872, 3894.55876, 3944.32072, 3989.872..."
3,caf69,1228_0_12,358.152546,F,wt,ACC,RSU,0.52,3,"[[0.24439999999999998, 0.27224000000000004, 0....","[[2.0253600000000915, 0.87920000000031, 0.7080...","[[0.6291599999999562, 0.11724000000003798, 0.7...","[3320, 320, 20, 1708, 588, 92, 740, 252, 68, 3...","[520, 440, 40, 240, 180, 200, 180, 220, 180, 6...","[160, 40, 100, 20, 40, 60, 100, 40, 108, 80, 3...","[[0.00892, 22.6154, 48.60976, 73.74956, 91.015...","[[3320.42208, 3368.56088, 3431.02976, 3503.225...","[[3840.58268, 3899.72988, 3942.88864, 3976.861..."
4,caf69,1228_0_12,358.152546,F,wt,ACC,RSU,0.48,4,"[[0.15028000000000002, 0.34468000000000004, 0....","[[0.59996000000001, 0.4675600000000486, 0.8568...","[[2.2804799999998977, 0.46628000000009706, 1.0...","[3320, 320, 20, 1708, 588, 92, 740, 252, 68, 3...","[520, 440, 40, 240, 180, 200, 180, 220, 180, 6...","[160, 40, 100, 20, 40, 60, 100, 40, 108, 80, 3...","[[0.25464, 28.47056, 53.57136, 85.74888, 91.68...","[[3320.71772, 3373.96056, 3425.57584, 3523.176...","[[3841.0414, 3907.79736, 3946.2996, 3986.7532,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5470,bth100,0624_12_24,98.687060,M,wt,V1,RSU,0.68,90,"[[0.020479999999906795, 0.4212400000000116, 0....","[[1.57676, 0.04683999999999999, 0.407960000000...","[[1.6818399999999656, 0.047159999999962565, 0....","[5852, 336, 168, 2548, 676, 3524, 3780, 448, 3...","[592, 692, 68, 484, 324, 196, 380, 472, 256, 5...","[76, 28, 40, 88, 40, 72, 120, 104, 100, 88, 44...","[[668.57176, 707.01432, 740.97008, 767.3638, 7...","[[1.30304, 45.60452, 92.60128, 153.071, 202.79...","[[592.2716, 636.20772, 667.88588], [7214.34452..."
5471,bth100,0624_12_24,98.687060,M,wt,V1,RSU,0.56,91,"[[0.1151199999999335, 0.12744000000009237, 0.0...","[[0.46224, 1.79184, 0.24311999999999978, 0.452...","[[1.3544399999999541, 1.002520000000004, 0.383...","[5852, 336, 168, 2548, 676, 3524, 3780, 448, 3...","[592, 692, 68, 484, 324, 196, 380, 472, 256, 5...","[76, 28, 40, 88, 40, 72, 120, 104, 100, 88, 44...","[[668.24004, 694.74624, 733.93376, 754.5682, 7...","[[0.79468, 44.809, 98.434, 153.49844, 192.7348...","[[592.14768, 617.384, 640.14308, 656.65148, 66..."
5472,bth100,0624_12_24,98.687060,M,wt,V1,RSU,0.52,92,"[[0.2658400000000256, 0.22303999999996904, 0.1...","[[0.04723999999999995, 0.015519999999999978, 1...","[[0.11188000000004195, 0.050520000000005894, 1...","[5852, 336, 168, 2548, 676, 3524, 3780, 448, 3...","[592, 692, 68, 484, 324, 196, 380, 472, 256, 5...","[76, 28, 40, 88, 40, 72, 120, 104, 100, 88, 44...","[[668.0002, 691.67572, 726.4122, 752.80192, 77...","[[0.83096, 18.63536, 35.94724, 58.99576, 72.86...","[[592.35984, 608.945, 626.10488, 651.55616, 66..."
5473,bth100,0624_12_24,98.687060,M,wt,V1,FS,0.24,93,"[[0.0017599999999902138, 0.0036400000000185173...","[[0.05371999999999999, 0.006599999999999939, 0...","[[0.015319999999974243, 0.00952000000006592, 0...","[5852, 336, 168, 2548, 676, 3524, 3780, 448, 3...","[592, 692, 68, 484, 324, 196, 380, 472, 256, 5...","[76, 28, 40, 88, 40, 72, 120, 104, 100, 88, 44...","[[668.059, 671.24976, 674.65804, 677.55264, 68...","[[0.57132, 8.88216, 10.725, 12.5402, 14.50152,...","[[592.0422, 596.30928, 598.21452, 600.23812, 6..."
5474,bth100,0624_12_24,98.687060,M,wt,V1,RSU,0.64,94,"[[0.37239999999997053, 0.11788000000001375, 0....","[[0.07823999999999998, 0.37315999999999994, 0....","[[0.012119999999981701, 1.1850399999999581, 0....","[5852, 336, 168, 2548, 676, 3524, 3780, 448, 3...","[592, 692, 68, 484, 324, 196, 380, 472, 256, 5...","[76, 28, 40, 88, 40, 72, 120, 104, 100, 88, 44...","[[668.07948, 684.70712, 698.44004, 709.13184, ...","[[0.60892, 24.43068, 56.51936, 75.62352, 103.3...","[[592.27164, 610.02992, 623.00304, 639.55592, ..."

In [28]:
with open(f'{begin}filtered_full_animal_isi.pkl', 'wb') as file:
    pickle.dump(filtered_dataset, file)